---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: strmgen
spec:
  name: STRMGen
  category: Media Management
  description: STRMGen is a Python-based tool and web API/UI for generating Jellyfin-compatible .strm files (and optional accompanying metadata) from IPTV/M3U playlists and TMDb data.
  url: &url https://strmgen.${ROOT_DOMAIN}
  # icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/dispatcharr.svg
  access_policy:
    groups:
      - media-managers
  gatus:
    - group: "Applications"
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
