// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class BlockedZone extends pulumi.CustomResource {
    /**
     * Get an existing BlockedZone resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BlockedZoneState, opts?: pulumi.CustomResourceOptions): BlockedZone {
        return new BlockedZone(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'technitium:index/blockedZone:BlockedZone';

    /**
     * Returns true if the given object is an instance of BlockedZone.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BlockedZone {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BlockedZone.__pulumiType;
    }

    /**
     * The domain name to block (e.g., ads.example.com).
     */
    declare public readonly domain: pulumi.Output<string>;

    /**
     * Create a BlockedZone resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BlockedZoneArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BlockedZoneArgs | BlockedZoneState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BlockedZoneState | undefined;
            resourceInputs["domain"] = state?.domain;
        } else {
            const args = argsOrState as BlockedZoneArgs | undefined;
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            resourceInputs["domain"] = args?.domain;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BlockedZone.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering BlockedZone resources.
 */
export interface BlockedZoneState {
    /**
     * The domain name to block (e.g., ads.example.com).
     */
    domain?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a BlockedZone resource.
 */
export interface BlockedZoneArgs {
    /**
     * The domain name to block (e.g., ads.example.com).
     */
    domain: pulumi.Input<string>;
}
