// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class DhcpScope extends pulumi.CustomResource {
    /**
     * Get an existing DhcpScope resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DhcpScopeState, opts?: pulumi.CustomResourceOptions): DhcpScope {
        return new DhcpScope(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'technitium:index/dhcpScope:DhcpScope';

    /**
     * Returns true if the given object is an instance of DhcpScope.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DhcpScope {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DhcpScope.__pulumiType;
    }

    /**
     * Stop dynamic allocation and serve only reserved leases.
     */
    declare public readonly allowOnlyReservedLeases: pulumi.Output<boolean>;
    /**
     * Refuse dynamic allocation for clients with locally administered MAC addresses (privacy/randomized MACs).
     */
    declare public readonly blockLocallyAdministeredMacAddresses: pulumi.Output<boolean>;
    /**
     * Boot file name on the bootstrap TFTP server (file / option 67).
     */
    declare public readonly bootFileName: pulumi.Output<string>;
    /**
     * CAPWAP Access Controller addresses (option 138).
     */
    declare public readonly capwapAcIpAddresses: pulumi.Output<string[] | undefined>;
    /**
     * Overwrite existing DNS A records matching the client domain name for dynamic leases.
     */
    declare public readonly dnsOverwriteForDynamicLease: pulumi.Output<boolean>;
    /**
     * DNS server addresses for clients (option 6). Ignored when use_this_dns_server is true.
     */
    declare public readonly dnsServers: pulumi.Output<string[] | undefined>;
    /**
     * TTL for DNS records created by the DHCP server.
     */
    declare public readonly dnsTtl: pulumi.Output<number>;
    /**
     * Automatically update forward and reverse DNS entries for clients.
     */
    declare public readonly dnsUpdates: pulumi.Output<boolean>;
    /**
     * Domain name for this network (option 15). When set, the DHCP server adds forward and reverse DNS entries for allocations.
     */
    declare public readonly domainName: pulumi.Output<string>;
    /**
     * Domain names clients use as search suffixes (option 119).
     */
    declare public readonly domainSearchLists: pulumi.Output<string[] | undefined>;
    /**
     * Whether the scope is enabled (allocating leases). Default: false. Enabling requires a host interface with a static IP inside the scope subnet.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * The ending IP address of the scope range.
     */
    declare public readonly endingAddress: pulumi.Output<string>;
    /**
     * Address ranges excluded from dynamic allocation.
     */
    declare public readonly exclusions: pulumi.Output<outputs.DhcpScopeExclusion[] | undefined>;
    /**
     * Raw DHCP options not otherwise supported.
     */
    declare public readonly genericOptions: pulumi.Output<outputs.DhcpScopeGenericOption[] | undefined>;
    /**
     * Always use the client MAC address as the lease identifier instead of option 61.
     */
    declare public readonly ignoreClientIdentifierOption: pulumi.Output<boolean>;
    /**
     * Lease time, days component. Default: server default (1).
     */
    declare public readonly leaseTimeDays: pulumi.Output<number>;
    /**
     * Lease time, hours component.
     */
    declare public readonly leaseTimeHours: pulumi.Output<number>;
    /**
     * Lease time, minutes component.
     */
    declare public readonly leaseTimeMinutes: pulumi.Output<number>;
    /**
     * The name of the DHCP scope. Renaming is supported in place.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * NTP server domain names the DHCP server resolves and passes to clients as option 42.
     */
    declare public readonly ntpServerDomainNames: pulumi.Output<string[] | undefined>;
    /**
     * NTP server addresses for clients (option 42).
     */
    declare public readonly ntpServers: pulumi.Output<string[] | undefined>;
    /**
     * Delay in milliseconds before sending DHCPOFFER.
     */
    declare public readonly offerDelayTime: pulumi.Output<number>;
    /**
     * Ping an address before offering it to detect conflicts with statically configured devices.
     */
    declare public readonly pingCheckEnabled: pulumi.Output<boolean>;
    /**
     * Maximum number of ping attempts.
     */
    declare public readonly pingCheckRetries: pulumi.Output<number>;
    /**
     * Ping reply timeout in milliseconds.
     */
    declare public readonly pingCheckTimeout: pulumi.Output<number>;
    /**
     * Inline MAC-to-IP reservations. While this attribute has never been declared the scope leaves the server-side reservation list alone, so standalone technitium.DhcpReservedLease resources can manage it. Do not combine the two styles on the same scope — a declared list (even an empty one) overwrites the server's list on every scope update, and removing the attribute from config clears the list.
     */
    declare public readonly reservedLeases: pulumi.Output<outputs.DhcpScopeReservedLease[] | undefined>;
    /**
     * Default gateway address for clients (option 3).
     */
    declare public readonly routerAddress: pulumi.Output<string>;
    /**
     * Next server (TFTP) address used in bootstrap (siaddr). Defaults to this server's address.
     */
    declare public readonly serverAddress: pulumi.Output<string>;
    /**
     * Bootstrap TFTP server host name (sname / option 66).
     */
    declare public readonly serverHostName: pulumi.Output<string>;
    /**
     * The starting IP address of the scope range.
     */
    declare public readonly startingAddress: pulumi.Output<string>;
    /**
     * Classless static routes pushed to clients (option 121).
     */
    declare public readonly staticRoutes: pulumi.Output<outputs.DhcpScopeStaticRoute[] | undefined>;
    /**
     * The subnet mask of the network (e.g. 255.255.255.0).
     */
    declare public readonly subnetMask: pulumi.Output<string>;
    /**
     * TFTP / VoIP configuration server addresses (option 150).
     */
    declare public readonly tftpServerAddresses: pulumi.Output<string[] | undefined>;
    /**
     * Advertise this DNS server's address as the DNS server for clients (overrides dns_servers).
     */
    declare public readonly useThisDnsServer: pulumi.Output<boolean>;
    /**
     * Vendor-specific information entries (option 43).
     */
    declare public readonly vendorInfos: pulumi.Output<outputs.DhcpScopeVendorInfo[] | undefined>;
    /**
     * NBNS/WINS server addresses for clients (option 44).
     */
    declare public readonly winsServers: pulumi.Output<string[] | undefined>;

    /**
     * Create a DhcpScope resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DhcpScopeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DhcpScopeArgs | DhcpScopeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DhcpScopeState | undefined;
            resourceInputs["allowOnlyReservedLeases"] = state?.allowOnlyReservedLeases;
            resourceInputs["blockLocallyAdministeredMacAddresses"] = state?.blockLocallyAdministeredMacAddresses;
            resourceInputs["bootFileName"] = state?.bootFileName;
            resourceInputs["capwapAcIpAddresses"] = state?.capwapAcIpAddresses;
            resourceInputs["dnsOverwriteForDynamicLease"] = state?.dnsOverwriteForDynamicLease;
            resourceInputs["dnsServers"] = state?.dnsServers;
            resourceInputs["dnsTtl"] = state?.dnsTtl;
            resourceInputs["dnsUpdates"] = state?.dnsUpdates;
            resourceInputs["domainName"] = state?.domainName;
            resourceInputs["domainSearchLists"] = state?.domainSearchLists;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["endingAddress"] = state?.endingAddress;
            resourceInputs["exclusions"] = state?.exclusions;
            resourceInputs["genericOptions"] = state?.genericOptions;
            resourceInputs["ignoreClientIdentifierOption"] = state?.ignoreClientIdentifierOption;
            resourceInputs["leaseTimeDays"] = state?.leaseTimeDays;
            resourceInputs["leaseTimeHours"] = state?.leaseTimeHours;
            resourceInputs["leaseTimeMinutes"] = state?.leaseTimeMinutes;
            resourceInputs["name"] = state?.name;
            resourceInputs["ntpServerDomainNames"] = state?.ntpServerDomainNames;
            resourceInputs["ntpServers"] = state?.ntpServers;
            resourceInputs["offerDelayTime"] = state?.offerDelayTime;
            resourceInputs["pingCheckEnabled"] = state?.pingCheckEnabled;
            resourceInputs["pingCheckRetries"] = state?.pingCheckRetries;
            resourceInputs["pingCheckTimeout"] = state?.pingCheckTimeout;
            resourceInputs["reservedLeases"] = state?.reservedLeases;
            resourceInputs["routerAddress"] = state?.routerAddress;
            resourceInputs["serverAddress"] = state?.serverAddress;
            resourceInputs["serverHostName"] = state?.serverHostName;
            resourceInputs["startingAddress"] = state?.startingAddress;
            resourceInputs["staticRoutes"] = state?.staticRoutes;
            resourceInputs["subnetMask"] = state?.subnetMask;
            resourceInputs["tftpServerAddresses"] = state?.tftpServerAddresses;
            resourceInputs["useThisDnsServer"] = state?.useThisDnsServer;
            resourceInputs["vendorInfos"] = state?.vendorInfos;
            resourceInputs["winsServers"] = state?.winsServers;
        } else {
            const args = argsOrState as DhcpScopeArgs | undefined;
            if (args?.endingAddress === undefined && !opts.urn) {
                throw new Error("Missing required property 'endingAddress'");
            }
            if (args?.startingAddress === undefined && !opts.urn) {
                throw new Error("Missing required property 'startingAddress'");
            }
            if (args?.subnetMask === undefined && !opts.urn) {
                throw new Error("Missing required property 'subnetMask'");
            }
            resourceInputs["allowOnlyReservedLeases"] = args?.allowOnlyReservedLeases;
            resourceInputs["blockLocallyAdministeredMacAddresses"] = args?.blockLocallyAdministeredMacAddresses;
            resourceInputs["bootFileName"] = args?.bootFileName;
            resourceInputs["capwapAcIpAddresses"] = args?.capwapAcIpAddresses;
            resourceInputs["dnsOverwriteForDynamicLease"] = args?.dnsOverwriteForDynamicLease;
            resourceInputs["dnsServers"] = args?.dnsServers;
            resourceInputs["dnsTtl"] = args?.dnsTtl;
            resourceInputs["dnsUpdates"] = args?.dnsUpdates;
            resourceInputs["domainName"] = args?.domainName;
            resourceInputs["domainSearchLists"] = args?.domainSearchLists;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["endingAddress"] = args?.endingAddress;
            resourceInputs["exclusions"] = args?.exclusions;
            resourceInputs["genericOptions"] = args?.genericOptions;
            resourceInputs["ignoreClientIdentifierOption"] = args?.ignoreClientIdentifierOption;
            resourceInputs["leaseTimeDays"] = args?.leaseTimeDays;
            resourceInputs["leaseTimeHours"] = args?.leaseTimeHours;
            resourceInputs["leaseTimeMinutes"] = args?.leaseTimeMinutes;
            resourceInputs["name"] = args?.name;
            resourceInputs["ntpServerDomainNames"] = args?.ntpServerDomainNames;
            resourceInputs["ntpServers"] = args?.ntpServers;
            resourceInputs["offerDelayTime"] = args?.offerDelayTime;
            resourceInputs["pingCheckEnabled"] = args?.pingCheckEnabled;
            resourceInputs["pingCheckRetries"] = args?.pingCheckRetries;
            resourceInputs["pingCheckTimeout"] = args?.pingCheckTimeout;
            resourceInputs["reservedLeases"] = args?.reservedLeases;
            resourceInputs["routerAddress"] = args?.routerAddress;
            resourceInputs["serverAddress"] = args?.serverAddress;
            resourceInputs["serverHostName"] = args?.serverHostName;
            resourceInputs["startingAddress"] = args?.startingAddress;
            resourceInputs["staticRoutes"] = args?.staticRoutes;
            resourceInputs["subnetMask"] = args?.subnetMask;
            resourceInputs["tftpServerAddresses"] = args?.tftpServerAddresses;
            resourceInputs["useThisDnsServer"] = args?.useThisDnsServer;
            resourceInputs["vendorInfos"] = args?.vendorInfos;
            resourceInputs["winsServers"] = args?.winsServers;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DhcpScope.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering DhcpScope resources.
 */
export interface DhcpScopeState {
    /**
     * Stop dynamic allocation and serve only reserved leases.
     */
    allowOnlyReservedLeases?: pulumi.Input<boolean | undefined>;
    /**
     * Refuse dynamic allocation for clients with locally administered MAC addresses (privacy/randomized MACs).
     */
    blockLocallyAdministeredMacAddresses?: pulumi.Input<boolean | undefined>;
    /**
     * Boot file name on the bootstrap TFTP server (file / option 67).
     */
    bootFileName?: pulumi.Input<string | undefined>;
    /**
     * CAPWAP Access Controller addresses (option 138).
     */
    capwapAcIpAddresses?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Overwrite existing DNS A records matching the client domain name for dynamic leases.
     */
    dnsOverwriteForDynamicLease?: pulumi.Input<boolean | undefined>;
    /**
     * DNS server addresses for clients (option 6). Ignored when use_this_dns_server is true.
     */
    dnsServers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * TTL for DNS records created by the DHCP server.
     */
    dnsTtl?: pulumi.Input<number | undefined>;
    /**
     * Automatically update forward and reverse DNS entries for clients.
     */
    dnsUpdates?: pulumi.Input<boolean | undefined>;
    /**
     * Domain name for this network (option 15). When set, the DHCP server adds forward and reverse DNS entries for allocations.
     */
    domainName?: pulumi.Input<string | undefined>;
    /**
     * Domain names clients use as search suffixes (option 119).
     */
    domainSearchLists?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the scope is enabled (allocating leases). Default: false. Enabling requires a host interface with a static IP inside the scope subnet.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * The ending IP address of the scope range.
     */
    endingAddress?: pulumi.Input<string | undefined>;
    /**
     * Address ranges excluded from dynamic allocation.
     */
    exclusions?: pulumi.Input<pulumi.Input<inputs.DhcpScopeExclusion>[] | undefined>;
    /**
     * Raw DHCP options not otherwise supported.
     */
    genericOptions?: pulumi.Input<pulumi.Input<inputs.DhcpScopeGenericOption>[] | undefined>;
    /**
     * Always use the client MAC address as the lease identifier instead of option 61.
     */
    ignoreClientIdentifierOption?: pulumi.Input<boolean | undefined>;
    /**
     * Lease time, days component. Default: server default (1).
     */
    leaseTimeDays?: pulumi.Input<number | undefined>;
    /**
     * Lease time, hours component.
     */
    leaseTimeHours?: pulumi.Input<number | undefined>;
    /**
     * Lease time, minutes component.
     */
    leaseTimeMinutes?: pulumi.Input<number | undefined>;
    /**
     * The name of the DHCP scope. Renaming is supported in place.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * NTP server domain names the DHCP server resolves and passes to clients as option 42.
     */
    ntpServerDomainNames?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * NTP server addresses for clients (option 42).
     */
    ntpServers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Delay in milliseconds before sending DHCPOFFER.
     */
    offerDelayTime?: pulumi.Input<number | undefined>;
    /**
     * Ping an address before offering it to detect conflicts with statically configured devices.
     */
    pingCheckEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Maximum number of ping attempts.
     */
    pingCheckRetries?: pulumi.Input<number | undefined>;
    /**
     * Ping reply timeout in milliseconds.
     */
    pingCheckTimeout?: pulumi.Input<number | undefined>;
    /**
     * Inline MAC-to-IP reservations. While this attribute has never been declared the scope leaves the server-side reservation list alone, so standalone technitium.DhcpReservedLease resources can manage it. Do not combine the two styles on the same scope — a declared list (even an empty one) overwrites the server's list on every scope update, and removing the attribute from config clears the list.
     */
    reservedLeases?: pulumi.Input<pulumi.Input<inputs.DhcpScopeReservedLease>[] | undefined>;
    /**
     * Default gateway address for clients (option 3).
     */
    routerAddress?: pulumi.Input<string | undefined>;
    /**
     * Next server (TFTP) address used in bootstrap (siaddr). Defaults to this server's address.
     */
    serverAddress?: pulumi.Input<string | undefined>;
    /**
     * Bootstrap TFTP server host name (sname / option 66).
     */
    serverHostName?: pulumi.Input<string | undefined>;
    /**
     * The starting IP address of the scope range.
     */
    startingAddress?: pulumi.Input<string | undefined>;
    /**
     * Classless static routes pushed to clients (option 121).
     */
    staticRoutes?: pulumi.Input<pulumi.Input<inputs.DhcpScopeStaticRoute>[] | undefined>;
    /**
     * The subnet mask of the network (e.g. 255.255.255.0).
     */
    subnetMask?: pulumi.Input<string | undefined>;
    /**
     * TFTP / VoIP configuration server addresses (option 150).
     */
    tftpServerAddresses?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Advertise this DNS server's address as the DNS server for clients (overrides dns_servers).
     */
    useThisDnsServer?: pulumi.Input<boolean | undefined>;
    /**
     * Vendor-specific information entries (option 43).
     */
    vendorInfos?: pulumi.Input<pulumi.Input<inputs.DhcpScopeVendorInfo>[] | undefined>;
    /**
     * NBNS/WINS server addresses for clients (option 44).
     */
    winsServers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a DhcpScope resource.
 */
export interface DhcpScopeArgs {
    /**
     * Stop dynamic allocation and serve only reserved leases.
     */
    allowOnlyReservedLeases?: pulumi.Input<boolean | undefined>;
    /**
     * Refuse dynamic allocation for clients with locally administered MAC addresses (privacy/randomized MACs).
     */
    blockLocallyAdministeredMacAddresses?: pulumi.Input<boolean | undefined>;
    /**
     * Boot file name on the bootstrap TFTP server (file / option 67).
     */
    bootFileName?: pulumi.Input<string | undefined>;
    /**
     * CAPWAP Access Controller addresses (option 138).
     */
    capwapAcIpAddresses?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Overwrite existing DNS A records matching the client domain name for dynamic leases.
     */
    dnsOverwriteForDynamicLease?: pulumi.Input<boolean | undefined>;
    /**
     * DNS server addresses for clients (option 6). Ignored when use_this_dns_server is true.
     */
    dnsServers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * TTL for DNS records created by the DHCP server.
     */
    dnsTtl?: pulumi.Input<number | undefined>;
    /**
     * Automatically update forward and reverse DNS entries for clients.
     */
    dnsUpdates?: pulumi.Input<boolean | undefined>;
    /**
     * Domain name for this network (option 15). When set, the DHCP server adds forward and reverse DNS entries for allocations.
     */
    domainName?: pulumi.Input<string | undefined>;
    /**
     * Domain names clients use as search suffixes (option 119).
     */
    domainSearchLists?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether the scope is enabled (allocating leases). Default: false. Enabling requires a host interface with a static IP inside the scope subnet.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * The ending IP address of the scope range.
     */
    endingAddress: pulumi.Input<string>;
    /**
     * Address ranges excluded from dynamic allocation.
     */
    exclusions?: pulumi.Input<pulumi.Input<inputs.DhcpScopeExclusion>[] | undefined>;
    /**
     * Raw DHCP options not otherwise supported.
     */
    genericOptions?: pulumi.Input<pulumi.Input<inputs.DhcpScopeGenericOption>[] | undefined>;
    /**
     * Always use the client MAC address as the lease identifier instead of option 61.
     */
    ignoreClientIdentifierOption?: pulumi.Input<boolean | undefined>;
    /**
     * Lease time, days component. Default: server default (1).
     */
    leaseTimeDays?: pulumi.Input<number | undefined>;
    /**
     * Lease time, hours component.
     */
    leaseTimeHours?: pulumi.Input<number | undefined>;
    /**
     * Lease time, minutes component.
     */
    leaseTimeMinutes?: pulumi.Input<number | undefined>;
    /**
     * The name of the DHCP scope. Renaming is supported in place.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * NTP server domain names the DHCP server resolves and passes to clients as option 42.
     */
    ntpServerDomainNames?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * NTP server addresses for clients (option 42).
     */
    ntpServers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Delay in milliseconds before sending DHCPOFFER.
     */
    offerDelayTime?: pulumi.Input<number | undefined>;
    /**
     * Ping an address before offering it to detect conflicts with statically configured devices.
     */
    pingCheckEnabled?: pulumi.Input<boolean | undefined>;
    /**
     * Maximum number of ping attempts.
     */
    pingCheckRetries?: pulumi.Input<number | undefined>;
    /**
     * Ping reply timeout in milliseconds.
     */
    pingCheckTimeout?: pulumi.Input<number | undefined>;
    /**
     * Inline MAC-to-IP reservations. While this attribute has never been declared the scope leaves the server-side reservation list alone, so standalone technitium.DhcpReservedLease resources can manage it. Do not combine the two styles on the same scope — a declared list (even an empty one) overwrites the server's list on every scope update, and removing the attribute from config clears the list.
     */
    reservedLeases?: pulumi.Input<pulumi.Input<inputs.DhcpScopeReservedLease>[] | undefined>;
    /**
     * Default gateway address for clients (option 3).
     */
    routerAddress?: pulumi.Input<string | undefined>;
    /**
     * Next server (TFTP) address used in bootstrap (siaddr). Defaults to this server's address.
     */
    serverAddress?: pulumi.Input<string | undefined>;
    /**
     * Bootstrap TFTP server host name (sname / option 66).
     */
    serverHostName?: pulumi.Input<string | undefined>;
    /**
     * The starting IP address of the scope range.
     */
    startingAddress: pulumi.Input<string>;
    /**
     * Classless static routes pushed to clients (option 121).
     */
    staticRoutes?: pulumi.Input<pulumi.Input<inputs.DhcpScopeStaticRoute>[] | undefined>;
    /**
     * The subnet mask of the network (e.g. 255.255.255.0).
     */
    subnetMask: pulumi.Input<string>;
    /**
     * TFTP / VoIP configuration server addresses (option 150).
     */
    tftpServerAddresses?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Advertise this DNS server's address as the DNS server for clients (overrides dns_servers).
     */
    useThisDnsServer?: pulumi.Input<boolean | undefined>;
    /**
     * Vendor-specific information entries (option 43).
     */
    vendorInfos?: pulumi.Input<pulumi.Input<inputs.DhcpScopeVendorInfo>[] | undefined>;
    /**
     * NBNS/WINS server addresses for clients (option 44).
     */
    winsServers?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
