// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDhcpLeases(args?: GetDhcpLeasesArgs, opts?: pulumi.InvokeOptions): Promise<GetDhcpLeasesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("technitium:index/getDhcpLeases:getDhcpLeases", {
        "scope": args.scope,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDhcpLeases.
 */
export interface GetDhcpLeasesArgs {
    scope?: string;
}

/**
 * A collection of values returned by getDhcpLeases.
 */
export interface GetDhcpLeasesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly leases: outputs.GetDhcpLeasesLease[];
    readonly scope?: string;
}
export function getDhcpLeasesOutput(args?: GetDhcpLeasesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDhcpLeasesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("technitium:index/getDhcpLeases:getDhcpLeases", {
        "scope": args.scope,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDhcpLeases.
 */
export interface GetDhcpLeasesOutputArgs {
    scope?: pulumi.Input<string | undefined>;
}
