// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AllowedZoneArgs, AllowedZoneState } from "./allowedZone";
export type AllowedZone = import("./allowedZone").AllowedZone;
export const AllowedZone: typeof import("./allowedZone").AllowedZone = null as any;
utilities.lazyLoad(exports, ["AllowedZone"], () => require("./allowedZone"));

export { AllowedZonesArgs, AllowedZonesState } from "./allowedZones";
export type AllowedZones = import("./allowedZones").AllowedZones;
export const AllowedZones: typeof import("./allowedZones").AllowedZones = null as any;
utilities.lazyLoad(exports, ["AllowedZones"], () => require("./allowedZones"));

export { BlockedZoneArgs, BlockedZoneState } from "./blockedZone";
export type BlockedZone = import("./blockedZone").BlockedZone;
export const BlockedZone: typeof import("./blockedZone").BlockedZone = null as any;
utilities.lazyLoad(exports, ["BlockedZone"], () => require("./blockedZone"));

export { BlockedZonesArgs, BlockedZonesState } from "./blockedZones";
export type BlockedZones = import("./blockedZones").BlockedZones;
export const BlockedZones: typeof import("./blockedZones").BlockedZones = null as any;
utilities.lazyLoad(exports, ["BlockedZones"], () => require("./blockedZones"));

export { CatalogMembershipArgs, CatalogMembershipState } from "./catalogMembership";
export type CatalogMembership = import("./catalogMembership").CatalogMembership;
export const CatalogMembership: typeof import("./catalogMembership").CatalogMembership = null as any;
utilities.lazyLoad(exports, ["CatalogMembership"], () => require("./catalogMembership"));

export { GetAllowedZoneArgs, GetAllowedZoneResult, GetAllowedZoneOutputArgs } from "./getAllowedZone";
export const getAllowedZone: typeof import("./getAllowedZone").getAllowedZone = null as any;
export const getAllowedZoneOutput: typeof import("./getAllowedZone").getAllowedZoneOutput = null as any;
utilities.lazyLoad(exports, ["getAllowedZone","getAllowedZoneOutput"], () => require("./getAllowedZone"));

export { GetAllowedZonesResult } from "./getAllowedZones";
export const getAllowedZones: typeof import("./getAllowedZones").getAllowedZones = null as any;
export const getAllowedZonesOutput: typeof import("./getAllowedZones").getAllowedZonesOutput = null as any;
utilities.lazyLoad(exports, ["getAllowedZones","getAllowedZonesOutput"], () => require("./getAllowedZones"));

export { GetBlockedZoneArgs, GetBlockedZoneResult, GetBlockedZoneOutputArgs } from "./getBlockedZone";
export const getBlockedZone: typeof import("./getBlockedZone").getBlockedZone = null as any;
export const getBlockedZoneOutput: typeof import("./getBlockedZone").getBlockedZoneOutput = null as any;
utilities.lazyLoad(exports, ["getBlockedZone","getBlockedZoneOutput"], () => require("./getBlockedZone"));

export { GetBlockedZonesResult } from "./getBlockedZones";
export const getBlockedZones: typeof import("./getBlockedZones").getBlockedZones = null as any;
export const getBlockedZonesOutput: typeof import("./getBlockedZones").getBlockedZonesOutput = null as any;
utilities.lazyLoad(exports, ["getBlockedZones","getBlockedZonesOutput"], () => require("./getBlockedZones"));

export { GetRecordArgs, GetRecordResult, GetRecordOutputArgs } from "./getRecord";
export const getRecord: typeof import("./getRecord").getRecord = null as any;
export const getRecordOutput: typeof import("./getRecord").getRecordOutput = null as any;
utilities.lazyLoad(exports, ["getRecord","getRecordOutput"], () => require("./getRecord"));

export { GetServerSettingsResult } from "./getServerSettings";
export const getServerSettings: typeof import("./getServerSettings").getServerSettings = null as any;
export const getServerSettingsOutput: typeof import("./getServerSettings").getServerSettingsOutput = null as any;
utilities.lazyLoad(exports, ["getServerSettings","getServerSettingsOutput"], () => require("./getServerSettings"));

export { GetTsigKeyArgs, GetTsigKeyResult, GetTsigKeyOutputArgs } from "./getTsigKey";
export const getTsigKey: typeof import("./getTsigKey").getTsigKey = null as any;
export const getTsigKeyOutput: typeof import("./getTsigKey").getTsigKeyOutput = null as any;
utilities.lazyLoad(exports, ["getTsigKey","getTsigKeyOutput"], () => require("./getTsigKey"));

export { GetZoneArgs, GetZoneResult, GetZoneOutputArgs } from "./getZone";
export const getZone: typeof import("./getZone").getZone = null as any;
export const getZoneOutput: typeof import("./getZone").getZoneOutput = null as any;
utilities.lazyLoad(exports, ["getZone","getZoneOutput"], () => require("./getZone"));

export * from "./provider";
import { Provider } from "./provider";

export { RecordArgs, RecordState } from "./record";
export type Record = import("./record").Record;
export const Record: typeof import("./record").Record = null as any;
utilities.lazyLoad(exports, ["Record"], () => require("./record"));

export { ServerSettingsArgs, ServerSettingsState } from "./serverSettings";
export type ServerSettings = import("./serverSettings").ServerSettings;
export const ServerSettings: typeof import("./serverSettings").ServerSettings = null as any;
utilities.lazyLoad(exports, ["ServerSettings"], () => require("./serverSettings"));

export { TsigKeyArgs, TsigKeyState } from "./tsigKey";
export type TsigKey = import("./tsigKey").TsigKey;
export const TsigKey: typeof import("./tsigKey").TsigKey = null as any;
utilities.lazyLoad(exports, ["TsigKey"], () => require("./tsigKey"));

export { ZoneArgs, ZoneState } from "./zone";
export type Zone = import("./zone").Zone;
export const Zone: typeof import("./zone").Zone = null as any;
utilities.lazyLoad(exports, ["Zone"], () => require("./zone"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "technitium:index/allowedZone:AllowedZone":
                return new AllowedZone(name, <any>undefined, { urn })
            case "technitium:index/allowedZones:AllowedZones":
                return new AllowedZones(name, <any>undefined, { urn })
            case "technitium:index/blockedZone:BlockedZone":
                return new BlockedZone(name, <any>undefined, { urn })
            case "technitium:index/blockedZones:BlockedZones":
                return new BlockedZones(name, <any>undefined, { urn })
            case "technitium:index/catalogMembership:CatalogMembership":
                return new CatalogMembership(name, <any>undefined, { urn })
            case "technitium:index/record:Record":
                return new Record(name, <any>undefined, { urn })
            case "technitium:index/serverSettings:ServerSettings":
                return new ServerSettings(name, <any>undefined, { urn })
            case "technitium:index/tsigKey:TsigKey":
                return new TsigKey(name, <any>undefined, { urn })
            case "technitium:index/zone:Zone":
                return new Zone(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("technitium", "index/allowedZone", _module)
pulumi.runtime.registerResourceModule("technitium", "index/allowedZones", _module)
pulumi.runtime.registerResourceModule("technitium", "index/blockedZone", _module)
pulumi.runtime.registerResourceModule("technitium", "index/blockedZones", _module)
pulumi.runtime.registerResourceModule("technitium", "index/catalogMembership", _module)
pulumi.runtime.registerResourceModule("technitium", "index/record", _module)
pulumi.runtime.registerResourceModule("technitium", "index/serverSettings", _module)
pulumi.runtime.registerResourceModule("technitium", "index/tsigKey", _module)
pulumi.runtime.registerResourceModule("technitium", "index/zone", _module)
pulumi.runtime.registerResourcePackage("technitium", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:technitium") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
