services:
  dockge:
    image: louislam/dockge:1@sha256:335c6368b880ecc203236ed89e6e5232e0d6578e8ef5920e4a502390451502bf
    labels:
      # Enable Traefik
      traefik.enable: true

      traefik.http.routers.dockge.rule: Host(`dockge.${CLUSTER_DOMAIN}`)
      traefik.http.routers.dockge.middlewares: authentik-outpost@docker
      traefik.http.routers.dockge.entrypoints: websecure
      traefik.http.routers.dockge.service: dockge
      traefik.http.routers.dockge.tls.certresolver: le

      traefik.http.services.dockge.loadbalancer.server.port: 5001
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data

      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
    networks:
      - dockge_default
    restart: unless-stopped
    dns:
      - 100.100.100.100

networks:
  dockge_default:
    external: true
x-dockge:
  urls:
    - https://dockge.${CLUSTER_DOMAIN}
