services:
  traefik:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest@sha256:4ce403579f0e52e49f061ff90e89be7b7049b79a0c525482f88ea238bf8f059a
    restart: unless-stopped
    dns:
      - 100.100.100.100
    labels:
      # Enable Traefik for itself
      traefik.enable: true
      # Dashboard configuration
      traefik.http.routers.librespeed.rule: Host(`librespeed.${CLUSTER_DOMAIN}`)
      traefik.http.routers.librespeed.entrypoints: websecure
      traefik.http.routers.librespeed.service: librespeed
      traefik.http.routers.librespeed.tls.certresolver: le

      traefik.http.services.librespeed.loadbalancer.server.port: 8080
    networks:
      - dockge_default
x-dockge:
  urls:
    - https://librespeed.${CLUSTER_DOMAIN}
networks:
  dockge_default:
    external: true
