services:
  traefik:
    container_name: speedtest
    image: ghcr.io/librespeed/speedtest:latest@sha256:62ac13abfc1863e6c4741febb8f6af3d5c3499bb8af980ac864b6f8c439a85ba
    restart: unless-stopped
    dns:
      - 100.100.100.100
    labels:
      # Enable Traefik for itself
      traefik.enable: true
      # Dashboard configuration
      traefik.http.routers.librespeed.rule: Host(`librespeed.${CLUSTER_DOMAIN}`)
      traefik.http.routers.librespeed.entrypoints: websecure
      traefik.http.routers.librespeed.service: librespeed
      traefik.http.routers.librespeed.tls.certresolver: le

      traefik.http.services.librespeed.loadbalancer.server.port: 8080
    environment:
      - USE_NEW_DESIGN=true
      - TELEMETRY=false
      - ENABLE_ID_OBFUSCATION=false
      - REDACT_IP_ADDRESSES=false
    networks:
      - dockge_default
x-dockge:
  urls:
    - https://librespeed.${CLUSTER_DOMAIN}
networks:
  dockge_default:
    external: true
