---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-env
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        DB_TYPE: postgresdb
        DB_POSTGRESDB_PORT: "{{ .postgres_port }}"
        DB_POSTGRESDB_DATABASE: "{{ .postgres_database }}"
        DB_POSTGRESDB_HOST: "{{ .postgres_hostname }}"
        DB_POSTGRESDB_USER: "{{ .postgres_username }}"
        DB_POSTGRESDB_PASSWORD: "{{ .postgres_password }}"
        N8N_ENCRYPTION_KEY: "{{ .n8n_password }}"
        N8N_LICENSE_ACTIVATION_KEY: "{{ .n8n_license_key }}"
  dataFrom:
    - extract:
        # was: N8N
        key: shared/n8n
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "n8n_$1"
    - extract:
        key: '${APP}-postgres'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
