services:
  authentik_proxy:
    image: ghcr.io/goauthentik/proxy:2025.8.4
    ports:
      - 9000:9000
      - 9443:9443
    # env is set in each app stack for the secret.
    env_file:
      - .env
    labels:
      traefik.enable: true
      # Outpust
      traefik.http.routers.outpostle: Host(`outpostCLUSTER_KEY}.driscoll.tech`)
      traefik.http.routers.outpost.entrypoints: websecure
      traefik.http.routers.outpost.service: outpost
      traefik.http.routers.outpost.tls.certresolver: le
      traefik.http.services.outpost.loadbalancer.healthcheck.path: "/outpost.goauthentik.io/ping"
      traefik.http.services.outpost.loadbalancer.healthcheck.port: 9300
      traefik.http.services.outpost.loadbalancer.server.port: 9000

      # The middleware
      traefik.http.middlewares.authentik.forwardauth.address: http://authentik_proxy:9000/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
    networks:
      - dockge_default
x-dockge:
  urls:
    - https://outpost.${CLUSTER_KEY}.driscoll.tech
networks:
  dockge_default:
    external: true
