[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
AWS_ACCESS_KEY_ID = "op://Eris/minio root user/username"
AWS_SECRET_ACCESS_KEY = "op://Eris/minio root user/password"
AWS_REGION = "home"
PULUMI_CONFIG_PASSPHRASE = "op://Eris/Pulumi Passphrase/password"
CONNECT_HOST = "https://op-connect.equestria.driscoll.tech/"
CONNECT_VAULT = "Eris"
CONNECT_TOKEN = "op://Eris/OnePassword Connect Token/credential"
AUTHENTIK_TOKEN = "op://Eris/Authentik Token/credential"
AUTHENTIK_URL = "op://Eris/Authentik Token/url"

[tools]
kubectl = "1.34.1"
powershell-core = "7.5.1"
1password-cli = "2.30.3"
yq = "4.48.1"
jq = "1.8.1"
task = "3.44.0"
sops = "3.10.2"
flux2 = "2.7.3"
age = "1.2.1"
gh = "2.74.2"
"npm:typescript" = "5.9.3"
node = "24.8.0"
