[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
AWS_ACCESS_KEY_ID = "op://Private/Backblaze home-operations/username"
AWS_SECRET_ACCESS_KEY = "op://Private/Backblaze home-operations/credential"
AWS_REGION = "us-east-005"
AWS_USE_PATH_STYLE_ENDPOINT = "true"
PULUMI_CONFIG_PASSPHRASE = "op://Eris/Pulumi Passphrase/password"
CONNECT_HOST = "https://op-connect.equestria.driscoll.tech/"
CONNECT_VAULT = "Eris"
CONNECT_TOKEN = "op://Eris/OnePassword Connect Token/credential"

[tools]
kubectl = "1.33.0"
powershell-core = "7.5.1"
1password-cli = "2.30.3"
yq = "4.45.4"
jq = "1.8.0"
task = "3.44.0"
sops = "3.10.2"
flux2 = "2.6.3"
age = "1.2.1"
gh = "2.74.2"
"npm:typescript" = "5.9.2"
node = "24.8.0"
