// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface FirewallPolicyDestination {
    /**
     * Client device MAC addresses to match. Use the `mac` attribute from `terrifi.ClientDevice` resources.
     */
    deviceIds?: string[];
    /**
     * IP addresses or CIDR ranges to match.
     */
    ips?: string[];
    /**
     * MAC addresses to match.
     */
    macAddresses?: string[];
    /**
     * Inverts IP matching. When `true` and action is `ALLOW`, all IPs except the specified ones are allowed. When `true` and action is `BLOCK`, all IPs except the specified ones are blocked.
     */
    matchOppositeIps?: boolean;
    /**
     * Inverts port matching. When `true` and action is `ALLOW`, all ports except the specified ones are allowed. When `true` and action is `BLOCK`, all ports except the specified ones are blocked.
     */
    matchOppositePorts?: boolean;
    /**
     * Network IDs to match.
     */
    networkIds?: string[];
    /**
     * Specific port number to match (when `port_matching_type` is `SPECIFIC`).
     */
    port?: number;
    /**
     * Port group ID to match (when `port_matching_type` is `OBJECT`).
     */
    portGroupId?: string;
    /**
     * Port matching type. Valid values: `ANY`, `SPECIFIC`, `OBJECT`. Default: `ANY`. Automatically derived when `port` or `port_group_id` is set.
     */
    portMatchingType: string;
    /**
     * The ID of the firewall zone.
     */
    zoneId: string;
}

export interface FirewallPolicySchedule {
    /**
     * Date for one-time schedules.
     */
    date?: string;
    /**
     * Schedule mode. Valid values: `ALWAYS`, `EVERY_DAY`, `EVERY_WEEK`, `ONE_TIME_ONLY`.
     */
    mode?: string;
    /**
     * Days of the week to repeat on. Valid values: `mon`, `tue`, `wed`, `thu`, `fri`, `sat`, `sun`.
     */
    repeatOnDays?: string[];
    /**
     * Whether the schedule applies all day.
     */
    timeAllDay?: boolean;
    /**
     * End time for the schedule (e.g. `17:00`).
     */
    timeRangeEnd?: string;
    /**
     * Start time for the schedule (e.g. `08:00`).
     */
    timeRangeStart?: string;
}

export interface FirewallPolicySource {
    /**
     * Client device MAC addresses to match. Use the `mac` attribute from `terrifi.ClientDevice` resources.
     */
    deviceIds?: string[];
    /**
     * IP addresses or CIDR ranges to match.
     */
    ips?: string[];
    /**
     * MAC addresses to match.
     */
    macAddresses?: string[];
    /**
     * Inverts IP matching. When `true` and action is `ALLOW`, all IPs except the specified ones are allowed. When `true` and action is `BLOCK`, all IPs except the specified ones are blocked.
     */
    matchOppositeIps?: boolean;
    /**
     * Inverts port matching. When `true` and action is `ALLOW`, all ports except the specified ones are allowed. When `true` and action is `BLOCK`, all ports except the specified ones are blocked.
     */
    matchOppositePorts?: boolean;
    /**
     * Network IDs to match.
     */
    networkIds?: string[];
    /**
     * Specific port number to match (when `port_matching_type` is `SPECIFIC`).
     */
    port?: number;
    /**
     * Port group ID to match (when `port_matching_type` is `OBJECT`).
     */
    portGroupId?: string;
    /**
     * Port matching type. Valid values: `ANY`, `SPECIFIC`, `OBJECT`. Default: `ANY`. Automatically derived when `port` or `port_group_id` is set.
     */
    portMatchingType: string;
    /**
     * The ID of the firewall zone.
     */
    zoneId: string;
}

