---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./ersatztv/ks.yaml
  # - ./fhdhr/ks.yaml
  # - ./iptv-sync/ks.yaml
  # - ./nextpvr/ks.yaml
  # - ./threadfin/ks.yaml
  - ./dispatcharr/ks.yaml
  - ./ecm/ks.yaml
  - ./game-thumbs/ks.yaml
  - ./identifiarr/ks.yaml
  - ./teamarr/ks.yaml
  - ./kptv-fast/ks.yaml
  - ./xcproxy/ks.yaml
  # - ./strmgen/ks.yaml
