#!/usr/bin/env -S npx tsx
/**
 * 1Password -> OpenBao migration tool.
 *
 *   --plan     walk the Eris vault, write mapping.yaml for review
 *   --apply    read mapping.yaml, write the items into OpenBao
 *   --verify   compare both sides field by field, report drift
 *
 * --plan and --apply are separate on purpose. The path scheme cannot be derived
 * from titles alone with enough confidence to write blind, so a human reviews
 * mapping.yaml first and the result is committed alongside the code.
 *
 * Env: CONNECT_HOST / CONNECT_TOKEN (1Password), BAO_ADDR / BAO_TOKEN (OpenBao).
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseYAML, stringifyYAML } from "confbox";
import { OPClient } from "@components/op.ts";
import { BaoClient } from "./bao.ts";
import { classify, describe, toPayload, type MappingEntry, type OPItem } from "./mapping.ts";

const MAPPING_PATH = join(dirname(fileURLToPath(import.meta.url)), "mapping.yaml");

function loadMapping(): MappingEntry[] {
  let raw: string;
  try {
    raw = readFileSync(MAPPING_PATH, "utf8");
  } catch {
    throw new Error(`${MAPPING_PATH} not found — run --plan first, then review it.`);
  }
  const parsed = parseYAML<{ items?: MappingEntry[] }>(raw);
  if (!parsed?.items?.length) throw new Error(`${MAPPING_PATH} has no items.`);
  return parsed.items;
}

/** Every item in Eris, from the unfiltered list endpoint (stubs only — values re-fetched below). */
async function allItems(op: OPClient): Promise<OPItem[]> {
  const stubs = await op.listAllItems();
  const items: OPItem[] = [];
  for (const stub of stubs) {
    // Re-fetch by id: the list endpoint omits field values.
    items.push(await op.getItemById(stub.id));
  }
  return items.sort((a, b) => a.title.localeCompare(b.title));
}

async function plan(): Promise<number> {
  const op = new OPClient();
  const items = await allItems(op);

  const entries: MappingEntry[] = items.map(item => ({ ...classify(item), ...describe(item) }));

  // Collisions are the failure mode that would silently overwrite one secret
  // with another, so they are a hard error rather than a warning. Skipped
  // entries are excluded: --apply never writes them, so they cannot collide.
  const byPath = new Map<string, MappingEntry[]>();
  for (const e of entries.filter(e => !e.skip)) {
    const key = `${e.mount}/${e.path}`;
    byPath.set(key, [...(byPath.get(key) ?? []), e]);
  }
  const collisions = [...byPath.entries()].filter(([, v]) => v.length > 1);

  writeFileSync(
    MAPPING_PATH,
    `# Generated by scripts/op-to-bao --plan. REVIEW BEFORE --apply.\n` +
      `#\n` +
      `# Every entry with 'review: true' needs a human decision. Set 'skip: true'\n` +
      `# to exclude an item (inventory that belongs in Pulumi stack outputs,\n` +
      `# obsolete entries, personal-scope credentials). Correct 'path' freely —\n` +
      `# --apply reads this file, not the classifier.\n` +
      `#\n` +
      `# Field VALUES are never written here, only labels.\n\n` +
      stringifyYAML({ items: entries }),
    "utf8",
  );

  const needsReview = entries.filter(e => e.review).length;
  console.log(`planned ${entries.length} items -> ${MAPPING_PATH}`);
  console.log(`  ${needsReview} need review, ${entries.filter(e => e.skip).length} pre-marked skip`);
  if (collisions.length > 0) {
    console.error(`\n${collisions.length} PATH COLLISION(S) — fix these in mapping.yaml before --apply:`);
    for (const [path, group] of collisions) console.error(`  ${path}\n    <- ${group.map(g => g.title).join("\n    <- ")}`);
    return 1;
  }
  return 0;
}

async function apply(dryRun: boolean): Promise<number> {
  const op = new OPClient();
  const bao = new BaoClient();
  const migratedAt = new Date().toISOString();
  const entries = loadMapping().filter(e => !e.skip);

  let written = 0;
  let unchanged = 0;
  let failed = 0;

  for (const entry of entries) {
    try {
      const item = await op.getItemById(entry.uuid);
      const { data, customMetadata } = toPayload(item, migratedAt);

      const existing = await bao.read(entry.mount, entry.path);
      // Compare against what is already there so re-runs are no-ops. Key order
      // is not meaningful in KV v2, so compare canonicalised JSON.
      if (existing && canonical(existing.data) === canonical(data)) {
        unchanged++;
        continue;
      }

      if (dryRun) {
        console.log(`would write ${entry.mount}/${entry.path}  (${Object.keys(data).length} keys)`);
        written++;
        continue;
      }

      // cas 0 creates only if absent; cas <current version> updates only if
      // nothing moved underneath. Either way a concurrent writer errors rather
      // than being clobbered.
      await bao.write(entry.mount, entry.path, data, existing ? existing.metadata.version : 0);
      await bao.writeCustomMetadata(entry.mount, entry.path, customMetadata);
      console.log(`wrote ${entry.mount}/${entry.path}`);
      written++;
    } catch (e) {
      console.error(`FAILED ${entry.mount}/${entry.path} (${entry.title}): ${(e as Error).message}`);
      failed++;
    }
  }

  console.log(`\n${dryRun ? "dry-run: " : ""}${written} written, ${unchanged} unchanged, ${failed} failed`);
  return failed > 0 ? 1 : 0;
}

async function verify(): Promise<number> {
  const op = new OPClient();
  const bao = new BaoClient();
  const entries = loadMapping().filter(e => !e.skip);

  let ok = 0;
  const problems: string[] = [];

  for (const entry of entries) {
    const target = `${entry.mount}/${entry.path}`;
    try {
      const item = await op.getItemById(entry.uuid);
      const { data } = toPayload(item, "");
      const existing = await bao.read(entry.mount, entry.path);

      if (!existing) {
        problems.push(`MISSING  ${target}  (${entry.title})`);
        continue;
      }
      if (canonical(existing.data) !== canonical(data)) {
        // Report which keys differ, never the values — this output is meant to
        // be safe to paste into an issue.
        const opKeys = new Set(Object.keys(data));
        const baoKeys = new Set(Object.keys(existing.data));
        const onlyOp = [...opKeys].filter(k => !baoKeys.has(k));
        const onlyBao = [...baoKeys].filter(k => !opKeys.has(k));
        const changed = [...opKeys].filter(k => baoKeys.has(k) && canonical(data[k]) !== canonical(existing.data[k]));
        problems.push(
          `DRIFT    ${target}  (${entry.title})` +
            (onlyOp.length ? `\n           only in 1Password: ${onlyOp.join(", ")}` : "") +
            (onlyBao.length ? `\n           only in OpenBao:   ${onlyBao.join(", ")}` : "") +
            (changed.length ? `\n           differing values:  ${changed.join(", ")}` : ""),
        );
        continue;
      }
      ok++;
    } catch (e) {
      problems.push(`ERROR    ${target}: ${(e as Error).message}`);
    }
  }

  for (const p of problems) console.error(p);
  console.log(`\n${ok}/${entries.length} in sync, ${problems.length} problem(s)`);
  return problems.length > 0 ? 1 : 0;
}

/** Stable stringify so key order never registers as a difference. */
function canonical(value: unknown): string {
  return JSON.stringify(value, (_k, v) =>
    v && typeof v === "object" && !Array.isArray(v)
      ? Object.fromEntries(Object.entries(v as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)))
      : v,
  );
}

const mode = process.argv[2];
const exitCode = await (mode === "--plan"
  ? plan()
  : mode === "--apply"
    ? apply(process.argv.includes("--dry-run"))
    : mode === "--verify"
      ? verify()
      : (() => {
          console.error("usage: op-to-bao --plan | --apply [--dry-run] | --verify");
          return Promise.resolve(2);
        })());

process.exit(exitCode);
