// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ApGroup extends pulumi.CustomResource {
    /**
     * Get an existing ApGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApGroupState, opts?: pulumi.CustomResourceOptions): ApGroup {
        return new ApGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:index/apGroup:ApGroup';

    /**
     * Returns true if the given object is an instance of ApGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApGroup.__pulumiType;
    }

    /**
     * The MAC addresses of the access points that are members of the group. May be empty — the controller accepts a group with no members.
     */
    declare public readonly deviceMacs: pulumi.Output<string[]>;
    /**
     * The name of the AP group.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The name of the site to associate the AP group with.
     */
    declare public readonly site: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.ApGroupTimeouts | undefined>;

    /**
     * Create a ApGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApGroupArgs | ApGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApGroupState | undefined;
            resourceInputs["deviceMacs"] = state?.deviceMacs;
            resourceInputs["name"] = state?.name;
            resourceInputs["site"] = state?.site;
            resourceInputs["timeouts"] = state?.timeouts;
        } else {
            const args = argsOrState as ApGroupArgs | undefined;
            if (args?.deviceMacs === undefined && !opts.urn) {
                throw new Error("Missing required property 'deviceMacs'");
            }
            resourceInputs["deviceMacs"] = args?.deviceMacs;
            resourceInputs["name"] = args?.name;
            resourceInputs["site"] = args?.site;
            resourceInputs["timeouts"] = args?.timeouts;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ApGroup.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ApGroup resources.
 */
export interface ApGroupState {
    /**
     * The MAC addresses of the access points that are members of the group. May be empty — the controller accepts a group with no members.
     */
    deviceMacs?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The name of the AP group.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The name of the site to associate the AP group with.
     */
    site?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.ApGroupTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a ApGroup resource.
 */
export interface ApGroupArgs {
    /**
     * The MAC addresses of the access points that are members of the group. May be empty — the controller accepts a group with no members.
     */
    deviceMacs: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the AP group.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The name of the site to associate the AP group with.
     */
    site?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.ApGroupTimeouts | undefined>;
}
