// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Client extends pulumi.CustomResource {
    /**
     * Get an existing Client resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClientState, opts?: pulumi.CustomResourceOptions): Client {
        return new Client(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:index/client:Client';

    /**
     * Returns true if the given object is an instance of Client.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Client {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Client.__pulumiType;
    }

    /**
     * Specifies whether this resource should just take over control of an existing client.
     */
    declare public readonly allowExisting: pulumi.Output<boolean>;
    /**
     * Specifies whether this client should be blocked from the network.
     */
    declare public readonly blocked: pulumi.Output<boolean>;
    /**
     * The display name of the client.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * The MAC address of the access point to which this client should be fixed.
     */
    declare public readonly fixedApMac: pulumi.Output<string>;
    /**
     * A fixed IPv4 address for this client.
     */
    declare public readonly fixedIp: pulumi.Output<string>;
    /**
     * List of network members group names for this client.
     */
    declare public readonly groups: pulumi.Output<string[]>;
    /**
     * The hostname of the client.
     */
    declare public /*out*/ readonly hostname: pulumi.Output<string>;
    /**
     * The most recent IP address the controller has seen for this client (read-only).
     */
    declare public /*out*/ readonly lastIp: pulumi.Output<string>;
    /**
     * Specifies the local DNS record for this client.
     */
    declare public readonly localDnsRecord: pulumi.Output<string>;
    /**
     * The MAC address of the client.
     */
    declare public readonly mac: pulumi.Output<string>;
    /**
     * The name of the client.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The network ID for this client.
     */
    declare public readonly networkId: pulumi.Output<string>;
    /**
     * A note with additional information for the client.
     */
    declare public readonly note: pulumi.Output<string>;
    /**
     * QoS rate limiting configuration. Controls the client group (usergroup) used for bandwidth limits.
     */
    declare public readonly qosRate: pulumi.Output<outputs.ClientQosRate>;
    /**
     * The name of the site to associate the client with.
     */
    declare public readonly site: pulumi.Output<string>;
    /**
     * Specifies whether this resource should tell the controller to "forget" the client on destroy.
     */
    declare public readonly skipForgetOnDestroy: pulumi.Output<boolean>;
    declare public readonly timeouts: pulumi.Output<outputs.ClientTimeouts | undefined>;

    /**
     * Create a Client resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClientArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClientArgs | ClientState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ClientState | undefined;
            resourceInputs["allowExisting"] = state?.allowExisting;
            resourceInputs["blocked"] = state?.blocked;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["fixedApMac"] = state?.fixedApMac;
            resourceInputs["fixedIp"] = state?.fixedIp;
            resourceInputs["groups"] = state?.groups;
            resourceInputs["hostname"] = state?.hostname;
            resourceInputs["lastIp"] = state?.lastIp;
            resourceInputs["localDnsRecord"] = state?.localDnsRecord;
            resourceInputs["mac"] = state?.mac;
            resourceInputs["name"] = state?.name;
            resourceInputs["networkId"] = state?.networkId;
            resourceInputs["note"] = state?.note;
            resourceInputs["qosRate"] = state?.qosRate;
            resourceInputs["site"] = state?.site;
            resourceInputs["skipForgetOnDestroy"] = state?.skipForgetOnDestroy;
            resourceInputs["timeouts"] = state?.timeouts;
        } else {
            const args = argsOrState as ClientArgs | undefined;
            if (args?.mac === undefined && !opts.urn) {
                throw new Error("Missing required property 'mac'");
            }
            resourceInputs["allowExisting"] = args?.allowExisting;
            resourceInputs["blocked"] = args?.blocked;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["fixedApMac"] = args?.fixedApMac;
            resourceInputs["fixedIp"] = args?.fixedIp;
            resourceInputs["groups"] = args?.groups;
            resourceInputs["localDnsRecord"] = args?.localDnsRecord;
            resourceInputs["mac"] = args?.mac;
            resourceInputs["name"] = args?.name;
            resourceInputs["networkId"] = args?.networkId;
            resourceInputs["note"] = args?.note;
            resourceInputs["qosRate"] = args?.qosRate;
            resourceInputs["site"] = args?.site;
            resourceInputs["skipForgetOnDestroy"] = args?.skipForgetOnDestroy;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["lastIp"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Client.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Client resources.
 */
export interface ClientState {
    /**
     * Specifies whether this resource should just take over control of an existing client.
     */
    allowExisting?: pulumi.Input<boolean | undefined>;
    /**
     * Specifies whether this client should be blocked from the network.
     */
    blocked?: pulumi.Input<boolean | undefined>;
    /**
     * The display name of the client.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * The MAC address of the access point to which this client should be fixed.
     */
    fixedApMac?: pulumi.Input<string | undefined>;
    /**
     * A fixed IPv4 address for this client.
     */
    fixedIp?: pulumi.Input<string | undefined>;
    /**
     * List of network members group names for this client.
     */
    groups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The hostname of the client.
     */
    hostname?: pulumi.Input<string | undefined>;
    /**
     * The most recent IP address the controller has seen for this client (read-only).
     */
    lastIp?: pulumi.Input<string | undefined>;
    /**
     * Specifies the local DNS record for this client.
     */
    localDnsRecord?: pulumi.Input<string | undefined>;
    /**
     * The MAC address of the client.
     */
    mac?: pulumi.Input<string | undefined>;
    /**
     * The name of the client.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The network ID for this client.
     */
    networkId?: pulumi.Input<string | undefined>;
    /**
     * A note with additional information for the client.
     */
    note?: pulumi.Input<string | undefined>;
    /**
     * QoS rate limiting configuration. Controls the client group (usergroup) used for bandwidth limits.
     */
    qosRate?: pulumi.Input<inputs.ClientQosRate | undefined>;
    /**
     * The name of the site to associate the client with.
     */
    site?: pulumi.Input<string | undefined>;
    /**
     * Specifies whether this resource should tell the controller to "forget" the client on destroy.
     */
    skipForgetOnDestroy?: pulumi.Input<boolean | undefined>;
    timeouts?: pulumi.Input<inputs.ClientTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a Client resource.
 */
export interface ClientArgs {
    /**
     * Specifies whether this resource should just take over control of an existing client.
     */
    allowExisting?: pulumi.Input<boolean | undefined>;
    /**
     * Specifies whether this client should be blocked from the network.
     */
    blocked?: pulumi.Input<boolean | undefined>;
    /**
     * The display name of the client.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * The MAC address of the access point to which this client should be fixed.
     */
    fixedApMac?: pulumi.Input<string | undefined>;
    /**
     * A fixed IPv4 address for this client.
     */
    fixedIp?: pulumi.Input<string | undefined>;
    /**
     * List of network members group names for this client.
     */
    groups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Specifies the local DNS record for this client.
     */
    localDnsRecord?: pulumi.Input<string | undefined>;
    /**
     * The MAC address of the client.
     */
    mac: pulumi.Input<string>;
    /**
     * The name of the client.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The network ID for this client.
     */
    networkId?: pulumi.Input<string | undefined>;
    /**
     * A note with additional information for the client.
     */
    note?: pulumi.Input<string | undefined>;
    /**
     * QoS rate limiting configuration. Controls the client group (usergroup) used for bandwidth limits.
     */
    qosRate?: pulumi.Input<inputs.ClientQosRate | undefined>;
    /**
     * The name of the site to associate the client with.
     */
    site?: pulumi.Input<string | undefined>;
    /**
     * Specifies whether this resource should tell the controller to "forget" the client on destroy.
     */
    skipForgetOnDestroy?: pulumi.Input<boolean | undefined>;
    timeouts?: pulumi.Input<inputs.ClientTimeouts | undefined>;
}
