// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getClientInfo(args: GetClientInfoArgs, opts?: pulumi.InvokeOptions): Promise<GetClientInfoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("unifi:index/getClientInfo:getClientInfo", {
        "mac": args.mac,
        "site": args.site,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClientInfo.
 */
export interface GetClientInfoArgs {
    mac: string;
    site?: string;
}

/**
 * A collection of values returned by getClientInfo.
 */
export interface GetClientInfoResult {
    readonly apMac: string;
    readonly authorized: boolean;
    readonly blocked: boolean;
    readonly bssid: string;
    readonly channel: number;
    readonly displayName: string;
    readonly essid: string;
    readonly firstSeen: number;
    readonly fixedIp: string;
    readonly hostname: string;
    readonly id: string;
    readonly ip: string;
    readonly isGuest: boolean;
    readonly isWired: boolean;
    readonly lastConnectionNetworkId: string;
    readonly lastConnectionNetworkName: string;
    readonly lastSeen: number;
    readonly lastUplinkMac: string;
    readonly lastUplinkName: string;
    readonly lastUplinkRemotePort: number;
    readonly localDnsRecord: string;
    readonly localDnsRecordEnabled: boolean;
    readonly mac: string;
    readonly name: string;
    readonly networkId: string;
    readonly networkName: string;
    readonly noise: number;
    readonly oui: string;
    readonly radio: string;
    readonly radioName: string;
    readonly rssi: number;
    readonly rxBytes: number;
    readonly rxRate: number;
    readonly signal: number;
    readonly site: string;
    readonly status: string;
    readonly swPort: number;
    readonly txBytes: number;
    readonly txRate: number;
    readonly uptime: number;
    readonly useFixedip: boolean;
    readonly usergroupId: string;
    readonly wiredRateMbps: number;
}
export function getClientInfoOutput(args: GetClientInfoOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClientInfoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("unifi:index/getClientInfo:getClientInfo", {
        "mac": args.mac,
        "site": args.site,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClientInfo.
 */
export interface GetClientInfoOutputArgs {
    mac: pulumi.Input<string>;
    site?: pulumi.Input<string>;
}
