// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getClientQosRate(args: GetClientQosRateArgs, opts?: pulumi.InvokeOptions): Promise<GetClientQosRateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("unifi:index/getClientQosRate:getClientQosRate", {
        "name": args.name,
        "site": args.site,
        "timeouts": args.timeouts,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClientQosRate.
 */
export interface GetClientQosRateArgs {
    name: string;
    site?: string;
    timeouts?: inputs.GetClientQosRateTimeouts;
}

/**
 * A collection of values returned by getClientQosRate.
 */
export interface GetClientQosRateResult {
    readonly id: string;
    readonly name: string;
    readonly qosRateMaxDown: number;
    readonly qosRateMaxUp: number;
    readonly site: string;
    readonly timeouts?: outputs.GetClientQosRateTimeouts;
}
export function getClientQosRateOutput(args: GetClientQosRateOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClientQosRateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("unifi:index/getClientQosRate:getClientQosRate", {
        "name": args.name,
        "site": args.site,
        "timeouts": args.timeouts,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClientQosRate.
 */
export interface GetClientQosRateOutputArgs {
    name: pulumi.Input<string>;
    site?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.GetClientQosRateTimeoutsArgs | undefined>;
}
