// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getClientList(args?: GetClientListArgs, opts?: pulumi.InvokeOptions): Promise<GetClientListResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("unifi:index/getClientList:getClientList", {
        "blocked": args.blocked,
        "group": args.group,
        "oui": args.oui,
        "site": args.site,
        "wired": args.wired,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClientList.
 */
export interface GetClientListArgs {
    blocked?: boolean;
    group?: string;
    oui?: string;
    site?: string;
    wired?: boolean;
}

/**
 * A collection of values returned by getClientList.
 */
export interface GetClientListResult {
    readonly blocked?: boolean;
    readonly clients: outputs.GetClientListClient[];
    readonly group?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly oui?: string;
    readonly site: string;
    readonly wired?: boolean;
}
export function getClientListOutput(args?: GetClientListOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClientListResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("unifi:index/getClientList:getClientList", {
        "blocked": args.blocked,
        "group": args.group,
        "oui": args.oui,
        "site": args.site,
        "wired": args.wired,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClientList.
 */
export interface GetClientListOutputArgs {
    blocked?: pulumi.Input<boolean>;
    group?: pulumi.Input<string>;
    oui?: pulumi.Input<string>;
    site?: pulumi.Input<string>;
    wired?: pulumi.Input<boolean>;
}
