// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getClientInfoList(args?: GetClientInfoListArgs, opts?: pulumi.InvokeOptions): Promise<GetClientInfoListResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("unifi:index/getClientInfoList:getClientInfoList", {
        "site": args.site,
        "timeouts": args.timeouts,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClientInfoList.
 */
export interface GetClientInfoListArgs {
    site?: string;
    timeouts?: inputs.GetClientInfoListTimeouts;
}

/**
 * A collection of values returned by getClientInfoList.
 */
export interface GetClientInfoListResult {
    readonly clients: outputs.GetClientInfoListClient[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly site: string;
    readonly timeouts?: outputs.GetClientInfoListTimeouts;
}
export function getClientInfoListOutput(args?: GetClientInfoListOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClientInfoListResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("unifi:index/getClientInfoList:getClientInfoList", {
        "site": args.site,
        "timeouts": args.timeouts,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getClientInfoList.
 */
export interface GetClientInfoListOutputArgs {
    site?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.GetClientInfoListTimeoutsArgs | undefined>;
}
