// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getRadiusProfile(args: GetRadiusProfileArgs, opts?: pulumi.InvokeOptions): Promise<GetRadiusProfileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("unifi:index/getRadiusProfile:getRadiusProfile", {
        "name": args.name,
        "site": args.site,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRadiusProfile.
 */
export interface GetRadiusProfileArgs {
    name: string;
    site?: string;
}

/**
 * A collection of values returned by getRadiusProfile.
 */
export interface GetRadiusProfileResult {
    readonly accountingEnabled: boolean;
    readonly id: string;
    readonly interimUpdateEnabled: boolean;
    readonly interimUpdateInterval: number;
    readonly name: string;
    readonly site: string;
    readonly useUsgAcctServer: boolean;
    readonly useUsgAuthServer: boolean;
    readonly vlanEnabled: boolean;
    readonly vlanWlanMode: string;
}
export function getRadiusProfileOutput(args: GetRadiusProfileOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRadiusProfileResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("unifi:index/getRadiusProfile:getRadiusProfile", {
        "name": args.name,
        "site": args.site,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRadiusProfile.
 */
export interface GetRadiusProfileOutputArgs {
    name: pulumi.Input<string>;
    site?: pulumi.Input<string>;
}
