// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class SiteToSiteVpn extends pulumi.CustomResource {
    /**
     * Get an existing SiteToSiteVpn resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SiteToSiteVpnState, opts?: pulumi.CustomResourceOptions): SiteToSiteVpn {
        return new SiteToSiteVpn(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:index/siteToSiteVpn:SiteToSiteVpn';

    /**
     * Returns true if the given object is an instance of SiteToSiteVpn.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SiteToSiteVpn {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SiteToSiteVpn.__pulumiType;
    }

    /**
     * Whether IPsec dynamic routing is enabled.
     */
    declare public readonly dynamicRouting: pulumi.Output<boolean>;
    /**
     * Whether the tunnel is enabled.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * ESP (phase 2) Diffie-Hellman group (PFS). Only used when `profile = customized`.
     */
    declare public readonly espDhGroup: pulumi.Output<number>;
    /**
     * ESP (phase 2) encryption. Only used when `profile = customized`.
     */
    declare public readonly espEncryption: pulumi.Output<string>;
    /**
     * ESP (phase 2) hash. Only used when `profile = customized`.
     */
    declare public readonly espHash: pulumi.Output<string>;
    /**
     * ESP (phase 2) security-association lifetime, as a Go duration string (e.g. `1h`, `3600s`). Must be a whole number of seconds between `30s` and `86400s` (24h).
     */
    declare public readonly espLifetime: pulumi.Output<string>;
    /**
     * IKE (phase 1) Diffie-Hellman group. Only used when `profile = customized`.
     */
    declare public readonly ikeDhGroup: pulumi.Output<number>;
    /**
     * IKE (phase 1) encryption. Only used when `profile = customized`.
     */
    declare public readonly ikeEncryption: pulumi.Output<string>;
    /**
     * IKE (phase 1) hash. Only used when `profile = customized`.
     */
    declare public readonly ikeHash: pulumi.Output<string>;
    /**
     * IKE (phase 1) security-association lifetime, as a Go duration string (e.g. `8h`, `28800s`). Must be a whole number of seconds between `30s` and `86400s` (24h).
     */
    declare public readonly ikeLifetime: pulumi.Output<string>;
    /**
     * The local WAN interface the tunnel binds to (e.g. `wan`, `wan2`).
     */
    declare public readonly interface: pulumi.Output<string>;
    /**
     * IKE key-exchange version. One of `ikev1` or `ikev2`.
     */
    declare public readonly keyExchange: pulumi.Output<string>;
    /**
     * The local IP used for the tunnel. Defaults to the WAN address when omitted.
     */
    declare public readonly localIp: pulumi.Output<string>;
    /**
     * The name of the site-to-site VPN.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The public IP address of the remote VPN gateway (peer).
     */
    declare public readonly peerIp: pulumi.Output<string>;
    /**
     * Whether Perfect Forward Secrecy is enabled.
     */
    declare public readonly pfs: pulumi.Output<boolean>;
    /**
     * The IPsec pre-shared key. Stored in state — use `pre_shared_key_wo` to avoid persisting the secret.
     */
    declare public readonly preSharedKey: pulumi.Output<string | undefined>;
    declare public readonly preSharedKeyWo: pulumi.Output<string | undefined>;
    /**
     * IPsec profile. One of `customized`, `azure_dynamic`, or `azure_static`. Set to `customized` to tune the IKE/ESP attributes below; the controller may derive the ESP values from the IKE ones.
     */
    declare public readonly profile: pulumi.Output<string>;
    /**
     * The remote site's subnets reachable through the tunnel (CIDR).
     */
    declare public readonly remoteSubnets: pulumi.Output<string[]>;
    /**
     * The route distance (administrative metric) for tunnel routes (1-255).
     */
    declare public readonly routeDistance: pulumi.Output<number>;
    /**
     * The name of the site to associate the VPN with.
     */
    declare public readonly site: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.SiteToSiteVpnTimeouts | undefined>;

    /**
     * Create a SiteToSiteVpn resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SiteToSiteVpnArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SiteToSiteVpnArgs | SiteToSiteVpnState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SiteToSiteVpnState | undefined;
            resourceInputs["dynamicRouting"] = state?.dynamicRouting;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["espDhGroup"] = state?.espDhGroup;
            resourceInputs["espEncryption"] = state?.espEncryption;
            resourceInputs["espHash"] = state?.espHash;
            resourceInputs["espLifetime"] = state?.espLifetime;
            resourceInputs["ikeDhGroup"] = state?.ikeDhGroup;
            resourceInputs["ikeEncryption"] = state?.ikeEncryption;
            resourceInputs["ikeHash"] = state?.ikeHash;
            resourceInputs["ikeLifetime"] = state?.ikeLifetime;
            resourceInputs["interface"] = state?.interface;
            resourceInputs["keyExchange"] = state?.keyExchange;
            resourceInputs["localIp"] = state?.localIp;
            resourceInputs["name"] = state?.name;
            resourceInputs["peerIp"] = state?.peerIp;
            resourceInputs["pfs"] = state?.pfs;
            resourceInputs["preSharedKey"] = state?.preSharedKey;
            resourceInputs["preSharedKeyWo"] = state?.preSharedKeyWo;
            resourceInputs["profile"] = state?.profile;
            resourceInputs["remoteSubnets"] = state?.remoteSubnets;
            resourceInputs["routeDistance"] = state?.routeDistance;
            resourceInputs["site"] = state?.site;
            resourceInputs["timeouts"] = state?.timeouts;
        } else {
            const args = argsOrState as SiteToSiteVpnArgs | undefined;
            if (args?.peerIp === undefined && !opts.urn) {
                throw new Error("Missing required property 'peerIp'");
            }
            if (args?.remoteSubnets === undefined && !opts.urn) {
                throw new Error("Missing required property 'remoteSubnets'");
            }
            resourceInputs["dynamicRouting"] = args?.dynamicRouting;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["espDhGroup"] = args?.espDhGroup;
            resourceInputs["espEncryption"] = args?.espEncryption;
            resourceInputs["espHash"] = args?.espHash;
            resourceInputs["espLifetime"] = args?.espLifetime;
            resourceInputs["ikeDhGroup"] = args?.ikeDhGroup;
            resourceInputs["ikeEncryption"] = args?.ikeEncryption;
            resourceInputs["ikeHash"] = args?.ikeHash;
            resourceInputs["ikeLifetime"] = args?.ikeLifetime;
            resourceInputs["interface"] = args?.interface;
            resourceInputs["keyExchange"] = args?.keyExchange;
            resourceInputs["localIp"] = args?.localIp;
            resourceInputs["name"] = args?.name;
            resourceInputs["peerIp"] = args?.peerIp;
            resourceInputs["pfs"] = args?.pfs;
            resourceInputs["preSharedKey"] = args?.preSharedKey ? pulumi.secret(args.preSharedKey) : undefined;
            resourceInputs["preSharedKeyWo"] = args?.preSharedKeyWo ? pulumi.secret(args.preSharedKeyWo) : undefined;
            resourceInputs["profile"] = args?.profile;
            resourceInputs["remoteSubnets"] = args?.remoteSubnets;
            resourceInputs["routeDistance"] = args?.routeDistance;
            resourceInputs["site"] = args?.site;
            resourceInputs["timeouts"] = args?.timeouts;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["preSharedKey", "preSharedKeyWo"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(SiteToSiteVpn.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SiteToSiteVpn resources.
 */
export interface SiteToSiteVpnState {
    /**
     * Whether IPsec dynamic routing is enabled.
     */
    dynamicRouting?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the tunnel is enabled.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * ESP (phase 2) Diffie-Hellman group (PFS). Only used when `profile = customized`.
     */
    espDhGroup?: pulumi.Input<number | undefined>;
    /**
     * ESP (phase 2) encryption. Only used when `profile = customized`.
     */
    espEncryption?: pulumi.Input<string | undefined>;
    /**
     * ESP (phase 2) hash. Only used when `profile = customized`.
     */
    espHash?: pulumi.Input<string | undefined>;
    /**
     * ESP (phase 2) security-association lifetime, as a Go duration string (e.g. `1h`, `3600s`). Must be a whole number of seconds between `30s` and `86400s` (24h).
     */
    espLifetime?: pulumi.Input<string | undefined>;
    /**
     * IKE (phase 1) Diffie-Hellman group. Only used when `profile = customized`.
     */
    ikeDhGroup?: pulumi.Input<number | undefined>;
    /**
     * IKE (phase 1) encryption. Only used when `profile = customized`.
     */
    ikeEncryption?: pulumi.Input<string | undefined>;
    /**
     * IKE (phase 1) hash. Only used when `profile = customized`.
     */
    ikeHash?: pulumi.Input<string | undefined>;
    /**
     * IKE (phase 1) security-association lifetime, as a Go duration string (e.g. `8h`, `28800s`). Must be a whole number of seconds between `30s` and `86400s` (24h).
     */
    ikeLifetime?: pulumi.Input<string | undefined>;
    /**
     * The local WAN interface the tunnel binds to (e.g. `wan`, `wan2`).
     */
    interface?: pulumi.Input<string | undefined>;
    /**
     * IKE key-exchange version. One of `ikev1` or `ikev2`.
     */
    keyExchange?: pulumi.Input<string | undefined>;
    /**
     * The local IP used for the tunnel. Defaults to the WAN address when omitted.
     */
    localIp?: pulumi.Input<string | undefined>;
    /**
     * The name of the site-to-site VPN.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The public IP address of the remote VPN gateway (peer).
     */
    peerIp?: pulumi.Input<string | undefined>;
    /**
     * Whether Perfect Forward Secrecy is enabled.
     */
    pfs?: pulumi.Input<boolean | undefined>;
    /**
     * The IPsec pre-shared key. Stored in state — use `pre_shared_key_wo` to avoid persisting the secret.
     */
    preSharedKey?: pulumi.Input<string | undefined>;
    preSharedKeyWo?: pulumi.Input<string | undefined>;
    /**
     * IPsec profile. One of `customized`, `azure_dynamic`, or `azure_static`. Set to `customized` to tune the IKE/ESP attributes below; the controller may derive the ESP values from the IKE ones.
     */
    profile?: pulumi.Input<string | undefined>;
    /**
     * The remote site's subnets reachable through the tunnel (CIDR).
     */
    remoteSubnets?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The route distance (administrative metric) for tunnel routes (1-255).
     */
    routeDistance?: pulumi.Input<number | undefined>;
    /**
     * The name of the site to associate the VPN with.
     */
    site?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.SiteToSiteVpnTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a SiteToSiteVpn resource.
 */
export interface SiteToSiteVpnArgs {
    /**
     * Whether IPsec dynamic routing is enabled.
     */
    dynamicRouting?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the tunnel is enabled.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * ESP (phase 2) Diffie-Hellman group (PFS). Only used when `profile = customized`.
     */
    espDhGroup?: pulumi.Input<number | undefined>;
    /**
     * ESP (phase 2) encryption. Only used when `profile = customized`.
     */
    espEncryption?: pulumi.Input<string | undefined>;
    /**
     * ESP (phase 2) hash. Only used when `profile = customized`.
     */
    espHash?: pulumi.Input<string | undefined>;
    /**
     * ESP (phase 2) security-association lifetime, as a Go duration string (e.g. `1h`, `3600s`). Must be a whole number of seconds between `30s` and `86400s` (24h).
     */
    espLifetime?: pulumi.Input<string | undefined>;
    /**
     * IKE (phase 1) Diffie-Hellman group. Only used when `profile = customized`.
     */
    ikeDhGroup?: pulumi.Input<number | undefined>;
    /**
     * IKE (phase 1) encryption. Only used when `profile = customized`.
     */
    ikeEncryption?: pulumi.Input<string | undefined>;
    /**
     * IKE (phase 1) hash. Only used when `profile = customized`.
     */
    ikeHash?: pulumi.Input<string | undefined>;
    /**
     * IKE (phase 1) security-association lifetime, as a Go duration string (e.g. `8h`, `28800s`). Must be a whole number of seconds between `30s` and `86400s` (24h).
     */
    ikeLifetime?: pulumi.Input<string | undefined>;
    /**
     * The local WAN interface the tunnel binds to (e.g. `wan`, `wan2`).
     */
    interface?: pulumi.Input<string | undefined>;
    /**
     * IKE key-exchange version. One of `ikev1` or `ikev2`.
     */
    keyExchange?: pulumi.Input<string | undefined>;
    /**
     * The local IP used for the tunnel. Defaults to the WAN address when omitted.
     */
    localIp?: pulumi.Input<string | undefined>;
    /**
     * The name of the site-to-site VPN.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The public IP address of the remote VPN gateway (peer).
     */
    peerIp: pulumi.Input<string>;
    /**
     * Whether Perfect Forward Secrecy is enabled.
     */
    pfs?: pulumi.Input<boolean | undefined>;
    /**
     * The IPsec pre-shared key. Stored in state — use `pre_shared_key_wo` to avoid persisting the secret.
     */
    preSharedKey?: pulumi.Input<string | undefined>;
    preSharedKeyWo?: pulumi.Input<string | undefined>;
    /**
     * IPsec profile. One of `customized`, `azure_dynamic`, or `azure_static`. Set to `customized` to tune the IKE/ESP attributes below; the controller may derive the ESP values from the IKE ones.
     */
    profile?: pulumi.Input<string | undefined>;
    /**
     * The remote site's subnets reachable through the tunnel (CIDR).
     */
    remoteSubnets: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The route distance (administrative metric) for tunnel routes (1-255).
     */
    routeDistance?: pulumi.Input<number | undefined>;
    /**
     * The name of the site to associate the VPN with.
     */
    site?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.SiteToSiteVpnTimeouts | undefined>;
}
