[env]
PULUMI_STACK = "authentik"
PULUMI_BACKEND_URL = "postgres://postgres.sgc.driscoll.tech"
PULUMI_CONFIG_PASSPHRASE = "op://Eris/Pulumi Passphrase/password"
PGUSER = "op://Eris/sgc-pulumi-operator-postgres/username"
PGPASSWORD = "op://Eris/sgc-pulumi-operator-postgres/password"
PGHOST = "op://Eris/sgc-pulumi-operator-postgres/public-hostname"
PGPORT = "op://Eris/sgc-pulumi-operator-postgres/port"
PGDATABASE = "op://Eris/sgc-pulumi-operator-postgres/database"
AUTHENTIK_TOKEN = "op://Eris/Authentik Token/credential"
PGSSLMODE = "disable"
AUTHENTIK_URL = "op://Eris/Authentik Token/url"
