---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: zot
spec:
  name: Container Registry Mirror
  category: ${CLUSTER_TITLE}
  description: A container registry mirror for faster image pulls
  url: &url https://registry.${searchDomain}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/zot-registry.svg
  access_policy:
    groups:
      - admins
  uptime:
    http:
      url: https://registry.${searchDomain}/livez
      method: GET
      accepted_statuscodes: ["200"]
      parent_name: "cluster"
