// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ClientDevice extends pulumi.CustomResource {
    /**
     * Get an existing ClientDevice resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClientDeviceState, opts?: pulumi.CustomResourceOptions): ClientDevice {
        return new ClientDevice(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'terrifi:index/clientDevice:ClientDevice';

    /**
     * Returns true if the given object is an instance of ClientDevice.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ClientDevice {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ClientDevice.__pulumiType;
    }

    /**
     * Whether the client device is blocked from network access. Defaults to `false`.
     */
    declare public readonly blocked: pulumi.Output<boolean>;
    /**
     * Set of client group IDs to assign this device to. Use `terrifi.ClientGroup` to manage groups.
     */
    declare public readonly clientGroupIds: pulumi.Output<string[] | undefined>;
    /**
     * The device type ID (fingerprint override) to set a custom icon for this client device. Use `terrifi list-device-types` to list IDs as CSV, or `terrifi list-device-types --html` to generate a browsable page with icons and fuzzy search.
     */
    declare public readonly deviceTypeId: pulumi.Output<number | undefined>;
    /**
     * A fixed IP address to assign to this client via DHCP reservation. Requires `network_id` or `network_override_id` to also be set.
     */
    declare public readonly fixedIp: pulumi.Output<string | undefined>;
    /**
     * A local DNS hostname for this client device. Requires `fixed_ip` to also be set (controller requirement).
     */
    declare public readonly localDnsRecord: pulumi.Output<string | undefined>;
    /**
     * The MAC address of the client device (e.g. `aa:bb:cc:dd:ee:ff`).
     */
    declare public readonly mac: pulumi.Output<string>;
    /**
     * The alias/display name for the client device.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The network ID for fixed IP assignment. Required when `fixed_ip` is set unless `network_override_id` provides the network context.
     */
    declare public readonly networkId: pulumi.Output<string | undefined>;
    /**
     * The network ID for VLAN/network override. When set, the client will be placed on this network regardless of the SSID or port profile it connects to.
     */
    declare public readonly networkOverrideId: pulumi.Output<string | undefined>;
    /**
     * A free-text note for the client device.
     */
    declare public readonly note: pulumi.Output<string | undefined>;
    /**
     * The site to associate the client device with. Defaults to the provider site.
     */
    declare public readonly site: pulumi.Output<string>;

    /**
     * Create a ClientDevice resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClientDeviceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClientDeviceArgs | ClientDeviceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ClientDeviceState | undefined;
            resourceInputs["blocked"] = state?.blocked;
            resourceInputs["clientGroupIds"] = state?.clientGroupIds;
            resourceInputs["deviceTypeId"] = state?.deviceTypeId;
            resourceInputs["fixedIp"] = state?.fixedIp;
            resourceInputs["localDnsRecord"] = state?.localDnsRecord;
            resourceInputs["mac"] = state?.mac;
            resourceInputs["name"] = state?.name;
            resourceInputs["networkId"] = state?.networkId;
            resourceInputs["networkOverrideId"] = state?.networkOverrideId;
            resourceInputs["note"] = state?.note;
            resourceInputs["site"] = state?.site;
        } else {
            const args = argsOrState as ClientDeviceArgs | undefined;
            if (args?.mac === undefined && !opts.urn) {
                throw new Error("Missing required property 'mac'");
            }
            resourceInputs["blocked"] = args?.blocked;
            resourceInputs["clientGroupIds"] = args?.clientGroupIds;
            resourceInputs["deviceTypeId"] = args?.deviceTypeId;
            resourceInputs["fixedIp"] = args?.fixedIp;
            resourceInputs["localDnsRecord"] = args?.localDnsRecord;
            resourceInputs["mac"] = args?.mac;
            resourceInputs["name"] = args?.name;
            resourceInputs["networkId"] = args?.networkId;
            resourceInputs["networkOverrideId"] = args?.networkOverrideId;
            resourceInputs["note"] = args?.note;
            resourceInputs["site"] = args?.site;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ClientDevice.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ClientDevice resources.
 */
export interface ClientDeviceState {
    /**
     * Whether the client device is blocked from network access. Defaults to `false`.
     */
    blocked?: pulumi.Input<boolean>;
    /**
     * Set of client group IDs to assign this device to. Use `terrifi.ClientGroup` to manage groups.
     */
    clientGroupIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The device type ID (fingerprint override) to set a custom icon for this client device. Use `terrifi list-device-types` to list IDs as CSV, or `terrifi list-device-types --html` to generate a browsable page with icons and fuzzy search.
     */
    deviceTypeId?: pulumi.Input<number>;
    /**
     * A fixed IP address to assign to this client via DHCP reservation. Requires `network_id` or `network_override_id` to also be set.
     */
    fixedIp?: pulumi.Input<string>;
    /**
     * A local DNS hostname for this client device. Requires `fixed_ip` to also be set (controller requirement).
     */
    localDnsRecord?: pulumi.Input<string>;
    /**
     * The MAC address of the client device (e.g. `aa:bb:cc:dd:ee:ff`).
     */
    mac?: pulumi.Input<string>;
    /**
     * The alias/display name for the client device.
     */
    name?: pulumi.Input<string>;
    /**
     * The network ID for fixed IP assignment. Required when `fixed_ip` is set unless `network_override_id` provides the network context.
     */
    networkId?: pulumi.Input<string>;
    /**
     * The network ID for VLAN/network override. When set, the client will be placed on this network regardless of the SSID or port profile it connects to.
     */
    networkOverrideId?: pulumi.Input<string>;
    /**
     * A free-text note for the client device.
     */
    note?: pulumi.Input<string>;
    /**
     * The site to associate the client device with. Defaults to the provider site.
     */
    site?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ClientDevice resource.
 */
export interface ClientDeviceArgs {
    /**
     * Whether the client device is blocked from network access. Defaults to `false`.
     */
    blocked?: pulumi.Input<boolean>;
    /**
     * Set of client group IDs to assign this device to. Use `terrifi.ClientGroup` to manage groups.
     */
    clientGroupIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The device type ID (fingerprint override) to set a custom icon for this client device. Use `terrifi list-device-types` to list IDs as CSV, or `terrifi list-device-types --html` to generate a browsable page with icons and fuzzy search.
     */
    deviceTypeId?: pulumi.Input<number>;
    /**
     * A fixed IP address to assign to this client via DHCP reservation. Requires `network_id` or `network_override_id` to also be set.
     */
    fixedIp?: pulumi.Input<string>;
    /**
     * A local DNS hostname for this client device. Requires `fixed_ip` to also be set (controller requirement).
     */
    localDnsRecord?: pulumi.Input<string>;
    /**
     * The MAC address of the client device (e.g. `aa:bb:cc:dd:ee:ff`).
     */
    mac: pulumi.Input<string>;
    /**
     * The alias/display name for the client device.
     */
    name?: pulumi.Input<string>;
    /**
     * The network ID for fixed IP assignment. Required when `fixed_ip` is set unless `network_override_id` provides the network context.
     */
    networkId?: pulumi.Input<string>;
    /**
     * The network ID for VLAN/network override. When set, the client will be placed on this network regardless of the SSID or port profile it connects to.
     */
    networkOverrideId?: pulumi.Input<string>;
    /**
     * A free-text note for the client device.
     */
    note?: pulumi.Input<string>;
    /**
     * The site to associate the client device with. Defaults to the provider site.
     */
    site?: pulumi.Input<string>;
}
