// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Device extends pulumi.CustomResource {
    /**
     * Get an existing Device resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DeviceState, opts?: pulumi.CustomResourceOptions): Device {
        return new Device(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'terrifi:index/device:Device';

    /**
     * Returns true if the given object is an instance of Device.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Device {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Device.__pulumiType;
    }

    /**
     * Whether the device has been adopted by the controller.
     */
    declare public /*out*/ readonly adopted: pulumi.Output<boolean>;
    /**
     * Management network configuration for the device. Use `type = "dhcp"` to receive an address from DHCP, or `type = "static"` with `ip`, `netmask`, and `gateway` set to assign a fixed management address. Omit this block to leave the device's current configuration unchanged.
     */
    declare public readonly configNetwork: pulumi.Output<outputs.DeviceConfigNetwork | undefined>;
    /**
     * Whether the device is administratively disabled. Defaults to `false`.
     */
    declare public readonly disabled: pulumi.Output<boolean>;
    /**
     * The current IP address of the device.
     */
    declare public /*out*/ readonly ip: pulumi.Output<string>;
    /**
     * LED brightness (0–100).
     */
    declare public readonly ledBrightness: pulumi.Output<number | undefined>;
    /**
     * LED color as a hex string (e.g. `#0000ff`).
     */
    declare public readonly ledColor: pulumi.Output<string | undefined>;
    /**
     * Whether LEDs are enabled. `true` forces LEDs on, `false` forces LEDs off. Omit to follow the site default.
     */
    declare public readonly ledEnabled: pulumi.Output<boolean | undefined>;
    /**
     * Whether the device is locked to prevent accidental removal. Defaults to `false`.
     */
    declare public readonly locked: pulumi.Output<boolean>;
    /**
     * The MAC address of the device (e.g. `aa:bb:cc:dd:ee:ff`). The device must already be adopted by the controller.
     */
    declare public readonly mac: pulumi.Output<string>;
    /**
     * The hardware model of the device (e.g. `U6-LR`, `US-16-XG`).
     */
    declare public /*out*/ readonly model: pulumi.Output<string>;
    /**
     * The display name for the device.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Outdoor mode override. `default` follows the device default, `on` enables outdoor mode, `off` disables it.
     */
    declare public readonly outdoorModeOverride: pulumi.Output<string | undefined>;
    /**
     * Radio settings for the 2.4 GHz (`ng`) radio on an access point. Omit to leave this radio's settings unchanged.
     */
    declare public readonly radio24: pulumi.Output<outputs.DeviceRadio24 | undefined>;
    /**
     * Radio settings for the 5 GHz (`na`) radio on an access point. Omit to leave this radio's settings unchanged.
     */
    declare public readonly radio5: pulumi.Output<outputs.DeviceRadio5 | undefined>;
    /**
     * Radio settings for the 6 GHz (`6e`) radio on an access point. Omit to leave this radio's settings unchanged.
     */
    declare public readonly radio6: pulumi.Output<outputs.DeviceRadio6 | undefined>;
    /**
     * The site the device belongs to. Defaults to the provider site.
     */
    declare public readonly site: pulumi.Output<string>;
    /**
     * [SNMP](https://en.wikipedia.org/wiki/Simple_Network_Management_Protocol) contact string (max 255 characters). Identifies who is responsible for the device; read by network monitoring tools.
     */
    declare public readonly snmpContact: pulumi.Output<string | undefined>;
    /**
     * [SNMP](https://en.wikipedia.org/wiki/Simple_Network_Management_Protocol) location string (max 255 characters). Describes where the device is physically located; read by network monitoring tools.
     */
    declare public readonly snmpLocation: pulumi.Output<string | undefined>;
    /**
     * The device state. 0 = unknown, 1 = connected, 2 = pending, 4 = upgrading, 5 = provisioning, 6 = heartbeat missed.
     */
    declare public /*out*/ readonly state: pulumi.Output<number>;
    /**
     * The device type (e.g. `uap` for access point, `usw` for switch, `ugw` for gateway).
     */
    declare public /*out*/ readonly type: pulumi.Output<string>;
    /**
     * Speaker volume (0–100). Only applicable to devices with speakers.
     */
    declare public readonly volume: pulumi.Output<number | undefined>;

    /**
     * Create a Device resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DeviceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DeviceArgs | DeviceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DeviceState | undefined;
            resourceInputs["adopted"] = state?.adopted;
            resourceInputs["configNetwork"] = state?.configNetwork;
            resourceInputs["disabled"] = state?.disabled;
            resourceInputs["ip"] = state?.ip;
            resourceInputs["ledBrightness"] = state?.ledBrightness;
            resourceInputs["ledColor"] = state?.ledColor;
            resourceInputs["ledEnabled"] = state?.ledEnabled;
            resourceInputs["locked"] = state?.locked;
            resourceInputs["mac"] = state?.mac;
            resourceInputs["model"] = state?.model;
            resourceInputs["name"] = state?.name;
            resourceInputs["outdoorModeOverride"] = state?.outdoorModeOverride;
            resourceInputs["radio24"] = state?.radio24;
            resourceInputs["radio5"] = state?.radio5;
            resourceInputs["radio6"] = state?.radio6;
            resourceInputs["site"] = state?.site;
            resourceInputs["snmpContact"] = state?.snmpContact;
            resourceInputs["snmpLocation"] = state?.snmpLocation;
            resourceInputs["state"] = state?.state;
            resourceInputs["type"] = state?.type;
            resourceInputs["volume"] = state?.volume;
        } else {
            const args = argsOrState as DeviceArgs | undefined;
            if (args?.mac === undefined && !opts.urn) {
                throw new Error("Missing required property 'mac'");
            }
            resourceInputs["configNetwork"] = args?.configNetwork;
            resourceInputs["disabled"] = args?.disabled;
            resourceInputs["ledBrightness"] = args?.ledBrightness;
            resourceInputs["ledColor"] = args?.ledColor;
            resourceInputs["ledEnabled"] = args?.ledEnabled;
            resourceInputs["locked"] = args?.locked;
            resourceInputs["mac"] = args?.mac;
            resourceInputs["name"] = args?.name;
            resourceInputs["outdoorModeOverride"] = args?.outdoorModeOverride;
            resourceInputs["radio24"] = args?.radio24;
            resourceInputs["radio5"] = args?.radio5;
            resourceInputs["radio6"] = args?.radio6;
            resourceInputs["site"] = args?.site;
            resourceInputs["snmpContact"] = args?.snmpContact;
            resourceInputs["snmpLocation"] = args?.snmpLocation;
            resourceInputs["volume"] = args?.volume;
            resourceInputs["adopted"] = undefined /*out*/;
            resourceInputs["ip"] = undefined /*out*/;
            resourceInputs["model"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Device.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Device resources.
 */
export interface DeviceState {
    /**
     * Whether the device has been adopted by the controller.
     */
    adopted?: pulumi.Input<boolean>;
    /**
     * Management network configuration for the device. Use `type = "dhcp"` to receive an address from DHCP, or `type = "static"` with `ip`, `netmask`, and `gateway` set to assign a fixed management address. Omit this block to leave the device's current configuration unchanged.
     */
    configNetwork?: pulumi.Input<inputs.DeviceConfigNetwork>;
    /**
     * Whether the device is administratively disabled. Defaults to `false`.
     */
    disabled?: pulumi.Input<boolean>;
    /**
     * The current IP address of the device.
     */
    ip?: pulumi.Input<string>;
    /**
     * LED brightness (0–100).
     */
    ledBrightness?: pulumi.Input<number>;
    /**
     * LED color as a hex string (e.g. `#0000ff`).
     */
    ledColor?: pulumi.Input<string>;
    /**
     * Whether LEDs are enabled. `true` forces LEDs on, `false` forces LEDs off. Omit to follow the site default.
     */
    ledEnabled?: pulumi.Input<boolean>;
    /**
     * Whether the device is locked to prevent accidental removal. Defaults to `false`.
     */
    locked?: pulumi.Input<boolean>;
    /**
     * The MAC address of the device (e.g. `aa:bb:cc:dd:ee:ff`). The device must already be adopted by the controller.
     */
    mac?: pulumi.Input<string>;
    /**
     * The hardware model of the device (e.g. `U6-LR`, `US-16-XG`).
     */
    model?: pulumi.Input<string>;
    /**
     * The display name for the device.
     */
    name?: pulumi.Input<string>;
    /**
     * Outdoor mode override. `default` follows the device default, `on` enables outdoor mode, `off` disables it.
     */
    outdoorModeOverride?: pulumi.Input<string>;
    /**
     * Radio settings for the 2.4 GHz (`ng`) radio on an access point. Omit to leave this radio's settings unchanged.
     */
    radio24?: pulumi.Input<inputs.DeviceRadio24>;
    /**
     * Radio settings for the 5 GHz (`na`) radio on an access point. Omit to leave this radio's settings unchanged.
     */
    radio5?: pulumi.Input<inputs.DeviceRadio5>;
    /**
     * Radio settings for the 6 GHz (`6e`) radio on an access point. Omit to leave this radio's settings unchanged.
     */
    radio6?: pulumi.Input<inputs.DeviceRadio6>;
    /**
     * The site the device belongs to. Defaults to the provider site.
     */
    site?: pulumi.Input<string>;
    /**
     * [SNMP](https://en.wikipedia.org/wiki/Simple_Network_Management_Protocol) contact string (max 255 characters). Identifies who is responsible for the device; read by network monitoring tools.
     */
    snmpContact?: pulumi.Input<string>;
    /**
     * [SNMP](https://en.wikipedia.org/wiki/Simple_Network_Management_Protocol) location string (max 255 characters). Describes where the device is physically located; read by network monitoring tools.
     */
    snmpLocation?: pulumi.Input<string>;
    /**
     * The device state. 0 = unknown, 1 = connected, 2 = pending, 4 = upgrading, 5 = provisioning, 6 = heartbeat missed.
     */
    state?: pulumi.Input<number>;
    /**
     * The device type (e.g. `uap` for access point, `usw` for switch, `ugw` for gateway).
     */
    type?: pulumi.Input<string>;
    /**
     * Speaker volume (0–100). Only applicable to devices with speakers.
     */
    volume?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Device resource.
 */
export interface DeviceArgs {
    /**
     * Management network configuration for the device. Use `type = "dhcp"` to receive an address from DHCP, or `type = "static"` with `ip`, `netmask`, and `gateway` set to assign a fixed management address. Omit this block to leave the device's current configuration unchanged.
     */
    configNetwork?: pulumi.Input<inputs.DeviceConfigNetwork>;
    /**
     * Whether the device is administratively disabled. Defaults to `false`.
     */
    disabled?: pulumi.Input<boolean>;
    /**
     * LED brightness (0–100).
     */
    ledBrightness?: pulumi.Input<number>;
    /**
     * LED color as a hex string (e.g. `#0000ff`).
     */
    ledColor?: pulumi.Input<string>;
    /**
     * Whether LEDs are enabled. `true` forces LEDs on, `false` forces LEDs off. Omit to follow the site default.
     */
    ledEnabled?: pulumi.Input<boolean>;
    /**
     * Whether the device is locked to prevent accidental removal. Defaults to `false`.
     */
    locked?: pulumi.Input<boolean>;
    /**
     * The MAC address of the device (e.g. `aa:bb:cc:dd:ee:ff`). The device must already be adopted by the controller.
     */
    mac: pulumi.Input<string>;
    /**
     * The display name for the device.
     */
    name?: pulumi.Input<string>;
    /**
     * Outdoor mode override. `default` follows the device default, `on` enables outdoor mode, `off` disables it.
     */
    outdoorModeOverride?: pulumi.Input<string>;
    /**
     * Radio settings for the 2.4 GHz (`ng`) radio on an access point. Omit to leave this radio's settings unchanged.
     */
    radio24?: pulumi.Input<inputs.DeviceRadio24>;
    /**
     * Radio settings for the 5 GHz (`na`) radio on an access point. Omit to leave this radio's settings unchanged.
     */
    radio5?: pulumi.Input<inputs.DeviceRadio5>;
    /**
     * Radio settings for the 6 GHz (`6e`) radio on an access point. Omit to leave this radio's settings unchanged.
     */
    radio6?: pulumi.Input<inputs.DeviceRadio6>;
    /**
     * The site the device belongs to. Defaults to the provider site.
     */
    site?: pulumi.Input<string>;
    /**
     * [SNMP](https://en.wikipedia.org/wiki/Simple_Network_Management_Protocol) contact string (max 255 characters). Identifies who is responsible for the device; read by network monitoring tools.
     */
    snmpContact?: pulumi.Input<string>;
    /**
     * [SNMP](https://en.wikipedia.org/wiki/Simple_Network_Management_Protocol) location string (max 255 characters). Describes where the device is physically located; read by network monitoring tools.
     */
    snmpLocation?: pulumi.Input<string>;
    /**
     * Speaker volume (0–100). Only applicable to devices with speakers.
     */
    volume?: pulumi.Input<number>;
}
