// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DnsRecord extends pulumi.CustomResource {
    /**
     * Get an existing DnsRecord resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnsRecordState, opts?: pulumi.CustomResourceOptions): DnsRecord {
        return new DnsRecord(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'terrifi:index/dnsRecord:DnsRecord';

    /**
     * Returns true if the given object is an instance of DnsRecord.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DnsRecord {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DnsRecord.__pulumiType;
    }

    /**
     * Whether the DNS record is enabled. Default: `true`.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * The hostname for the DNS record.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The port for SRV records.
     */
    declare public readonly port: pulumi.Output<number | undefined>;
    /**
     * The priority for MX/SRV records.
     */
    declare public readonly priority: pulumi.Output<number | undefined>;
    /**
     * The DNS record type (A, AAAA, CNAME, MX, TXT, SRV, PTR).
     */
    declare public readonly recordType: pulumi.Output<string | undefined>;
    /**
     * The site to associate the DNS record with. Defaults to the provider site.
     */
    declare public readonly site: pulumi.Output<string>;
    /**
     * The TTL in seconds.
     */
    declare public readonly ttl: pulumi.Output<number | undefined>;
    /**
     * The value of the DNS record (IP address, hostname, etc.).
     */
    declare public readonly value: pulumi.Output<string>;
    /**
     * The weight for SRV records.
     */
    declare public readonly weight: pulumi.Output<number | undefined>;

    /**
     * Create a DnsRecord resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DnsRecordArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnsRecordArgs | DnsRecordState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnsRecordState | undefined;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["name"] = state?.name;
            resourceInputs["port"] = state?.port;
            resourceInputs["priority"] = state?.priority;
            resourceInputs["recordType"] = state?.recordType;
            resourceInputs["site"] = state?.site;
            resourceInputs["ttl"] = state?.ttl;
            resourceInputs["value"] = state?.value;
            resourceInputs["weight"] = state?.weight;
        } else {
            const args = argsOrState as DnsRecordArgs | undefined;
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["port"] = args?.port;
            resourceInputs["priority"] = args?.priority;
            resourceInputs["recordType"] = args?.recordType;
            resourceInputs["site"] = args?.site;
            resourceInputs["ttl"] = args?.ttl;
            resourceInputs["value"] = args?.value;
            resourceInputs["weight"] = args?.weight;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DnsRecord.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering DnsRecord resources.
 */
export interface DnsRecordState {
    /**
     * Whether the DNS record is enabled. Default: `true`.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * The hostname for the DNS record.
     */
    name?: pulumi.Input<string>;
    /**
     * The port for SRV records.
     */
    port?: pulumi.Input<number>;
    /**
     * The priority for MX/SRV records.
     */
    priority?: pulumi.Input<number>;
    /**
     * The DNS record type (A, AAAA, CNAME, MX, TXT, SRV, PTR).
     */
    recordType?: pulumi.Input<string>;
    /**
     * The site to associate the DNS record with. Defaults to the provider site.
     */
    site?: pulumi.Input<string>;
    /**
     * The TTL in seconds.
     */
    ttl?: pulumi.Input<number>;
    /**
     * The value of the DNS record (IP address, hostname, etc.).
     */
    value?: pulumi.Input<string>;
    /**
     * The weight for SRV records.
     */
    weight?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a DnsRecord resource.
 */
export interface DnsRecordArgs {
    /**
     * Whether the DNS record is enabled. Default: `true`.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * The hostname for the DNS record.
     */
    name?: pulumi.Input<string>;
    /**
     * The port for SRV records.
     */
    port?: pulumi.Input<number>;
    /**
     * The priority for MX/SRV records.
     */
    priority?: pulumi.Input<number>;
    /**
     * The DNS record type (A, AAAA, CNAME, MX, TXT, SRV, PTR).
     */
    recordType?: pulumi.Input<string>;
    /**
     * The site to associate the DNS record with. Defaults to the provider site.
     */
    site?: pulumi.Input<string>;
    /**
     * The TTL in seconds.
     */
    ttl?: pulumi.Input<number>;
    /**
     * The value of the DNS record (IP address, hostname, etc.).
     */
    value: pulumi.Input<string>;
    /**
     * The weight for SRV records.
     */
    weight?: pulumi.Input<number>;
}
