// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class FirewallZone extends pulumi.CustomResource {
    /**
     * Get an existing FirewallZone resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FirewallZoneState, opts?: pulumi.CustomResourceOptions): FirewallZone {
        return new FirewallZone(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'terrifi:index/firewallZone:FirewallZone';

    /**
     * Returns true if the given object is an instance of FirewallZone.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FirewallZone {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FirewallZone.__pulumiType;
    }

    /**
     * The name of the firewall zone.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Set of network IDs to associate with this firewall zone.
     */
    declare public readonly networkIds: pulumi.Output<string[]>;
    /**
     * The site to associate the firewall zone with. Defaults to the provider site.
     */
    declare public readonly site: pulumi.Output<string>;
    /**
     * The zone key assigned by the controller.
     */
    declare public /*out*/ readonly zoneKey: pulumi.Output<string>;

    /**
     * Create a FirewallZone resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: FirewallZoneArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FirewallZoneArgs | FirewallZoneState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FirewallZoneState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["networkIds"] = state?.networkIds;
            resourceInputs["site"] = state?.site;
            resourceInputs["zoneKey"] = state?.zoneKey;
        } else {
            const args = argsOrState as FirewallZoneArgs | undefined;
            resourceInputs["name"] = args?.name;
            resourceInputs["networkIds"] = args?.networkIds;
            resourceInputs["site"] = args?.site;
            resourceInputs["zoneKey"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FirewallZone.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering FirewallZone resources.
 */
export interface FirewallZoneState {
    /**
     * The name of the firewall zone.
     */
    name?: pulumi.Input<string>;
    /**
     * Set of network IDs to associate with this firewall zone.
     */
    networkIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The site to associate the firewall zone with. Defaults to the provider site.
     */
    site?: pulumi.Input<string>;
    /**
     * The zone key assigned by the controller.
     */
    zoneKey?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a FirewallZone resource.
 */
export interface FirewallZoneArgs {
    /**
     * The name of the firewall zone.
     */
    name?: pulumi.Input<string>;
    /**
     * Set of network IDs to associate with this firewall zone.
     */
    networkIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The site to associate the firewall zone with. Defaults to the provider site.
     */
    site?: pulumi.Input<string>;
}
