// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Network extends pulumi.CustomResource {
    /**
     * Get an existing Network resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NetworkState, opts?: pulumi.CustomResourceOptions): Network {
        return new Network(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'terrifi:index/network:Network';

    /**
     * Returns true if the given object is an instance of Network.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Network {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Network.__pulumiType;
    }

    /**
     * List of DNS servers for DHCP clients. Maximum 4 servers.
     */
    declare public readonly dhcpDns: pulumi.Output<string[]>;
    /**
     * Whether DHCP is enabled on this network. Default: `false`.
     */
    declare public readonly dhcpEnabled: pulumi.Output<boolean>;
    /**
     * The DHCP lease time in seconds. Default: `86400` (24 hours).
     */
    declare public readonly dhcpLease: pulumi.Output<number>;
    /**
     * The starting IP address for the DHCP pool.
     */
    declare public readonly dhcpStart: pulumi.Output<string>;
    /**
     * The ending IP address for the DHCP pool.
     */
    declare public readonly dhcpStop: pulumi.Output<string>;
    /**
     * Whether internet access is enabled on this network. Default: `true`.
     */
    declare public readonly internetAccessEnabled: pulumi.Output<boolean>;
    /**
     * The name of the network.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The network group. Default: `LAN`.
     */
    declare public readonly networkGroup: pulumi.Output<string>;
    /**
     * The purpose of the network. One of: `corporate`, `vlan-only`.
     */
    declare public readonly purpose: pulumi.Output<string>;
    /**
     * The site to associate the network with. Defaults to the provider site.
     */
    declare public readonly site: pulumi.Output<string>;
    /**
     * The subnet for the network in CIDR notation (e.g., `192.168.33.0/24`).
     */
    declare public readonly subnet: pulumi.Output<string | undefined>;
    /**
     * The VLAN ID for the network. Must be between 2 and 4095.
     */
    declare public readonly vlanId: pulumi.Output<number | undefined>;

    /**
     * Create a Network resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NetworkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NetworkArgs | NetworkState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NetworkState | undefined;
            resourceInputs["dhcpDns"] = state?.dhcpDns;
            resourceInputs["dhcpEnabled"] = state?.dhcpEnabled;
            resourceInputs["dhcpLease"] = state?.dhcpLease;
            resourceInputs["dhcpStart"] = state?.dhcpStart;
            resourceInputs["dhcpStop"] = state?.dhcpStop;
            resourceInputs["internetAccessEnabled"] = state?.internetAccessEnabled;
            resourceInputs["name"] = state?.name;
            resourceInputs["networkGroup"] = state?.networkGroup;
            resourceInputs["purpose"] = state?.purpose;
            resourceInputs["site"] = state?.site;
            resourceInputs["subnet"] = state?.subnet;
            resourceInputs["vlanId"] = state?.vlanId;
        } else {
            const args = argsOrState as NetworkArgs | undefined;
            if (args?.purpose === undefined && !opts.urn) {
                throw new Error("Missing required property 'purpose'");
            }
            resourceInputs["dhcpDns"] = args?.dhcpDns;
            resourceInputs["dhcpEnabled"] = args?.dhcpEnabled;
            resourceInputs["dhcpLease"] = args?.dhcpLease;
            resourceInputs["dhcpStart"] = args?.dhcpStart;
            resourceInputs["dhcpStop"] = args?.dhcpStop;
            resourceInputs["internetAccessEnabled"] = args?.internetAccessEnabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["networkGroup"] = args?.networkGroup;
            resourceInputs["purpose"] = args?.purpose;
            resourceInputs["site"] = args?.site;
            resourceInputs["subnet"] = args?.subnet;
            resourceInputs["vlanId"] = args?.vlanId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Network.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Network resources.
 */
export interface NetworkState {
    /**
     * List of DNS servers for DHCP clients. Maximum 4 servers.
     */
    dhcpDns?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether DHCP is enabled on this network. Default: `false`.
     */
    dhcpEnabled?: pulumi.Input<boolean>;
    /**
     * The DHCP lease time in seconds. Default: `86400` (24 hours).
     */
    dhcpLease?: pulumi.Input<number>;
    /**
     * The starting IP address for the DHCP pool.
     */
    dhcpStart?: pulumi.Input<string>;
    /**
     * The ending IP address for the DHCP pool.
     */
    dhcpStop?: pulumi.Input<string>;
    /**
     * Whether internet access is enabled on this network. Default: `true`.
     */
    internetAccessEnabled?: pulumi.Input<boolean>;
    /**
     * The name of the network.
     */
    name?: pulumi.Input<string>;
    /**
     * The network group. Default: `LAN`.
     */
    networkGroup?: pulumi.Input<string>;
    /**
     * The purpose of the network. One of: `corporate`, `vlan-only`.
     */
    purpose?: pulumi.Input<string>;
    /**
     * The site to associate the network with. Defaults to the provider site.
     */
    site?: pulumi.Input<string>;
    /**
     * The subnet for the network in CIDR notation (e.g., `192.168.33.0/24`).
     */
    subnet?: pulumi.Input<string>;
    /**
     * The VLAN ID for the network. Must be between 2 and 4095.
     */
    vlanId?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Network resource.
 */
export interface NetworkArgs {
    /**
     * List of DNS servers for DHCP clients. Maximum 4 servers.
     */
    dhcpDns?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether DHCP is enabled on this network. Default: `false`.
     */
    dhcpEnabled?: pulumi.Input<boolean>;
    /**
     * The DHCP lease time in seconds. Default: `86400` (24 hours).
     */
    dhcpLease?: pulumi.Input<number>;
    /**
     * The starting IP address for the DHCP pool.
     */
    dhcpStart?: pulumi.Input<string>;
    /**
     * The ending IP address for the DHCP pool.
     */
    dhcpStop?: pulumi.Input<string>;
    /**
     * Whether internet access is enabled on this network. Default: `true`.
     */
    internetAccessEnabled?: pulumi.Input<boolean>;
    /**
     * The name of the network.
     */
    name?: pulumi.Input<string>;
    /**
     * The network group. Default: `LAN`.
     */
    networkGroup?: pulumi.Input<string>;
    /**
     * The purpose of the network. One of: `corporate`, `vlan-only`.
     */
    purpose: pulumi.Input<string>;
    /**
     * The site to associate the network with. Defaults to the provider site.
     */
    site?: pulumi.Input<string>;
    /**
     * The subnet for the network in CIDR notation (e.g., `192.168.33.0/24`).
     */
    subnet?: pulumi.Input<string>;
    /**
     * The VLAN ID for the network. Must be between 2 and 4095.
     */
    vlanId?: pulumi.Input<number>;
}
