// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Wlan extends pulumi.CustomResource {
    /**
     * Get an existing Wlan resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WlanState, opts?: pulumi.CustomResourceOptions): Wlan {
        return new Wlan(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'terrifi:index/wlan:Wlan';

    /**
     * Returns true if the given object is an instance of Wlan.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Wlan {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Wlan.__pulumiType;
    }

    /**
     * The application type for this WLAN. Must be `standard`, `hotspot`, or `iot`. `hotspot` enables guest behavior (captive portal); `iot` enables IoT-optimized behavior. Default: `standard`.
     */
    declare public readonly application: pulumi.Output<string>;
    /**
     * Whether the WLAN is enabled. Default: `true`.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Whether to hide the SSID from broadcast. Default: `false`.
     */
    declare public readonly hideSsid: pulumi.Output<boolean>;
    /**
     * The SSID (network name) of the WLAN. Must be 1-32 characters.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The ID of the network to associate with this WLAN.
     */
    declare public readonly networkId: pulumi.Output<string>;
    /**
     * Enable IoT-specific radio optimizations that improve connection reliability for IoT devices. Only meaningful when `application = "iot"`. Default: `false`.
     */
    declare public readonly optimizeIotConnectivity: pulumi.Output<boolean>;
    /**
     * The WPA passphrase for the WLAN. Must be 8-255 characters. Required when security is `wpapsk`.
     */
    declare public readonly passphrase: pulumi.Output<string | undefined>;
    /**
     * The security protocol for this WLAN. Must be `open` or `wpapsk`. Default: `wpapsk`.
     */
    declare public readonly security: pulumi.Output<string>;
    /**
     * The site to associate the WLAN with. Defaults to the provider site.
     */
    declare public readonly site: pulumi.Output<string>;
    /**
     * The WiFi band for this WLAN. Must be `2g`, `5g`, or `both`. Default: `both`.
     */
    declare public readonly wifiBand: pulumi.Output<string>;
    /**
     * Whether to enable WPA3 support. Default: `false`.
     */
    declare public readonly wpa3Support: pulumi.Output<boolean>;
    /**
     * Whether to enable WPA3 transition mode (WPA2/WPA3 mixed). Default: `false`.
     */
    declare public readonly wpa3Transition: pulumi.Output<boolean>;
    /**
     * The WPA mode for this WLAN. Must be `auto` or `wpa2`. Default: `wpa2`.
     */
    declare public readonly wpaMode: pulumi.Output<string>;

    /**
     * Create a Wlan resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WlanArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WlanArgs | WlanState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WlanState | undefined;
            resourceInputs["application"] = state?.application;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["hideSsid"] = state?.hideSsid;
            resourceInputs["name"] = state?.name;
            resourceInputs["networkId"] = state?.networkId;
            resourceInputs["optimizeIotConnectivity"] = state?.optimizeIotConnectivity;
            resourceInputs["passphrase"] = state?.passphrase;
            resourceInputs["security"] = state?.security;
            resourceInputs["site"] = state?.site;
            resourceInputs["wifiBand"] = state?.wifiBand;
            resourceInputs["wpa3Support"] = state?.wpa3Support;
            resourceInputs["wpa3Transition"] = state?.wpa3Transition;
            resourceInputs["wpaMode"] = state?.wpaMode;
        } else {
            const args = argsOrState as WlanArgs | undefined;
            if (args?.networkId === undefined && !opts.urn) {
                throw new Error("Missing required property 'networkId'");
            }
            resourceInputs["application"] = args?.application;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["hideSsid"] = args?.hideSsid;
            resourceInputs["name"] = args?.name;
            resourceInputs["networkId"] = args?.networkId;
            resourceInputs["optimizeIotConnectivity"] = args?.optimizeIotConnectivity;
            resourceInputs["passphrase"] = args?.passphrase ? pulumi.secret(args.passphrase) : undefined;
            resourceInputs["security"] = args?.security;
            resourceInputs["site"] = args?.site;
            resourceInputs["wifiBand"] = args?.wifiBand;
            resourceInputs["wpa3Support"] = args?.wpa3Support;
            resourceInputs["wpa3Transition"] = args?.wpa3Transition;
            resourceInputs["wpaMode"] = args?.wpaMode;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["passphrase"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Wlan.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Wlan resources.
 */
export interface WlanState {
    /**
     * The application type for this WLAN. Must be `standard`, `hotspot`, or `iot`. `hotspot` enables guest behavior (captive portal); `iot` enables IoT-optimized behavior. Default: `standard`.
     */
    application?: pulumi.Input<string>;
    /**
     * Whether the WLAN is enabled. Default: `true`.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Whether to hide the SSID from broadcast. Default: `false`.
     */
    hideSsid?: pulumi.Input<boolean>;
    /**
     * The SSID (network name) of the WLAN. Must be 1-32 characters.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of the network to associate with this WLAN.
     */
    networkId?: pulumi.Input<string>;
    /**
     * Enable IoT-specific radio optimizations that improve connection reliability for IoT devices. Only meaningful when `application = "iot"`. Default: `false`.
     */
    optimizeIotConnectivity?: pulumi.Input<boolean>;
    /**
     * The WPA passphrase for the WLAN. Must be 8-255 characters. Required when security is `wpapsk`.
     */
    passphrase?: pulumi.Input<string>;
    /**
     * The security protocol for this WLAN. Must be `open` or `wpapsk`. Default: `wpapsk`.
     */
    security?: pulumi.Input<string>;
    /**
     * The site to associate the WLAN with. Defaults to the provider site.
     */
    site?: pulumi.Input<string>;
    /**
     * The WiFi band for this WLAN. Must be `2g`, `5g`, or `both`. Default: `both`.
     */
    wifiBand?: pulumi.Input<string>;
    /**
     * Whether to enable WPA3 support. Default: `false`.
     */
    wpa3Support?: pulumi.Input<boolean>;
    /**
     * Whether to enable WPA3 transition mode (WPA2/WPA3 mixed). Default: `false`.
     */
    wpa3Transition?: pulumi.Input<boolean>;
    /**
     * The WPA mode for this WLAN. Must be `auto` or `wpa2`. Default: `wpa2`.
     */
    wpaMode?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Wlan resource.
 */
export interface WlanArgs {
    /**
     * The application type for this WLAN. Must be `standard`, `hotspot`, or `iot`. `hotspot` enables guest behavior (captive portal); `iot` enables IoT-optimized behavior. Default: `standard`.
     */
    application?: pulumi.Input<string>;
    /**
     * Whether the WLAN is enabled. Default: `true`.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * Whether to hide the SSID from broadcast. Default: `false`.
     */
    hideSsid?: pulumi.Input<boolean>;
    /**
     * The SSID (network name) of the WLAN. Must be 1-32 characters.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of the network to associate with this WLAN.
     */
    networkId: pulumi.Input<string>;
    /**
     * Enable IoT-specific radio optimizations that improve connection reliability for IoT devices. Only meaningful when `application = "iot"`. Default: `false`.
     */
    optimizeIotConnectivity?: pulumi.Input<boolean>;
    /**
     * The WPA passphrase for the WLAN. Must be 8-255 characters. Required when security is `wpapsk`.
     */
    passphrase?: pulumi.Input<string>;
    /**
     * The security protocol for this WLAN. Must be `open` or `wpapsk`. Default: `wpapsk`.
     */
    security?: pulumi.Input<string>;
    /**
     * The site to associate the WLAN with. Defaults to the provider site.
     */
    site?: pulumi.Input<string>;
    /**
     * The WiFi band for this WLAN. Must be `2g`, `5g`, or `both`. Default: `both`.
     */
    wifiBand?: pulumi.Input<string>;
    /**
     * Whether to enable WPA3 support. Default: `false`.
     */
    wpa3Support?: pulumi.Input<boolean>;
    /**
     * Whether to enable WPA3 transition mode (WPA2/WPA3 mixed). Default: `false`.
     */
    wpa3Transition?: pulumi.Input<boolean>;
    /**
     * The WPA mode for this WLAN. Must be `auto` or `wpa2`. Default: `wpa2`.
     */
    wpaMode?: pulumi.Input<string>;
}
