services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1
    labels:
      tsdproxy.enable: true
      tsdproxy.ephemeral: true
      tsdproxy.name: ${APP}-${CLUSTER_KEY}

      # Enable Traefik
      traefik.enable: true

      traefik.http.routers.tsdproxy.rule: Host(`${APP}.${CLUSTER_DOMAIN}`)
      traefik.http.routers.tsdproxy.entrypoints: websecure
      traefik.http.routers.tsdproxy.service: tsdproxy
      traefik.http.routers.tsdproxy.tls.certresolver: le
      traefik.http.services.tsdproxy.loadbalancer.server.port: 8585
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./config:/config
    restart: unless-stopped
    ports:
      - "8686:8686"
    networks:
      - dockge_default
x-dockge:
  urls:
    - https://${APP}.${CLUSTER_DOMAIN}
    - https://${APP}-${CLUSTER_KEY}.${tailscaleDomain}
networks:
  dockge_default:
    external: true
