# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json

# Traefik static configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# API and Dashboard configuration
api:
  dashboard: true
  insecure: false

# Entry points configuration
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: le
  dns:
    address: ":53/udp"
  dns_tcp:
    address: ":53/tcp"
  dns_quic:
    address: ":784/udp"
  dnss:
    address: ":853"

# Providers configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

# Certificate resolvers configuration
certificatesResolvers:
  le:
    acme:
      email: "david.driscoll+celestia@gmail.com"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare

  cloudflare:
    acme:
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      email: "david.driscoll+celestia@gmail.com"
      storage: "/letsencrypt/acme.json"
      dnsChallenge:
        provider: cloudflare