services:
  traefik:
    image: traefik:v3
    restart: unless-stopped
    command:
      - --configfile=/config/config.yaml
      - --providers.file.watch=true
    labels:
      # Enable Traefik for itself
      - traefik.enable=true
      # Dashboard configuration
      - traefik.http.routers.dashboard.rule=Host(`internal.celestia.driscoll.tech`)
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.tls.certresolver=le
      - traefik.http.routers.dockge.rule=Host(`dockge.celestia.driscoll.tech`)
      - traefik.http.routers.dockge.entrypoints=websecure
      - traefik.http.routers.dockge.tls.certresolver=le
      - traefik.http.routers.dockge.service=dockge
      - traefik.http.services.dockge.loadbalancer.server.url=http://celestia.driscoll.tech:5001
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=papj5TRKnYq_VdsHnCHH4yCNOh8hKj77SGbYAYzm
    ports:
      - 80:80
      - 443:443
      - 53:53/udp
      - 53:53/tcp
      - 853:853
      - 784:784/udp
      - 5443:5443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
      - ./config.yaml:/config/config.yaml
    networks:
      - dockge_default
x-dockge:
  urls:
    - https://internal.celestia.driscoll.tech
networks:
  dockge_default:
    external: true
