services:
  uptime:
    container_name: uptime
    image: ghcr.io/twin/gatus:v5.36.0@sha256:c5f210d095fa78e6efaa20ffeb14803f2ba4f10615e16a6d12087697149617f0
    restart: unless-stopped
    dns:
      - 100.100.100.100
    environment:
      GATUS_CONFIG_PATH: /config
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gatus
    labels:
      # Enable Traefik
      traefik.enable: true

      traefik.http.routers.uptime.rule: Host(`uptime.${searchDomain}`)
      traefik.http.routers.uptime.entrypoints: websecure
      traefik.http.routers.uptime.service: uptime
      traefik.http.routers.uptime.tls.certresolver: le

      traefik.http.routers.uptime-tailscale.rule: Host(`uptime.${tailscaleDomain}`)
      traefik.http.routers.uptime-tailscale.entrypoints: tailscale
      traefik.http.routers.uptime-tailscale.service: uptime

      traefik.http.services.uptime.loadbalancer.server.port: 8080
    volumes:
      - /opt/stacks-data/${APP}/data/:/data/
      - /opt/stacks-data/${APP}/config/:/config/
      - ./config/default.yaml:/config/default.yaml
    networks:
      - dockge_default

x-dockge:
  urls:
    - https://uptime.${searchDomain}
    - https://uptime.${tailscaleDomain}
networks:
  dockge_default:
    external: true