[env]
PULUMI_STACK = "unifi-network"
PULUMI_BACKEND_URL = "s3://pulumi-state/unifi-network?endpoint=dockge-celestia.{{ env.TAILSCALE_DOMAIN }}:3900&s3ForcePathStyle=true&disableSSL=true&region=garage"
