
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: zigbee
spec:
  name: Zigbee
  category: DNS
  url: &url https://zigbee.${searchDomain}
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/zigbee.svg
  access_policy:
    groups:
      - admins
  uptime:
    http:
      url: *url
      method: GET
      accepted_statuscodes: ["200"]
      parent_name: "apps"
