services:
  traefik:
    container_name: traefik
    image: ghcr.io/traefik/traefik:v3.7.0@sha256:eb328e2c806c53aafbbace6c451fa54d268961261a85452fcf0fb752a30c17be
    restart: unless-stopped
    dns:
      - 100.100.100.100
    command:
      - --configfile=/config/config.yaml
    labels:
      autoheal: true
      # Enable Traefik for itself
      traefik.enable: true
      # Dashboard configuration
      traefik.http.routers.dashboard.rule: Host(`internal.${CLUSTER_DOMAIN}`)
      traefik.http.routers.dashboard.middlewares: authentik-outpost@docker
      traefik.http.routers.dashboard.entrypoints: websecure,tailscale
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.tls.certresolver: le

      traefik.http.routers.dashboard-tailscale.rule: Host(`internal-${host}.${tailscaleDomain}`)
      traefik.http.routers.dashboard-tailscale.entrypoints: tailscale
      traefik.http.routers.dashboard-tailscale.service: api@internal

      # The middleware
      traefik.http.middlewares.authentik-outpost.forwardauth.address: http://authentik_proxy:9000/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik-outpost.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik-outpost.forwardauth.authResponseHeaders:
        X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version

    env_file:
      - path: .env
    ports:
      - 80:80
      - 443:443
      - 5443:5443
      - 8443:8443
      - 2022:2022/tcp
      - 7687:7687
      - 8082:8082/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
      - ./config.yaml:/config/config.yaml
      - ./dynamic:/config/dynamic
    networks:
      - dockge_default
x-dockge:
  urls:
    - https://internal.${CLUSTER_DOMAIN}
    - https://internal-${host}.${tailscaleDomain}
networks:
  dockge_default:
    external: true
