// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Repository extends pulumi.CustomResource {
    /**
     * Get an existing Repository resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RepositoryState, opts?: pulumi.CustomResourceOptions): Repository {
        return new Repository(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'forgejo:index/repository:Repository';

    /**
     * Returns true if the given object is an instance of Repository.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Repository {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Repository.__pulumiType;
    }

    /**
     * Allowed to fast-forward-only merge pull requests? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    declare public readonly allowFastForwardOnlyMerge: pulumi.Output<boolean>;
    /**
     * Allowed to manually merge pull requests? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    declare public readonly allowManualMerge: pulumi.Output<boolean>;
    /**
     * Allowed to create merge commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    declare public readonly allowMergeCommits: pulumi.Output<boolean>;
    /**
     * Allowed to rebase then fast-forward? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    declare public readonly allowRebase: pulumi.Output<boolean>;
    /**
     * Allowed to rebase then create merge commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    declare public readonly allowRebaseExplicit: pulumi.Output<boolean>;
    /**
     * Allowed to update pull request branch by rebase? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    declare public readonly allowRebaseUpdate: pulumi.Output<boolean>;
    /**
     * Allowed to create squash commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    declare public readonly allowSquashMerge: pulumi.Output<boolean>;
    /**
     * Archive the repo instead of delete?
     */
    declare public readonly archiveOnDestroy: pulumi.Output<boolean>;
    /**
     * Is the repository archived?
     */
    declare public readonly archived: pulumi.Output<boolean>;
    /**
     * API token for authenticating with migrate / clone URL. **Note**: This setting is only effective if `clone_addr` is set.
     */
    declare public readonly authToken: pulumi.Output<string | undefined>;
    /**
     * Whether the repository should be auto-intialized? Changing this forces a new resource to be created.
     */
    declare public readonly autoInit: pulumi.Output<boolean>;
    /**
     * Auto-detect manual pull request merges? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    declare public readonly autodetectManualMerge: pulumi.Output<boolean>;
    /**
     * Avatar URL of the repository.
     */
    declare public /*out*/ readonly avatarUrl: pulumi.Output<string>;
    /**
     * Migrate / clone from URL. Changing this forces a new resource to be created.
     */
    declare public readonly cloneAddr: pulumi.Output<string>;
    /**
     * Clone URL of the repository.
     */
    declare public /*out*/ readonly cloneUrl: pulumi.Output<string>;
    /**
     * Time at which the repository was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Allow maintainer edits on pull requests by default? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    declare public readonly defaultAllowMaintainerEdit: pulumi.Output<boolean>;
    /**
     * Default branch of the repository.
     */
    declare public readonly defaultBranch: pulumi.Output<string>;
    /**
     * Delete pull request branch after merge by default? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    declare public readonly defaultDeleteBranchAfterMerge: pulumi.Output<boolean>;
    /**
     * Default merge style of the repository. **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    declare public readonly defaultMergeStyle: pulumi.Output<string>;
    /**
     * Default pull request update style of the repository. **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    declare public readonly defaultUpdateStyle: pulumi.Output<string>;
    /**
     * Description of the repository.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Is the repository empty?
     */
    declare public /*out*/ readonly empty: pulumi.Output<boolean>;
    /**
     * Remove obsolete remote-tracking references when mirroring? **Note**: This setting is only effective if `mirror` is `true`.
     */
    declare public readonly enablePrune: pulumi.Output<boolean>;
    /**
     * Settings for external issue tracker. **Note**: This setting is only effective if `has_issues` is `true`.
     */
    declare public readonly externalTracker: pulumi.Output<outputs.RepositoryExternalTracker>;
    /**
     * Settings for external wiki. **Note**: This setting is only effective if `has_wiki` is `true`.
     */
    declare public readonly externalWiki: pulumi.Output<outputs.RepositoryExternalWiki>;
    /**
     * Is the repository a fork?
     */
    declare public /*out*/ readonly fork: pulumi.Output<boolean>;
    /**
     * Number of forks of the repository.
     */
    declare public /*out*/ readonly forksCount: pulumi.Output<number>;
    /**
     * Full name of the repository.
     */
    declare public /*out*/ readonly fullName: pulumi.Output<string>;
    /**
     * Gitignores to use. Changing this forces a new resource to be created.
     */
    declare public readonly gitignores: pulumi.Output<string>;
    /**
     * Is the repository wiki globally editable? **Note**: This setting is only effective if `has_wiki` is `true`.
     */
    declare public readonly globallyEditableWiki: pulumi.Output<boolean>;
    /**
     * Are integrated CI/CD pipelines enabled?
     */
    declare public readonly hasActions: pulumi.Output<boolean>;
    /**
     * Is the repository issue tracker enabled?
     */
    declare public readonly hasIssues: pulumi.Output<boolean>;
    /**
     * Is the repository package registry enabled?
     */
    declare public readonly hasPackages: pulumi.Output<boolean>;
    /**
     * Are repository projects enabled?
     */
    declare public readonly hasProjects: pulumi.Output<boolean>;
    /**
     * Are repository pull requests enabled?
     */
    declare public readonly hasPullRequests: pulumi.Output<boolean>;
    /**
     * Are repository releases enabled?
     */
    declare public readonly hasReleases: pulumi.Output<boolean>;
    /**
     * Is the repository wiki enabled?
     */
    declare public readonly hasWiki: pulumi.Output<boolean>;
    /**
     * HTML URL of the repository.
     */
    declare public /*out*/ readonly htmlUrl: pulumi.Output<string>;
    /**
     * Are whitespace conflicts ignored? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    declare public readonly ignoreWhitespaceConflicts: pulumi.Output<boolean>;
    /**
     * Is the repository internal?
     */
    declare public /*out*/ readonly internal: pulumi.Output<boolean>;
    /**
     * Settings for built-in issue tracker. **Note**: This setting is only effective if `has_issues` is `true`.
     */
    declare public readonly internalTracker: pulumi.Output<outputs.RepositoryInternalTracker>;
    /**
     * Issue Label set to use. Changing this forces a new resource to be created.
     */
    declare public readonly issueLabels: pulumi.Output<string>;
    /**
     * Whether to migrate labels. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    declare public readonly labels: pulumi.Output<boolean>;
    /**
     * Whether to migrate LFS files. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    declare public readonly lfs: pulumi.Output<boolean>;
    /**
     * LFS endpoint to use. Changing this forces a new resource to be created. **Note**: This setting is only effective if `lfs` is `true`.
     */
    declare public readonly lfsEndpoint: pulumi.Output<string>;
    /**
     * License to use. Changing this forces a new resource to be created.
     */
    declare public readonly license: pulumi.Output<string>;
    /**
     * Whether to migrate milestones. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    declare public readonly milestones: pulumi.Output<boolean>;
    /**
     * Is the repository a mirror? Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    declare public readonly mirror: pulumi.Output<boolean>;
    /**
     * Mirror interval of the repository. **Note**: This setting is only effective if `mirror` is `true`.
     */
    declare public readonly mirrorInterval: pulumi.Output<string>;
    /**
     * Time at which the repository mirror was updated.
     */
    declare public /*out*/ readonly mirrorUpdated: pulumi.Output<string>;
    /**
     * Name of the repository.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Number of open issues of the repository.
     */
    declare public /*out*/ readonly openIssuesCount: pulumi.Output<number>;
    /**
     * Number of open pull requests of the repository.
     */
    declare public /*out*/ readonly openPrCounter: pulumi.Output<number>;
    /**
     * Owner of the repository (user or organization). Changing this forces a new resource to be created.
     */
    declare public readonly owner: pulumi.Output<string>;
    /**
     * Numeric identifier of the parent repository.
     */
    declare public /*out*/ readonly parentId: pulumi.Output<number>;
    /**
     * Permissions of the repository.
     */
    declare public /*out*/ readonly permissions: pulumi.Output<outputs.RepositoryPermissions>;
    /**
     * Is the repository private?
     */
    declare public readonly private: pulumi.Output<boolean>;
    /**
     * Readme of the repository to create. Changing this forces a new resource to be created.
     */
    declare public readonly readme: pulumi.Output<string>;
    /**
     * Number of releases of the repository.
     */
    declare public /*out*/ readonly releaseCounter: pulumi.Output<number>;
    /**
     * Numeric identifier of the repository.
     */
    declare public /*out*/ readonly repositoryId: pulumi.Output<number>;
    /**
     * Service to migrate from. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    declare public readonly service: pulumi.Output<string>;
    /**
     * Size of the repository in KiB.
     */
    declare public /*out*/ readonly size: pulumi.Output<number>;
    /**
     * SSH URL of the repository.
     */
    declare public /*out*/ readonly sshUrl: pulumi.Output<string>;
    /**
     * Number of stars of the repository.
     */
    declare public /*out*/ readonly starsCount: pulumi.Output<number>;
    /**
     * Is the repository a template?
     */
    declare public readonly template: pulumi.Output<boolean>;
    /**
     * TrustModel of the repository. Changing this forces a new resource to be created.
     */
    declare public readonly trustModel: pulumi.Output<string>;
    /**
     * Time at which the repository was updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * Number of watchers of the repository.
     */
    declare public /*out*/ readonly watchersCount: pulumi.Output<number>;
    /**
     * Website of the repository.
     */
    declare public readonly website: pulumi.Output<string>;
    /**
     * Branch used for the repository wiki. **Note**: This setting is only effective if `has_wiki` is `true`.
     */
    declare public readonly wikiBranch: pulumi.Output<string>;

    /**
     * Create a Repository resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: RepositoryArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RepositoryArgs | RepositoryState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RepositoryState | undefined;
            resourceInputs["allowFastForwardOnlyMerge"] = state?.allowFastForwardOnlyMerge;
            resourceInputs["allowManualMerge"] = state?.allowManualMerge;
            resourceInputs["allowMergeCommits"] = state?.allowMergeCommits;
            resourceInputs["allowRebase"] = state?.allowRebase;
            resourceInputs["allowRebaseExplicit"] = state?.allowRebaseExplicit;
            resourceInputs["allowRebaseUpdate"] = state?.allowRebaseUpdate;
            resourceInputs["allowSquashMerge"] = state?.allowSquashMerge;
            resourceInputs["archiveOnDestroy"] = state?.archiveOnDestroy;
            resourceInputs["archived"] = state?.archived;
            resourceInputs["authToken"] = state?.authToken;
            resourceInputs["autoInit"] = state?.autoInit;
            resourceInputs["autodetectManualMerge"] = state?.autodetectManualMerge;
            resourceInputs["avatarUrl"] = state?.avatarUrl;
            resourceInputs["cloneAddr"] = state?.cloneAddr;
            resourceInputs["cloneUrl"] = state?.cloneUrl;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["defaultAllowMaintainerEdit"] = state?.defaultAllowMaintainerEdit;
            resourceInputs["defaultBranch"] = state?.defaultBranch;
            resourceInputs["defaultDeleteBranchAfterMerge"] = state?.defaultDeleteBranchAfterMerge;
            resourceInputs["defaultMergeStyle"] = state?.defaultMergeStyle;
            resourceInputs["defaultUpdateStyle"] = state?.defaultUpdateStyle;
            resourceInputs["description"] = state?.description;
            resourceInputs["empty"] = state?.empty;
            resourceInputs["enablePrune"] = state?.enablePrune;
            resourceInputs["externalTracker"] = state?.externalTracker;
            resourceInputs["externalWiki"] = state?.externalWiki;
            resourceInputs["fork"] = state?.fork;
            resourceInputs["forksCount"] = state?.forksCount;
            resourceInputs["fullName"] = state?.fullName;
            resourceInputs["gitignores"] = state?.gitignores;
            resourceInputs["globallyEditableWiki"] = state?.globallyEditableWiki;
            resourceInputs["hasActions"] = state?.hasActions;
            resourceInputs["hasIssues"] = state?.hasIssues;
            resourceInputs["hasPackages"] = state?.hasPackages;
            resourceInputs["hasProjects"] = state?.hasProjects;
            resourceInputs["hasPullRequests"] = state?.hasPullRequests;
            resourceInputs["hasReleases"] = state?.hasReleases;
            resourceInputs["hasWiki"] = state?.hasWiki;
            resourceInputs["htmlUrl"] = state?.htmlUrl;
            resourceInputs["ignoreWhitespaceConflicts"] = state?.ignoreWhitespaceConflicts;
            resourceInputs["internal"] = state?.internal;
            resourceInputs["internalTracker"] = state?.internalTracker;
            resourceInputs["issueLabels"] = state?.issueLabels;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["lfs"] = state?.lfs;
            resourceInputs["lfsEndpoint"] = state?.lfsEndpoint;
            resourceInputs["license"] = state?.license;
            resourceInputs["milestones"] = state?.milestones;
            resourceInputs["mirror"] = state?.mirror;
            resourceInputs["mirrorInterval"] = state?.mirrorInterval;
            resourceInputs["mirrorUpdated"] = state?.mirrorUpdated;
            resourceInputs["name"] = state?.name;
            resourceInputs["openIssuesCount"] = state?.openIssuesCount;
            resourceInputs["openPrCounter"] = state?.openPrCounter;
            resourceInputs["owner"] = state?.owner;
            resourceInputs["parentId"] = state?.parentId;
            resourceInputs["permissions"] = state?.permissions;
            resourceInputs["private"] = state?.private;
            resourceInputs["readme"] = state?.readme;
            resourceInputs["releaseCounter"] = state?.releaseCounter;
            resourceInputs["repositoryId"] = state?.repositoryId;
            resourceInputs["service"] = state?.service;
            resourceInputs["size"] = state?.size;
            resourceInputs["sshUrl"] = state?.sshUrl;
            resourceInputs["starsCount"] = state?.starsCount;
            resourceInputs["template"] = state?.template;
            resourceInputs["trustModel"] = state?.trustModel;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["watchersCount"] = state?.watchersCount;
            resourceInputs["website"] = state?.website;
            resourceInputs["wikiBranch"] = state?.wikiBranch;
        } else {
            const args = argsOrState as RepositoryArgs | undefined;
            resourceInputs["allowFastForwardOnlyMerge"] = args?.allowFastForwardOnlyMerge;
            resourceInputs["allowManualMerge"] = args?.allowManualMerge;
            resourceInputs["allowMergeCommits"] = args?.allowMergeCommits;
            resourceInputs["allowRebase"] = args?.allowRebase;
            resourceInputs["allowRebaseExplicit"] = args?.allowRebaseExplicit;
            resourceInputs["allowRebaseUpdate"] = args?.allowRebaseUpdate;
            resourceInputs["allowSquashMerge"] = args?.allowSquashMerge;
            resourceInputs["archiveOnDestroy"] = args?.archiveOnDestroy;
            resourceInputs["archived"] = args?.archived;
            resourceInputs["authToken"] = args?.authToken ? pulumi.secret(args.authToken) : undefined;
            resourceInputs["autoInit"] = args?.autoInit;
            resourceInputs["autodetectManualMerge"] = args?.autodetectManualMerge;
            resourceInputs["cloneAddr"] = args?.cloneAddr;
            resourceInputs["defaultAllowMaintainerEdit"] = args?.defaultAllowMaintainerEdit;
            resourceInputs["defaultBranch"] = args?.defaultBranch;
            resourceInputs["defaultDeleteBranchAfterMerge"] = args?.defaultDeleteBranchAfterMerge;
            resourceInputs["defaultMergeStyle"] = args?.defaultMergeStyle;
            resourceInputs["defaultUpdateStyle"] = args?.defaultUpdateStyle;
            resourceInputs["description"] = args?.description;
            resourceInputs["enablePrune"] = args?.enablePrune;
            resourceInputs["externalTracker"] = args?.externalTracker;
            resourceInputs["externalWiki"] = args?.externalWiki;
            resourceInputs["gitignores"] = args?.gitignores;
            resourceInputs["globallyEditableWiki"] = args?.globallyEditableWiki;
            resourceInputs["hasActions"] = args?.hasActions;
            resourceInputs["hasIssues"] = args?.hasIssues;
            resourceInputs["hasPackages"] = args?.hasPackages;
            resourceInputs["hasProjects"] = args?.hasProjects;
            resourceInputs["hasPullRequests"] = args?.hasPullRequests;
            resourceInputs["hasReleases"] = args?.hasReleases;
            resourceInputs["hasWiki"] = args?.hasWiki;
            resourceInputs["ignoreWhitespaceConflicts"] = args?.ignoreWhitespaceConflicts;
            resourceInputs["internalTracker"] = args?.internalTracker;
            resourceInputs["issueLabels"] = args?.issueLabels;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["lfs"] = args?.lfs;
            resourceInputs["lfsEndpoint"] = args?.lfsEndpoint;
            resourceInputs["license"] = args?.license;
            resourceInputs["milestones"] = args?.milestones;
            resourceInputs["mirror"] = args?.mirror;
            resourceInputs["mirrorInterval"] = args?.mirrorInterval;
            resourceInputs["name"] = args?.name;
            resourceInputs["owner"] = args?.owner;
            resourceInputs["private"] = args?.private;
            resourceInputs["readme"] = args?.readme;
            resourceInputs["service"] = args?.service;
            resourceInputs["template"] = args?.template;
            resourceInputs["trustModel"] = args?.trustModel;
            resourceInputs["website"] = args?.website;
            resourceInputs["wikiBranch"] = args?.wikiBranch;
            resourceInputs["avatarUrl"] = undefined /*out*/;
            resourceInputs["cloneUrl"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["empty"] = undefined /*out*/;
            resourceInputs["fork"] = undefined /*out*/;
            resourceInputs["forksCount"] = undefined /*out*/;
            resourceInputs["fullName"] = undefined /*out*/;
            resourceInputs["htmlUrl"] = undefined /*out*/;
            resourceInputs["internal"] = undefined /*out*/;
            resourceInputs["mirrorUpdated"] = undefined /*out*/;
            resourceInputs["openIssuesCount"] = undefined /*out*/;
            resourceInputs["openPrCounter"] = undefined /*out*/;
            resourceInputs["parentId"] = undefined /*out*/;
            resourceInputs["permissions"] = undefined /*out*/;
            resourceInputs["releaseCounter"] = undefined /*out*/;
            resourceInputs["repositoryId"] = undefined /*out*/;
            resourceInputs["size"] = undefined /*out*/;
            resourceInputs["sshUrl"] = undefined /*out*/;
            resourceInputs["starsCount"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["watchersCount"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["authToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Repository.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Repository resources.
 */
export interface RepositoryState {
    /**
     * Allowed to fast-forward-only merge pull requests? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowFastForwardOnlyMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed to manually merge pull requests? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowManualMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed to create merge commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowMergeCommits?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed to rebase then fast-forward? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowRebase?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed to rebase then create merge commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowRebaseExplicit?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed to update pull request branch by rebase? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowRebaseUpdate?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed to create squash commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowSquashMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Archive the repo instead of delete?
     */
    archiveOnDestroy?: pulumi.Input<boolean | undefined>;
    /**
     * Is the repository archived?
     */
    archived?: pulumi.Input<boolean | undefined>;
    /**
     * API token for authenticating with migrate / clone URL. **Note**: This setting is only effective if `clone_addr` is set.
     */
    authToken?: pulumi.Input<string | undefined>;
    /**
     * Whether the repository should be auto-intialized? Changing this forces a new resource to be created.
     */
    autoInit?: pulumi.Input<boolean | undefined>;
    /**
     * Auto-detect manual pull request merges? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    autodetectManualMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Avatar URL of the repository.
     */
    avatarUrl?: pulumi.Input<string | undefined>;
    /**
     * Migrate / clone from URL. Changing this forces a new resource to be created.
     */
    cloneAddr?: pulumi.Input<string | undefined>;
    /**
     * Clone URL of the repository.
     */
    cloneUrl?: pulumi.Input<string | undefined>;
    /**
     * Time at which the repository was created.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Allow maintainer edits on pull requests by default? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    defaultAllowMaintainerEdit?: pulumi.Input<boolean | undefined>;
    /**
     * Default branch of the repository.
     */
    defaultBranch?: pulumi.Input<string | undefined>;
    /**
     * Delete pull request branch after merge by default? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    defaultDeleteBranchAfterMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Default merge style of the repository. **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    defaultMergeStyle?: pulumi.Input<string | undefined>;
    /**
     * Default pull request update style of the repository. **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    defaultUpdateStyle?: pulumi.Input<string | undefined>;
    /**
     * Description of the repository.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Is the repository empty?
     */
    empty?: pulumi.Input<boolean | undefined>;
    /**
     * Remove obsolete remote-tracking references when mirroring? **Note**: This setting is only effective if `mirror` is `true`.
     */
    enablePrune?: pulumi.Input<boolean | undefined>;
    /**
     * Settings for external issue tracker. **Note**: This setting is only effective if `has_issues` is `true`.
     */
    externalTracker?: pulumi.Input<inputs.RepositoryExternalTracker | undefined>;
    /**
     * Settings for external wiki. **Note**: This setting is only effective if `has_wiki` is `true`.
     */
    externalWiki?: pulumi.Input<inputs.RepositoryExternalWiki | undefined>;
    /**
     * Is the repository a fork?
     */
    fork?: pulumi.Input<boolean | undefined>;
    /**
     * Number of forks of the repository.
     */
    forksCount?: pulumi.Input<number | undefined>;
    /**
     * Full name of the repository.
     */
    fullName?: pulumi.Input<string | undefined>;
    /**
     * Gitignores to use. Changing this forces a new resource to be created.
     */
    gitignores?: pulumi.Input<string | undefined>;
    /**
     * Is the repository wiki globally editable? **Note**: This setting is only effective if `has_wiki` is `true`.
     */
    globallyEditableWiki?: pulumi.Input<boolean | undefined>;
    /**
     * Are integrated CI/CD pipelines enabled?
     */
    hasActions?: pulumi.Input<boolean | undefined>;
    /**
     * Is the repository issue tracker enabled?
     */
    hasIssues?: pulumi.Input<boolean | undefined>;
    /**
     * Is the repository package registry enabled?
     */
    hasPackages?: pulumi.Input<boolean | undefined>;
    /**
     * Are repository projects enabled?
     */
    hasProjects?: pulumi.Input<boolean | undefined>;
    /**
     * Are repository pull requests enabled?
     */
    hasPullRequests?: pulumi.Input<boolean | undefined>;
    /**
     * Are repository releases enabled?
     */
    hasReleases?: pulumi.Input<boolean | undefined>;
    /**
     * Is the repository wiki enabled?
     */
    hasWiki?: pulumi.Input<boolean | undefined>;
    /**
     * HTML URL of the repository.
     */
    htmlUrl?: pulumi.Input<string | undefined>;
    /**
     * Are whitespace conflicts ignored? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    ignoreWhitespaceConflicts?: pulumi.Input<boolean | undefined>;
    /**
     * Is the repository internal?
     */
    internal?: pulumi.Input<boolean | undefined>;
    /**
     * Settings for built-in issue tracker. **Note**: This setting is only effective if `has_issues` is `true`.
     */
    internalTracker?: pulumi.Input<inputs.RepositoryInternalTracker | undefined>;
    /**
     * Issue Label set to use. Changing this forces a new resource to be created.
     */
    issueLabels?: pulumi.Input<string | undefined>;
    /**
     * Whether to migrate labels. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    labels?: pulumi.Input<boolean | undefined>;
    /**
     * Whether to migrate LFS files. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    lfs?: pulumi.Input<boolean | undefined>;
    /**
     * LFS endpoint to use. Changing this forces a new resource to be created. **Note**: This setting is only effective if `lfs` is `true`.
     */
    lfsEndpoint?: pulumi.Input<string | undefined>;
    /**
     * License to use. Changing this forces a new resource to be created.
     */
    license?: pulumi.Input<string | undefined>;
    /**
     * Whether to migrate milestones. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    milestones?: pulumi.Input<boolean | undefined>;
    /**
     * Is the repository a mirror? Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    mirror?: pulumi.Input<boolean | undefined>;
    /**
     * Mirror interval of the repository. **Note**: This setting is only effective if `mirror` is `true`.
     */
    mirrorInterval?: pulumi.Input<string | undefined>;
    /**
     * Time at which the repository mirror was updated.
     */
    mirrorUpdated?: pulumi.Input<string | undefined>;
    /**
     * Name of the repository.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Number of open issues of the repository.
     */
    openIssuesCount?: pulumi.Input<number | undefined>;
    /**
     * Number of open pull requests of the repository.
     */
    openPrCounter?: pulumi.Input<number | undefined>;
    /**
     * Owner of the repository (user or organization). Changing this forces a new resource to be created.
     */
    owner?: pulumi.Input<string | undefined>;
    /**
     * Numeric identifier of the parent repository.
     */
    parentId?: pulumi.Input<number | undefined>;
    /**
     * Permissions of the repository.
     */
    permissions?: pulumi.Input<inputs.RepositoryPermissions | undefined>;
    /**
     * Is the repository private?
     */
    private?: pulumi.Input<boolean | undefined>;
    /**
     * Readme of the repository to create. Changing this forces a new resource to be created.
     */
    readme?: pulumi.Input<string | undefined>;
    /**
     * Number of releases of the repository.
     */
    releaseCounter?: pulumi.Input<number | undefined>;
    /**
     * Numeric identifier of the repository.
     */
    repositoryId?: pulumi.Input<number | undefined>;
    /**
     * Service to migrate from. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    service?: pulumi.Input<string | undefined>;
    /**
     * Size of the repository in KiB.
     */
    size?: pulumi.Input<number | undefined>;
    /**
     * SSH URL of the repository.
     */
    sshUrl?: pulumi.Input<string | undefined>;
    /**
     * Number of stars of the repository.
     */
    starsCount?: pulumi.Input<number | undefined>;
    /**
     * Is the repository a template?
     */
    template?: pulumi.Input<boolean | undefined>;
    /**
     * TrustModel of the repository. Changing this forces a new resource to be created.
     */
    trustModel?: pulumi.Input<string | undefined>;
    /**
     * Time at which the repository was updated.
     */
    updatedAt?: pulumi.Input<string | undefined>;
    /**
     * Number of watchers of the repository.
     */
    watchersCount?: pulumi.Input<number | undefined>;
    /**
     * Website of the repository.
     */
    website?: pulumi.Input<string | undefined>;
    /**
     * Branch used for the repository wiki. **Note**: This setting is only effective if `has_wiki` is `true`.
     */
    wikiBranch?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Repository resource.
 */
export interface RepositoryArgs {
    /**
     * Allowed to fast-forward-only merge pull requests? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowFastForwardOnlyMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed to manually merge pull requests? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowManualMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed to create merge commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowMergeCommits?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed to rebase then fast-forward? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowRebase?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed to rebase then create merge commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowRebaseExplicit?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed to update pull request branch by rebase? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowRebaseUpdate?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed to create squash commit? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    allowSquashMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Archive the repo instead of delete?
     */
    archiveOnDestroy?: pulumi.Input<boolean | undefined>;
    /**
     * Is the repository archived?
     */
    archived?: pulumi.Input<boolean | undefined>;
    /**
     * API token for authenticating with migrate / clone URL. **Note**: This setting is only effective if `clone_addr` is set.
     */
    authToken?: pulumi.Input<string | undefined>;
    /**
     * Whether the repository should be auto-intialized? Changing this forces a new resource to be created.
     */
    autoInit?: pulumi.Input<boolean | undefined>;
    /**
     * Auto-detect manual pull request merges? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    autodetectManualMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Migrate / clone from URL. Changing this forces a new resource to be created.
     */
    cloneAddr?: pulumi.Input<string | undefined>;
    /**
     * Allow maintainer edits on pull requests by default? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    defaultAllowMaintainerEdit?: pulumi.Input<boolean | undefined>;
    /**
     * Default branch of the repository.
     */
    defaultBranch?: pulumi.Input<string | undefined>;
    /**
     * Delete pull request branch after merge by default? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    defaultDeleteBranchAfterMerge?: pulumi.Input<boolean | undefined>;
    /**
     * Default merge style of the repository. **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    defaultMergeStyle?: pulumi.Input<string | undefined>;
    /**
     * Default pull request update style of the repository. **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    defaultUpdateStyle?: pulumi.Input<string | undefined>;
    /**
     * Description of the repository.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Remove obsolete remote-tracking references when mirroring? **Note**: This setting is only effective if `mirror` is `true`.
     */
    enablePrune?: pulumi.Input<boolean | undefined>;
    /**
     * Settings for external issue tracker. **Note**: This setting is only effective if `has_issues` is `true`.
     */
    externalTracker?: pulumi.Input<inputs.RepositoryExternalTracker | undefined>;
    /**
     * Settings for external wiki. **Note**: This setting is only effective if `has_wiki` is `true`.
     */
    externalWiki?: pulumi.Input<inputs.RepositoryExternalWiki | undefined>;
    /**
     * Gitignores to use. Changing this forces a new resource to be created.
     */
    gitignores?: pulumi.Input<string | undefined>;
    /**
     * Is the repository wiki globally editable? **Note**: This setting is only effective if `has_wiki` is `true`.
     */
    globallyEditableWiki?: pulumi.Input<boolean | undefined>;
    /**
     * Are integrated CI/CD pipelines enabled?
     */
    hasActions?: pulumi.Input<boolean | undefined>;
    /**
     * Is the repository issue tracker enabled?
     */
    hasIssues?: pulumi.Input<boolean | undefined>;
    /**
     * Is the repository package registry enabled?
     */
    hasPackages?: pulumi.Input<boolean | undefined>;
    /**
     * Are repository projects enabled?
     */
    hasProjects?: pulumi.Input<boolean | undefined>;
    /**
     * Are repository pull requests enabled?
     */
    hasPullRequests?: pulumi.Input<boolean | undefined>;
    /**
     * Are repository releases enabled?
     */
    hasReleases?: pulumi.Input<boolean | undefined>;
    /**
     * Is the repository wiki enabled?
     */
    hasWiki?: pulumi.Input<boolean | undefined>;
    /**
     * Are whitespace conflicts ignored? **Note**: This setting is only effective if `has_pull_requests` is `true`.
     */
    ignoreWhitespaceConflicts?: pulumi.Input<boolean | undefined>;
    /**
     * Settings for built-in issue tracker. **Note**: This setting is only effective if `has_issues` is `true`.
     */
    internalTracker?: pulumi.Input<inputs.RepositoryInternalTracker | undefined>;
    /**
     * Issue Label set to use. Changing this forces a new resource to be created.
     */
    issueLabels?: pulumi.Input<string | undefined>;
    /**
     * Whether to migrate labels. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    labels?: pulumi.Input<boolean | undefined>;
    /**
     * Whether to migrate LFS files. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    lfs?: pulumi.Input<boolean | undefined>;
    /**
     * LFS endpoint to use. Changing this forces a new resource to be created. **Note**: This setting is only effective if `lfs` is `true`.
     */
    lfsEndpoint?: pulumi.Input<string | undefined>;
    /**
     * License to use. Changing this forces a new resource to be created.
     */
    license?: pulumi.Input<string | undefined>;
    /**
     * Whether to migrate milestones. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    milestones?: pulumi.Input<boolean | undefined>;
    /**
     * Is the repository a mirror? Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    mirror?: pulumi.Input<boolean | undefined>;
    /**
     * Mirror interval of the repository. **Note**: This setting is only effective if `mirror` is `true`.
     */
    mirrorInterval?: pulumi.Input<string | undefined>;
    /**
     * Name of the repository.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Owner of the repository (user or organization). Changing this forces a new resource to be created.
     */
    owner?: pulumi.Input<string | undefined>;
    /**
     * Is the repository private?
     */
    private?: pulumi.Input<boolean | undefined>;
    /**
     * Readme of the repository to create. Changing this forces a new resource to be created.
     */
    readme?: pulumi.Input<string | undefined>;
    /**
     * Service to migrate from. Changing this forces a new resource to be created. **Note**: This setting is only effective if `clone_addr` is set.
     */
    service?: pulumi.Input<string | undefined>;
    /**
     * Is the repository a template?
     */
    template?: pulumi.Input<boolean | undefined>;
    /**
     * TrustModel of the repository. Changing this forces a new resource to be created.
     */
    trustModel?: pulumi.Input<string | undefined>;
    /**
     * Website of the repository.
     */
    website?: pulumi.Input<string | undefined>;
    /**
     * Branch used for the repository wiki. **Note**: This setting is only effective if `has_wiki` is `true`.
     */
    wikiBranch?: pulumi.Input<string | undefined>;
}
