// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getRemoteGroups(args: GetRemoteGroupsArgs, opts?: pulumi.InvokeOptions): Promise<GetRemoteGroupsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pbs:index/getRemoteGroups:getRemoteGroups", {
        "namespace": args.namespace,
        "remoteName": args.remoteName,
        "store": args.store,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRemoteGroups.
 */
export interface GetRemoteGroupsArgs {
    namespace?: string;
    remoteName: string;
    store: string;
}

/**
 * A collection of values returned by getRemoteGroups.
 */
export interface GetRemoteGroupsResult {
    readonly groups: string[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly namespace?: string;
    readonly remoteName: string;
    readonly store: string;
}
export function getRemoteGroupsOutput(args: GetRemoteGroupsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRemoteGroupsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("pbs:index/getRemoteGroups:getRemoteGroups", {
        "namespace": args.namespace,
        "remoteName": args.remoteName,
        "store": args.store,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getRemoteGroups.
 */
export interface GetRemoteGroupsOutputArgs {
    namespace?: pulumi.Input<string>;
    remoteName: pulumi.Input<string>;
    store: pulumi.Input<string>;
}
