// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getS3Endpoint(args: GetS3EndpointArgs, opts?: pulumi.InvokeOptions): Promise<GetS3EndpointResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pbs:index/getS3Endpoint:getS3Endpoint", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getS3Endpoint.
 */
export interface GetS3EndpointArgs {
    id: string;
}

/**
 * A collection of values returned by getS3Endpoint.
 */
export interface GetS3EndpointResult {
    readonly accessKey: string;
    readonly endpoint: string;
    readonly fingerprint: string;
    readonly id: string;
    readonly pathStyle: boolean;
    readonly port: number;
    readonly providerQuirks: string[];
    readonly region: string;
}
export function getS3EndpointOutput(args: GetS3EndpointOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetS3EndpointResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("pbs:index/getS3Endpoint:getS3Endpoint", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getS3Endpoint.
 */
export interface GetS3EndpointOutputArgs {
    id: pulumi.Input<string>;
}
