// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSyncJobs(args?: GetSyncJobsArgs, opts?: pulumi.InvokeOptions): Promise<GetSyncJobsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pbs:index/getSyncJobs:getSyncJobs", {
        "remote": args.remote,
        "store": args.store,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSyncJobs.
 */
export interface GetSyncJobsArgs {
    remote?: string;
    store?: string;
}

/**
 * A collection of values returned by getSyncJobs.
 */
export interface GetSyncJobsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly jobs: outputs.GetSyncJobsJob[];
    readonly remote?: string;
    readonly store?: string;
}
export function getSyncJobsOutput(args?: GetSyncJobsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSyncJobsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("pbs:index/getSyncJobs:getSyncJobs", {
        "remote": args.remote,
        "store": args.store,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSyncJobs.
 */
export interface GetSyncJobsOutputArgs {
    remote?: pulumi.Input<string>;
    store?: pulumi.Input<string>;
}
