// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getVerifyJobs(args?: GetVerifyJobsArgs, opts?: pulumi.InvokeOptions): Promise<GetVerifyJobsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pbs:index/getVerifyJobs:getVerifyJobs", {
        "store": args.store,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getVerifyJobs.
 */
export interface GetVerifyJobsArgs {
    store?: string;
}

/**
 * A collection of values returned by getVerifyJobs.
 */
export interface GetVerifyJobsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly jobs: outputs.GetVerifyJobsJob[];
    readonly store?: string;
}
export function getVerifyJobsOutput(args?: GetVerifyJobsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetVerifyJobsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("pbs:index/getVerifyJobs:getVerifyJobs", {
        "store": args.store,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getVerifyJobs.
 */
export interface GetVerifyJobsOutputArgs {
    store?: pulumi.Input<string>;
}
