// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Remote extends pulumi.CustomResource {
    /**
     * Get an existing Remote resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RemoteState, opts?: pulumi.CustomResourceOptions): Remote {
        return new Remote(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pbs:index/remote:Remote';

    /**
     * Returns true if the given object is an instance of Remote.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Remote {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Remote.__pulumiType;
    }

    /**
     * Authentication ID for the remote server (e.g., `user@pam` or `user@pbs!token`).
     */
    declare public readonly authId: pulumi.Output<string>;
    /**
     * A comment describing this remote.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * Opaque digest returned by PBS for optimistic locking.
     */
    declare public /*out*/ readonly digest: pulumi.Output<string>;
    /**
     * X509 certificate fingerprint (SHA256) for TLS verification. Format: `AA:BB:CC:...` (32 pairs of hex digits separated by colons).
     */
    declare public readonly fingerprint: pulumi.Output<string | undefined>;
    /**
     * The hostname or IP address of the remote PBS server.
     */
    declare public readonly host: pulumi.Output<string>;
    /**
     * The unique identifier for the remote (3-32 characters).
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly password: pulumi.Output<string>;
    /**
     * The port number for the remote PBS server (default: 8007).
     */
    declare public readonly port: pulumi.Output<number | undefined>;

    /**
     * Create a Remote resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RemoteArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RemoteArgs | RemoteState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RemoteState | undefined;
            resourceInputs["authId"] = state?.authId;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["digest"] = state?.digest;
            resourceInputs["fingerprint"] = state?.fingerprint;
            resourceInputs["host"] = state?.host;
            resourceInputs["name"] = state?.name;
            resourceInputs["password"] = state?.password;
            resourceInputs["port"] = state?.port;
        } else {
            const args = argsOrState as RemoteArgs | undefined;
            if (args?.authId === undefined && !opts.urn) {
                throw new Error("Missing required property 'authId'");
            }
            if (args?.host === undefined && !opts.urn) {
                throw new Error("Missing required property 'host'");
            }
            if (args?.password === undefined && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            resourceInputs["authId"] = args?.authId;
            resourceInputs["comment"] = args?.comment;
            resourceInputs["fingerprint"] = args?.fingerprint;
            resourceInputs["host"] = args?.host;
            resourceInputs["name"] = args?.name;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["port"] = args?.port;
            resourceInputs["digest"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Remote.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Remote resources.
 */
export interface RemoteState {
    /**
     * Authentication ID for the remote server (e.g., `user@pam` or `user@pbs!token`).
     */
    authId?: pulumi.Input<string>;
    /**
     * A comment describing this remote.
     */
    comment?: pulumi.Input<string>;
    /**
     * Opaque digest returned by PBS for optimistic locking.
     */
    digest?: pulumi.Input<string>;
    /**
     * X509 certificate fingerprint (SHA256) for TLS verification. Format: `AA:BB:CC:...` (32 pairs of hex digits separated by colons).
     */
    fingerprint?: pulumi.Input<string>;
    /**
     * The hostname or IP address of the remote PBS server.
     */
    host?: pulumi.Input<string>;
    /**
     * The unique identifier for the remote (3-32 characters).
     */
    name?: pulumi.Input<string>;
    password?: pulumi.Input<string>;
    /**
     * The port number for the remote PBS server (default: 8007).
     */
    port?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Remote resource.
 */
export interface RemoteArgs {
    /**
     * Authentication ID for the remote server (e.g., `user@pam` or `user@pbs!token`).
     */
    authId: pulumi.Input<string>;
    /**
     * A comment describing this remote.
     */
    comment?: pulumi.Input<string>;
    /**
     * X509 certificate fingerprint (SHA256) for TLS verification. Format: `AA:BB:CC:...` (32 pairs of hex digits separated by colons).
     */
    fingerprint?: pulumi.Input<string>;
    /**
     * The hostname or IP address of the remote PBS server.
     */
    host: pulumi.Input<string>;
    /**
     * The unique identifier for the remote (3-32 characters).
     */
    name?: pulumi.Input<string>;
    password: pulumi.Input<string>;
    /**
     * The port number for the remote PBS server (default: 8007).
     */
    port?: pulumi.Input<number>;
}
