// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class VerifyJob extends pulumi.CustomResource {
    /**
     * Get an existing VerifyJob resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VerifyJobState, opts?: pulumi.CustomResourceOptions): VerifyJob {
        return new VerifyJob(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pbs:index/verifyJob:VerifyJob';

    /**
     * Returns true if the given object is an instance of VerifyJob.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VerifyJob {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VerifyJob.__pulumiType;
    }

    /**
     * A comment describing this verification job.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * Opaque digest returned by PBS for optimistic locking.
     */
    declare public /*out*/ readonly digest: pulumi.Output<string>;
    /**
     * Skip backups that have been recently verified. Defaults to `false`.
     */
    declare public readonly ignoreVerified: pulumi.Output<boolean>;
    /**
     * Maximum recursion depth when traversing namespace hierarchy.
     */
    declare public readonly maxDepth: pulumi.Output<number | undefined>;
    /**
     * Namespace to verify. Optional, supports pattern matching (e.g., `ns1`, `ns1/sub`).
     */
    declare public readonly namespace: pulumi.Output<string | undefined>;
    /**
     * Number of days after which a backup is considered outdated and needs re-verification. Only applies when `ignore_verified` is `true`.
     */
    declare public readonly outdatedAfter: pulumi.Output<number | undefined>;
    /**
     * When to run the verification job. Uses systemd calendar event format (e.g., `weekly`, `Mon 03:00`).
     */
    declare public readonly schedule: pulumi.Output<string>;
    /**
     * The datastore name where backups will be verified.
     */
    declare public readonly store: pulumi.Output<string>;
    /**
     * The unique identifier for the verification job.
     */
    declare public readonly verifyJobId: pulumi.Output<string>;

    /**
     * Create a VerifyJob resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VerifyJobArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VerifyJobArgs | VerifyJobState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VerifyJobState | undefined;
            resourceInputs["comment"] = state?.comment;
            resourceInputs["digest"] = state?.digest;
            resourceInputs["ignoreVerified"] = state?.ignoreVerified;
            resourceInputs["maxDepth"] = state?.maxDepth;
            resourceInputs["namespace"] = state?.namespace;
            resourceInputs["outdatedAfter"] = state?.outdatedAfter;
            resourceInputs["schedule"] = state?.schedule;
            resourceInputs["store"] = state?.store;
            resourceInputs["verifyJobId"] = state?.verifyJobId;
        } else {
            const args = argsOrState as VerifyJobArgs | undefined;
            if (args?.schedule === undefined && !opts.urn) {
                throw new Error("Missing required property 'schedule'");
            }
            if (args?.store === undefined && !opts.urn) {
                throw new Error("Missing required property 'store'");
            }
            if (args?.verifyJobId === undefined && !opts.urn) {
                throw new Error("Missing required property 'verifyJobId'");
            }
            resourceInputs["comment"] = args?.comment;
            resourceInputs["ignoreVerified"] = args?.ignoreVerified;
            resourceInputs["maxDepth"] = args?.maxDepth;
            resourceInputs["namespace"] = args?.namespace;
            resourceInputs["outdatedAfter"] = args?.outdatedAfter;
            resourceInputs["schedule"] = args?.schedule;
            resourceInputs["store"] = args?.store;
            resourceInputs["verifyJobId"] = args?.verifyJobId;
            resourceInputs["digest"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VerifyJob.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering VerifyJob resources.
 */
export interface VerifyJobState {
    /**
     * A comment describing this verification job.
     */
    comment?: pulumi.Input<string>;
    /**
     * Opaque digest returned by PBS for optimistic locking.
     */
    digest?: pulumi.Input<string>;
    /**
     * Skip backups that have been recently verified. Defaults to `false`.
     */
    ignoreVerified?: pulumi.Input<boolean>;
    /**
     * Maximum recursion depth when traversing namespace hierarchy.
     */
    maxDepth?: pulumi.Input<number>;
    /**
     * Namespace to verify. Optional, supports pattern matching (e.g., `ns1`, `ns1/sub`).
     */
    namespace?: pulumi.Input<string>;
    /**
     * Number of days after which a backup is considered outdated and needs re-verification. Only applies when `ignore_verified` is `true`.
     */
    outdatedAfter?: pulumi.Input<number>;
    /**
     * When to run the verification job. Uses systemd calendar event format (e.g., `weekly`, `Mon 03:00`).
     */
    schedule?: pulumi.Input<string>;
    /**
     * The datastore name where backups will be verified.
     */
    store?: pulumi.Input<string>;
    /**
     * The unique identifier for the verification job.
     */
    verifyJobId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a VerifyJob resource.
 */
export interface VerifyJobArgs {
    /**
     * A comment describing this verification job.
     */
    comment?: pulumi.Input<string>;
    /**
     * Skip backups that have been recently verified. Defaults to `false`.
     */
    ignoreVerified?: pulumi.Input<boolean>;
    /**
     * Maximum recursion depth when traversing namespace hierarchy.
     */
    maxDepth?: pulumi.Input<number>;
    /**
     * Namespace to verify. Optional, supports pattern matching (e.g., `ns1`, `ns1/sub`).
     */
    namespace?: pulumi.Input<string>;
    /**
     * Number of days after which a backup is considered outdated and needs re-verification. Only applies when `ignore_verified` is `true`.
     */
    outdatedAfter?: pulumi.Input<number>;
    /**
     * When to run the verification job. Uses systemd calendar event format (e.g., `weekly`, `Mon 03:00`).
     */
    schedule: pulumi.Input<string>;
    /**
     * The datastore name where backups will be verified.
     */
    store: pulumi.Input<string>;
    /**
     * The unique identifier for the verification job.
     */
    verifyJobId: pulumi.Input<string>;
}
