services:
  backups:
    user: "65534:65534"
    image: mcr.microsoft.com/dotnet/sdk:10.0@sha256:dc8430e6024d454edadad1e160e1973be3cabbb7125998ef190d9e5c6adf7dbb
    volumes:
      - ./:/workspace
      - ./keys:/keys:ro
      - ./jobs:/jobs:ro
      - /data/backup:/data/backup:rw
      # - /data/restic:/data/restic:rw
      - /spike/backup:/spike/backup:ro
      - /spike/data:/spike/data:ro
    tmpfs:
      - /tmp:uid=65534,gid=65534,exec
    working_dir: /workspace
    restart: unless-stopped
    dns:
      - 100.100.100.100
    command: dotnet run Playground.cs
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - DOTNET_NOLOGO=1
      - DOTNET_CLI_HOME=/workspace/.dotnet
      - NUGET_PACKAGES=/workspace/.nuget/packages
      - XDG_DATA_HOME=/tmp
      - TMPDIR=/tmp
      - RCLONE_CONFIG=/tmp/rclone.conf
    env_file:
      - .env
    cpus: 1
