#!/bin/sh
# graphify-sweep-commit.sh
#
# Registered as an INDEPENDENT post-commit hook via git's config-hook channel
# (hook.graphify-sweep.* -- see register-graphify-sweep.sh), not appended
# into graphify's own generated .git/hooks/post-commit script. That file is
# regenerated by `graphify hook install` from the pip-installed `graphifyy`
# package (renovate bumps it regularly); a hand-edit inside it would be
# silently reverted on the next install/upgrade.
#
# WHY THIS EXISTS: graphify's own post-commit hook rebuilds the tracked
# graph.json / GRAPH_REPORT.md in a DETACHED background process so `git
# commit` returns immediately (a full rebuild can take hours). That means the
# rebuild for commit N is almost always still running -- or has just finished
# -- by the time `git commit` for commit N returns, so its output cannot be
# folded into that SAME commit without blocking every commit on the rebuild.
# Left alone, the rebuild's output just sits as an uncommitted working-tree
# diff against tracked files (graphify-out/graph.json et al ARE tracked in
# this repo, unlike graphify-out/.graphify_python|.graphify_root|cache/).
#
# THE FIX: on every post-commit, check whether a PRIOR commit's rebuild left
# the tracked graphify-out/ files dirty and, if the working tree is otherwise
# completely clean, fold that diff into its own small commit right now. This
# lags the graph's own commit by one real commit but guarantees the rebuild's
# output never sits uncommitted for long, and it never touches anything
# outside graphify-out/.
#
# SAFETY: if anything OTHER than graphify-out/ is dirty, do nothing. That
# dirt could belong to a concurrent agent's in-progress edit sharing this
# checkout -- see .config/hk.pkl's "DELIBERATE SAFETY POSTURE" comment for
# the identical concern (hk never mutates the working tree mid-commit for
# exactly this reason). Never risk sweeping someone else's WIP into a commit
# labeled as a graphify update.
#
# This is also why the sweep runs post-commit rather than pre-commit: it only
# ever acts after a commit is already finalized, never delaying or altering
# the commit currently being made.
#
# Recursion is self-limiting: this script's own `git commit` immediately
# leaves the working tree clean, so a re-entrant post-commit invocation's
# dirty-check finds nothing and exits at the first checkpoint below.
# graphify's own hook additionally already special-cases this exact case --
# see its "Skip when only graphify-out/ artifacts changed" guard -- so a
# sweep commit never triggers another rebuild either.

set -eu

# Manual overrides. GRAPHIFY_SKIP_HOOK is graphify's own documented escape
# hatch; HK=0 is this repo's established "skip hooks for this commit" lever
# (see .config/hk.pkl).
[ "${GRAPHIFY_SKIP_HOOK:-0}" = "1" ] && exit 0
[ "${HK:-1}" = "0" ] && exit 0

# Never fire mid-rebase/merge/cherry-pick -- mirrors the guard in graphify's
# own generated post-commit hook.
GIT_DIR=${GIT_DIR:-$(git rev-parse --git-dir 2>/dev/null)}
[ -z "$GIT_DIR" ] && exit 0
[ -d "$GIT_DIR/rebase-merge" ] && exit 0
[ -d "$GIT_DIR/rebase-apply" ] && exit 0
[ -f "$GIT_DIR/MERGE_HEAD" ] && exit 0
[ -f "$GIT_DIR/CHERRY_PICK_HEAD" ] && exit 0

TOPLEVEL=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
cd "$TOPLEVEL"

[ -d graphify-out ] || exit 0

STATUS=$(git status --porcelain 2>/dev/null)
[ -z "$STATUS" ] && exit 0

# Anything dirty outside graphify-out/? Leave everything alone -- see the
# SAFETY note above.
if printf '%s\n' "$STATUS" | grep -qv 'graphify-out/'; then
    exit 0
fi

git add -A -- graphify-out

# `git add -A` can end up with nothing staged (e.g. the only "dirty" entries
# were gitignored paths that never showed up above, or a no-op touch).
if git diff --cached --quiet -- graphify-out; then
    exit 0
fi

GRAPHIFY_SKIP_HOOK=1 HK=0 git commit --no-verify --quiet -m "chore(graphify): sync knowledge graph output

Auto-committed by .config/hooks/graphify-sweep-commit.sh: folds a prior
commit's detached graphify rebuild (graph.json, GRAPH_REPORT.md, etc.) into
its own commit instead of leaving it as an uncommitted working-tree diff.

[skip-hook]" || true
