services:
  uhf-server:
    restart: unless-stopped
    dns:
      - 100.100.100.100
    image: swapplications/uhf-server:2.1.0@sha256:d6fe1dcddc9ab167cd2a7e4bd8c534446666781b169ea902d3ce1c17c04d26e9
    container_name: uhf-server
    labels:
      # Enable Traefik
      traefik.enable: true

      # Web UI routing (HTTPS)
      traefik.http.routers.${APP}.rule: Host(`uhf.${CLUSTER_DOMAIN}`)
      traefik.http.routers.${APP}.entrypoints: websecure
      traefik.http.routers.${APP}.tls.certresolver: le
      traefik.http.routers.${APP}.service: ${APP}

      traefik.http.services.${APP}.loadbalancer.server.port: 8809
    volumes:
      - /data/uhf/recordings/:/recordings
      - /opt/stacks-data/${APP}:/var/lib/uhf-server
    environment:
      PORT: "8809"
    command: uhf-server --port 8809 --recordings-dir /recordings
      --enable-commercial-detection
    networks:
      - dockge_default
networks:
  dockge_default:
    external: true
x-dockge:
  urls:
    - https://uhf.${CLUSTER_DOMAIN}
