---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  interval: 1h
  driftDetection:
    mode: enabled
  timeout: 10m
  install:
    createNamespace: true
    replace: true
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: -1
      strategy: rollback
  rollback:
    force: true
    cleanupOnFail: true
    recreate: true
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          *app :
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.2.3@sha256:4fcf15b7f265c2c8d7bc2a7e13240a07e0593c326f3cf3b5b9bb69eec5b79299
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              PUID: 568
              PGID: 568
              UMASK: "0022"
              QBT_LEGAL_NOTICE: confirm
              QBT_WEBUI_PORT: &port 8080
              QBT_TORRENTING_PORT: &port-bt 18289
              # QBT_CONFIG_PATH: /config
              # QBT_DOWNLOADS_PATH: /media/downloads/torrents
              # QBT_BitTorrent__Session__DefaultSavePath: /media/downloads/completed
              # QBT_BitTorrent__Session__TempPath: /media/downloads/torrents
              # QBT_BitTorrent__Session__TempPathEnabled: true
              QBT_Application__MemoryWorkingSetLimit:
                valueFrom:
                  resourceFieldRef:
                    containerName: *app
                    resource: limits.memory
                    divisor: 1Mi
              QBT_Preferences__WebUI__AlternativeUIEnabled: false
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
                10.10.0.0/16,100.64.0.0/10,${CLUSTER_NETWORK},${SERVICE_NETWORK}
              QBT_Preferences__WebUI__LocalHostAuth: false
              QBT_Preferences__WebUI__UseUPNP: false
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              runAsNonRoot: true
              runAsUser: 568
              runAsGroup: 568

              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                memory: 16Gi

    defaultPodOptions:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [0, 1, 44, 109, 303, 568, 10000]
        seccompProfile: { type: RuntimeDefault }

    service:
      *app :
        controller: *app
        type: ClusterIP
        ports:
          http:
            port: *port

      bittorrent:
        controller: *app
        type: LoadBalancer
        loadBalancerIP: "${QBITTORRENT_IP}"
        ports:
          bittorrent-udp:
            port: *port-bt
            protocol: UDP
            targetPort: *port-bt
          bittorrent-tcp:
            port: *port-bt
            protocol: TCP
            targetPort: *port-bt

    persistence:
      config:
        existingClaim: ${APP}
        globalMounts:
          - path: /config
      media:
        existingClaim: truenas-media
        globalMounts:
          - path: /media

    route:
      internal:
        kind: HTTPRoute
        parentRefs:
          - name: internal
            namespace: network
            kind: Gateway
        hostnames:
          - "${APP}.${ROOT_DOMAIN}"
        rules:
          - backendRefs:
              - identifier: *app
                port: *port
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: local-user
