---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app habitica
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  interval: 1h
  driftDetection:
    mode: enabled
  timeout: 15m
  install:
    createNamespace: true
    replace: true
    remediation:
      retries: 7
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 7
      strategy: rollback
  rollback:
    force: true
    cleanupOnFail: true
    recreate: true
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/awinterstein/habitica-server
              tag: 5.48.8@sha256:1352a3e100b9f6c297086d58d23d5b520198aa186f5293e1d356ea531ec70bfd
            env:
              BASE_URL: https://${APP}.${ROOT_DOMAIN}
              NODE_ENV: production
              TZ: "${TIMEZONE}"
              NODE_DB_URI: "mongodb://127.0.0.1:27017/habitica?replicaSet=rs&directConnection=true&readPreference=primary"
              INVITE_ONLY: "false"
            ports:
              - containerPort: 3000
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 3000
                  initialDelaySeconds: 10
                  periodSeconds: 20
                  timeoutSeconds: 10
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 3000
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
          mongo:
            image:
              repository: mongo
              tag: 8.3.8@sha256:44dce4b1688969ff3fdbfc438fd6113f734140ad96e3639ef17ee26a162dfb58
            ports:
              - containerPort: 27017
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
          email:
            image:
              repository: hashicorp/http-echo
              tag: 1.0.0@sha256:fcb75f691c8b0414d670ae570240cbf95502cc18a9ba57e982ecac589760a186
            args:
              - "-text=OK"
              - "-listen=:8080"
            ports:
              - containerPort: 8080
            resources:
              requests:
                cpu: 5m
                memory: 16Mi
              limits:
                memory: 64Mi

    service:
      app:
        controller: app
        type: ClusterIP
        ports:
          http:
            port: 3000

    persistence:
      data:
        existingClaim: ${APP}
        advancedMounts:
          app:
            mongo:
              - path: /data/db
                subPath: mongo
      tmp:
        type: emptyDir
        globalMounts:
          - path: /etc/environment

    route:
      internal:
        parentRefs:
          - name: internal
            namespace: network
            kind: Gateway
        hostnames:
          - "${APP}.${ROOT_DOMAIN}"
        kind: HTTPRoute
        rules:
          - backendRefs:
              - identifier: app
                port: 3000
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: local-user
