---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-env
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        TZ: "${TIMEZONE}"
        dbType: "postgres"
        dbHost: "{{ .postgres_hostname }}"
        dbPort: "{{ .postgres_port }}"
        dbName: "{{ .postgres_database }}"
        dbUser: "{{ .postgres_username }}"
        dbPassword: "{{ .postgres_password }}"
        plexTokens: "[\"{{ .media_plex_token }}\"]"
        skipFriendSync: "true"
        enablePlexPlaylistProtection: "false"
        # plexProtectionPlaylistName: "Do Not Delete"  # Name of protection playlist
        plexServerUrl: https://plex.${ROOT_DOMAIN}
        skipIfExistsOnPlex: "false"
  dataFrom:
    - extract:
        key: '${APP}-postgres'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
    - extract:
        # was: Media Management Secrets
        key: shared/media-management-secrets
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "media_$1"
