---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pulsarr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  interval: 1h
  driftDetection:
    mode: enabled
  timeout: 10m
  install:
    createNamespace: true
    replace: true
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: -1
      strategy: rollback
  rollback:
    force: true
    cleanupOnFail: true
    recreate: true
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          *app :
            image:
              repository: lakker/pulsarr
              tag: 1.1.6@sha256:4830936b1d77ca321ab2d8cdbf734f5feee35c65e99b0264569df5816cb49dcc
              pullPolicy: Always
            env:
              PUID: ${PUID}
              PGID: ${PGID}
              TZ: ${TIMEZONE}
              baseUrl: https://${APP}.${ROOT_DOMAIN}
              port: &port 3003
            envFrom:
              - secretRef:
                  name: ${APP}-env
            # probes:
            #   liveness: &probes
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /health
            #         port: *port
            #       initialDelaySeconds: 30
            #       periodSeconds: 20
            #       timeoutSeconds: 10
            #       failureThreshold: 5
            #   readiness: *probes
            securityContext:
              runAsNonRoot: true
              runAsUser: 568
              runAsGroup: 568
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [0, 1, 44, 109, 303, 568, 10000]
        seccompProfile: { type: RuntimeDefault }

    service:
      *app :
        controller: *app
        type: ClusterIP
        ports:
          http:
            port: *port

    route:
      internal:
        kind: HTTPRoute
        parentRefs:
          - name: internal
            namespace: network
            kind: Gateway
        hostnames:
          - "${APP}.${ROOT_DOMAIN}"
        rules:
          - backendRefs:
              - identifier: *app
                port: *port
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: local-user

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/data
