// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ProviderStigCompliance {
    /**
     * Security categorization for STIG validation.
     */
    categorization?: pulumi.Input<inputs.ProviderStigComplianceCategorization | undefined>;
    /**
     * Enable STIG validation on all resources.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * STIG enforcement policy: strict (errors block apply), warn (warnings only), silent (suppress all). Default: strict.
     */
    enforcement?: pulumi.Input<string | undefined>;
    /**
     * National Security System mode — requires full CNSSI 1253 categorization.
     */
    nss?: pulumi.Input<boolean | undefined>;
    /**
     * List of DNS-REQ-XXX requirement IDs to suppress. Suppressed findings emit warnings instead of errors.
     */
    suppresses?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface ProviderStigComplianceCategorization {
    /**
     * Availability objective level: low, moderate, high. Required when nss = true.
     */
    availability?: pulumi.Input<string | undefined>;
    /**
     * Shorthand baseline: low, moderate, high. Only when nss = false. Mutually exclusive with individual objectives.
     */
    baseline?: pulumi.Input<string | undefined>;
    /**
     * Confidentiality objective level: low, moderate, high. Required when nss = true.
     */
    confidentiality?: pulumi.Input<string | undefined>;
    /**
     * Integrity objective level: low, moderate, high. Required when nss = true.
     */
    integrity?: pulumi.Input<string | undefined>;
}

export interface ZoneDnssec {
    /**
     * DNSSEC signing algorithm. Valid values: ECDSA, EDDSA, RSA. Maps to STIG BIND-9X-002050 (SC-13).
     */
    algorithm?: pulumi.Input<string | undefined>;
    /**
     * Curve for ECDSA (P256, P384) or EDDSA (ED25519, ED448). Default: P256.
     */
    curve?: pulumi.Input<string | undefined>;
    /**
     * Enable DNSSEC signing for the zone.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * NSEC/NSEC3 proof of non-existence. Maps to STIG BIND-9X-001270 (SC-20).
     */
    nxProof?: pulumi.Input<string | undefined>;
}
export namespace config {
}
