---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-env
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        TZ: "${TIMEZONE}"
        CRON_MIN: "1,31"
        # OIDC Configuration
        OIDC_ENABLED: "1"
        OIDC_PROVIDER_METADATA_URL: "{{ .oidc_openid_configuration_url }}"
        OIDC_REMOTE_USER_CLAIM: "preferred_username"
        OIDC_SCOPES: "openid email profile"
        OIDC_X_FORWARDED_HEADERS: "X-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto"
        # Database Configuration
        DB_TYPE: "pgsql"
        DB_HOST: "{{ .postgres_hostname }}"
        DB_PORT: "{{ .postgres_port }}"
        DB_NAME: "{{ .postgres_database }}"
        DB_USER: "{{ .postgres_username }}"
        DB_PASSWORD: "{{ .postgres_password }}"
        # HTTP Configuration
        HTTP_HOST: "0.0.0.0"
        HTTP_PORT: "80"
        # OIDC Credentials
        OIDC_CLIENT_ID: "{{ .oidc_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        OIDC_CLIENT_CRYPTO_KEY: "{{ .crypto_password }}"
  dataFrom:
    - extract:
        # was: FreshRSS Crypto Key
        key: shared/freshrss-crypto-key
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "crypto_$1"
    - extract:
        key: '${APP}-postgres'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
    - extract:
        key: '${APP}-oidc-credentials'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: cluster
      rewrite:
        - regexp:
            source: "(.*)"
            target: "oidc_$1"
