services:
  authentik_proxy:
    container_name: authentik-outpost
    image: ghcr.io/goauthentik/proxy:2026.2.3@sha256:e37186957e16a956e078302af73ced7045c956fcd2574107b4acdb6f929e4d36
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -T 5 -O - http://127.0.0.1:9000/outpost.goauthentik.io/ping
            >/dev/null || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    dns:
      - 100.100.100.100
    # env is set in each app stack for the secret.
    env_file:
      - path: .env
        required: true
      - path: .env-token
        required: false
    labels:
      autoheal: true
      # Enable Traefik
      traefik.enable: true

      # Outpost
      traefik.http.routers.authentik-outpost.rule: Host(`${APP}.${CLUSTER_DOMAIN}`)
      traefik.http.routers.authentik-outpost.entrypoints: websecure
      traefik.http.routers.authentik-outpost.service: authentik-outpost
      traefik.http.routers.authentik-outpost.tls.certresolver: le

      traefik.http.routers.authentik-outpost-tailscale.rule: Host(`${APP}-${host}.${tailscaleDomain}`)
      traefik.http.routers.authentik-outpost-tailscale.entrypoints: tailscale
      traefik.http.routers.authentik-outpost-tailscale.service: authentik-outpost

      traefik.http.services.authentik-outpost.loadbalancer.healthcheck.path: "/outpost.goauthentik.io/ping"
      traefik.http.services.authentik-outpost.loadbalancer.healthcheck.port: 9300
      traefik.http.services.authentik-outpost.loadbalancer.server.port: 9000

    networks:
      - dockge_default
    ports:
      - 9000:9000
x-dockge:
  urls:
    - https://${APP}.${CLUSTER_DOMAIN}
networks:
  dockge_default:
    external: true
