---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app unpoller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        UP_UNIFI_DEFAULT_USER: "{{ .unifi_username }}"
        UP_UNIFI_DEFAULT_PASS: "{{ .unifi_password }}"
        UP_UNIFI_DEFAULT_API_KEY: "{{ .apikey_credential }}"

  dataFrom:
    - extract:
        # was: unifipoller
        key: shared/unifipoller
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "unifi_$1"
    - extract:
        # was: Unifi Api Key Eris Cluster
        key: shared/unifi-api-key-eris-cluster
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "apikey_$1"
