---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 7.3.0
    digest: sha256:ba8b6b3ee954c9d6eeee713d148a22e6f73eb440189e11acd3112a06acdfd2f8
  url: oci://ghcr.io/grafana/helm-charts/loki
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 1h
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: loki
  install:
    crds: Skip
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      retries: 3
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      analytics:
        reporting_enabled: false
      commonConfig:
        replication_factor: 1
      compactor:
        working_directory: /var/loki/compactor/retention
        delete_request_store: filesystem
        retention_enabled: true
        retention_delete_delay: 1h
      ingester:
        chunk_encoding: snappy
      limits_config:
        retention_period: 3d
        ingestion_rate_mb: 16
        ingestion_burst_size_mb: 32
        retention_stream:
          - selector: '{namespace="pulumi"}'
            priority: 1
            period: 24h
          - selector: '{namespace="flux-system"}'
            priority: 1
            period: 48h
      server:
        grpc_server_max_recv_msg_size: 10485760 # 10 MiB
        grpc_server_max_send_msg_size: 10485760 # 10 MiB
        log_level: info
      storage:
        type: filesystem
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      schemaConfig:
        configs:
          - from: "2024-04-01" # quote
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      structuredConfig:
        ruler:
          enable_api: true
          enable_alertmanager_v2: true
          alertmanager_url: http://alertmanager-operated.observability.svc.cluster.local:9093
          storage:
            type: local
            local:
              directory: /rules
          rule_path: /tmp/loki/rules-temp
    singleBinary:
      replicas: 1
      priorityClassName: observability-critical
      persistence:
        enabled: true
        storageClass: longhorn
        size: 60Gi
      service:
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/hostname: loki
          tailscale.com/tags: tag:observability
          tailscale.com/proxy-group: tailnet-outbound
    gateway:
      enabled: false
      replicas: 0
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    lokiCanary:
      enabled: false
    test:
      enabled: false
    sidecar:
      image:
        repository: ghcr.io/kiwigrid/k8s-sidecar
        tag: "2.10.1@sha256:440db6dcf9a724fa2c167612e147ad8839e75104732dc7ec89783e73199837f0"
      enableUniqueFilenames: true
      rules:
        searchNamespace: ALL
        folder: /rules/fake
