services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz:0.7.6-nbxyz10
    container_name: netbootxyz
    environment:
      - MENU_VERSION=2.0.84 # optional
      - NGINX_PORT=80 # optional
      - WEB_APP_PORT=3000 # optional
    labels:
      # Enable Traefik
      - traefik.enable=true

      # NetbootXYZ UI (port 3000) - HTTPS with domain
      - traefik.http.routers.netbootxyz-ui.rule=Host(`netbootxyz.${searchDomain}`)
      - traefik.http.routers.netbootxyz-ui.entrypoints=websecure
      - traefik.http.routers.netbootxyz-ui.tls.certresolver=le
      - traefik.http.routers.netbootxyz-ui.service=netbootxyz-ui
      - traefik.http.services.netbootxyz-ui.loadbalancer.server.port=3000

      # NetbootXYZ Nginx server (port 80) - HTTP for PXE boot clients (Default/Fallback)
      - traefik.http.routers.netbootxyz-pxe.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.netbootxyz-pxe.entrypoints=web
      - traefik.http.routers.netbootxyz-pxe.priority=1
      - traefik.http.routers.netbootxyz-pxe.service=netbootxyz-pxe
      - traefik.http.services.netbootxyz-pxe.loadbalancer.server.port=80
    # volumes:
    #   - /path/to/config:/config # optional
    #   - /path/to/assets:/assets # optional
    ports:
      - 1234:3000 # optional, destination should match ${WEB_APP_PORT} variable above.
      - 69:69/udp
      # Removed 80:80 mapping - Traefik will handle HTTP routing
    restart: unless-stopped
    networks:
      - dockge_default
x-dockge:
  urls:
    - https://netbootxyz.${searchDomain}
networks:
  dockge_default:
    external: true
