// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ProviderOauth2Dcr extends pulumi.CustomResource {
    /**
     * Get an existing ProviderOauth2Dcr resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProviderOauth2DcrState, opts?: pulumi.CustomResourceOptions): ProviderOauth2Dcr {
        return new ProviderOauth2Dcr(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/providerOauth2Dcr:ProviderOauth2Dcr';

    /**
     * Returns true if the given object is an instance of ProviderOauth2Dcr.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProviderOauth2Dcr {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProviderOauth2Dcr.__pulumiType;
    }

    /**
     * Maximum access token validity for registered clients. Format: hours=1;minutes=2;seconds=3. Generated.
     */
    declare public readonly accessTokenValidity: pulumi.Output<string>;
    /**
     * If empty, all grant types are allowed. Allowed values:
     *   - `authorization_code`
     *   - `implicit`
     *   - `hybrid`
     *   - `refresh_token`
     *   - `client_credentials`
     *   - `password`
     *   - `urn:ietf:params:oauth:grant-type:device_code`
     *   - `urn:ietf:params:oauth:grant-type:token-exchange`
     */
    declare public readonly allowedGrantTypes: pulumi.Output<string[] | undefined>;
    /**
     * Group to assign to automatically created applications.
     */
    declare public readonly defaultApplicationGroup: pulumi.Output<string | undefined>;
    /**
     * PK of the OAuth2 provider dynamic client registration applies to.
     */
    declare public readonly oauth2Provider: pulumi.Output<number>;
    /**
     * Authorization flow applied to dynamically registered clients.
     */
    declare public readonly overrideAuthorizationFlow: pulumi.Output<string | undefined>;
    declare public readonly overrideInvalidationFlow: pulumi.Output<string | undefined>;
    declare public readonly overridePropertyMappings: pulumi.Output<string[] | undefined>;
    /**
     * Allowed values:
     *   - `all`
     *   - `any`
     *      Generated.
     */
    declare public readonly policyEngineMode: pulumi.Output<string>;
    declare public readonly providerOauth2DcrId: pulumi.Output<string>;
    /**
     * Maximum refresh token validity for registered clients. Format: hours=1;minutes=2;seconds=3. Generated.
     */
    declare public readonly refreshTokenValidity: pulumi.Output<string>;

    /**
     * Create a ProviderOauth2Dcr resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderOauth2DcrArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProviderOauth2DcrArgs | ProviderOauth2DcrState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProviderOauth2DcrState | undefined;
            resourceInputs["accessTokenValidity"] = state?.accessTokenValidity;
            resourceInputs["allowedGrantTypes"] = state?.allowedGrantTypes;
            resourceInputs["defaultApplicationGroup"] = state?.defaultApplicationGroup;
            resourceInputs["oauth2Provider"] = state?.oauth2Provider;
            resourceInputs["overrideAuthorizationFlow"] = state?.overrideAuthorizationFlow;
            resourceInputs["overrideInvalidationFlow"] = state?.overrideInvalidationFlow;
            resourceInputs["overridePropertyMappings"] = state?.overridePropertyMappings;
            resourceInputs["policyEngineMode"] = state?.policyEngineMode;
            resourceInputs["providerOauth2DcrId"] = state?.providerOauth2DcrId;
            resourceInputs["refreshTokenValidity"] = state?.refreshTokenValidity;
        } else {
            const args = argsOrState as ProviderOauth2DcrArgs | undefined;
            if (args?.oauth2Provider === undefined && !opts.urn) {
                throw new Error("Missing required property 'oauth2Provider'");
            }
            resourceInputs["accessTokenValidity"] = args?.accessTokenValidity;
            resourceInputs["allowedGrantTypes"] = args?.allowedGrantTypes;
            resourceInputs["defaultApplicationGroup"] = args?.defaultApplicationGroup;
            resourceInputs["oauth2Provider"] = args?.oauth2Provider;
            resourceInputs["overrideAuthorizationFlow"] = args?.overrideAuthorizationFlow;
            resourceInputs["overrideInvalidationFlow"] = args?.overrideInvalidationFlow;
            resourceInputs["overridePropertyMappings"] = args?.overridePropertyMappings;
            resourceInputs["policyEngineMode"] = args?.policyEngineMode;
            resourceInputs["providerOauth2DcrId"] = args?.providerOauth2DcrId;
            resourceInputs["refreshTokenValidity"] = args?.refreshTokenValidity;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProviderOauth2Dcr.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ProviderOauth2Dcr resources.
 */
export interface ProviderOauth2DcrState {
    /**
     * Maximum access token validity for registered clients. Format: hours=1;minutes=2;seconds=3. Generated.
     */
    accessTokenValidity?: pulumi.Input<string | undefined>;
    /**
     * If empty, all grant types are allowed. Allowed values:
     *   - `authorization_code`
     *   - `implicit`
     *   - `hybrid`
     *   - `refresh_token`
     *   - `client_credentials`
     *   - `password`
     *   - `urn:ietf:params:oauth:grant-type:device_code`
     *   - `urn:ietf:params:oauth:grant-type:token-exchange`
     */
    allowedGrantTypes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Group to assign to automatically created applications.
     */
    defaultApplicationGroup?: pulumi.Input<string | undefined>;
    /**
     * PK of the OAuth2 provider dynamic client registration applies to.
     */
    oauth2Provider?: pulumi.Input<number | undefined>;
    /**
     * Authorization flow applied to dynamically registered clients.
     */
    overrideAuthorizationFlow?: pulumi.Input<string | undefined>;
    overrideInvalidationFlow?: pulumi.Input<string | undefined>;
    overridePropertyMappings?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Allowed values:
     *   - `all`
     *   - `any`
     *      Generated.
     */
    policyEngineMode?: pulumi.Input<string | undefined>;
    providerOauth2DcrId?: pulumi.Input<string | undefined>;
    /**
     * Maximum refresh token validity for registered clients. Format: hours=1;minutes=2;seconds=3. Generated.
     */
    refreshTokenValidity?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ProviderOauth2Dcr resource.
 */
export interface ProviderOauth2DcrArgs {
    /**
     * Maximum access token validity for registered clients. Format: hours=1;minutes=2;seconds=3. Generated.
     */
    accessTokenValidity?: pulumi.Input<string | undefined>;
    /**
     * If empty, all grant types are allowed. Allowed values:
     *   - `authorization_code`
     *   - `implicit`
     *   - `hybrid`
     *   - `refresh_token`
     *   - `client_credentials`
     *   - `password`
     *   - `urn:ietf:params:oauth:grant-type:device_code`
     *   - `urn:ietf:params:oauth:grant-type:token-exchange`
     */
    allowedGrantTypes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Group to assign to automatically created applications.
     */
    defaultApplicationGroup?: pulumi.Input<string | undefined>;
    /**
     * PK of the OAuth2 provider dynamic client registration applies to.
     */
    oauth2Provider: pulumi.Input<number>;
    /**
     * Authorization flow applied to dynamically registered clients.
     */
    overrideAuthorizationFlow?: pulumi.Input<string | undefined>;
    overrideInvalidationFlow?: pulumi.Input<string | undefined>;
    overridePropertyMappings?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Allowed values:
     *   - `all`
     *   - `any`
     *      Generated.
     */
    policyEngineMode?: pulumi.Input<string | undefined>;
    providerOauth2DcrId?: pulumi.Input<string | undefined>;
    /**
     * Maximum refresh token validity for registered clients. Format: hours=1;minutes=2;seconds=3. Generated.
     */
    refreshTokenValidity?: pulumi.Input<string | undefined>;
}
