---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app questarr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  interval: 1h
  driftDetection:
    mode: enabled
  timeout: 10m
  install:
    createNamespace: true
    replace: true
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: -1
      strategy: rollback
  rollback:
    force: true
    cleanupOnFail: true
    recreate: true
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/doezer/questarr
              tag: v1.4.2@sha256:6faaf75f484a20805309315dd9eb9f1550b039a668efb89c13fc028c72b45485
              pullPolicy: IfNotPresent
            env:
              PUID: "1001"
              PGID: "1001"
              UMASK: "002"
              PORT: &port 5000
              TZ: ${TIMEZONE}
            workingDir: /app
            envFrom:
              - secretRef:
                  name: ${APP}-env
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 5
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              runAsUser: 0
              runAsGroup: 0
              # capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 2Gi

    defaultPodOptions:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: app
        type: ClusterIP
        ports:
          http:
            port: *port

    persistence:
      config:
        existingClaim: ${APP}
        globalMounts:
          - path: /app/data
      media:
        existingClaim: truenas-media
        globalMounts:
          - path: /media/downloads
            subPath: downloads
          - path: /media/games
            subPath: games
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp

    route:
      internal:
        parentRefs:
          - name: internal
            namespace: network
            kind: Gateway
        hostnames:
          - "${APP}.${ROOT_DOMAIN}"
        kind: HTTPRoute
        rules:
          - matches:
              - headers:
                  - name: X-Api-Key
                    value: ".*"
                    type: RegularExpression
            backendRefs:
              - identifier: app
                port: *port
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: local-user
          - backendRefs:
              - identifier: app
                port: *port
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: authenticated-user
