services:
  arcane:
    image: ghcr.io/getarcaneapp/manager:latest@sha256:540c01198ca3e58dfd398d25c57c8dc241fa7e7f3d1d8d646c8268f19525b1a8
    container_name: arcane
    volumes:
      - arcane-data:/app/data
      - ./oidc-mapping.json:/app/oidc-mapping.json:ro
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
    env_file:
      - .env
    restart: unless-stopped
    dns:
      - 100.100.100.100
    networks:
      - dockge_default
    labels:
      # Enable Traefik
      traefik.enable: true

      # Arcane - HTTPS
      traefik.http.routers.arcane.rule: Host(`arcane.${searchDomain}`)
      traefik.http.routers.arcane.entrypoints: websecure
      traefik.http.routers.arcane.tls.certresolver: le
      traefik.http.routers.arcane.service: arcane

      traefik.http.routers.arcane-tailscale.rule: Host(`arcane.${tailscaleDomain}`)
      traefik.http.routers.arcane-tailscale.entrypoints: tailscale
      traefik.http.routers.arcane-tailscale.service: arcane

      traefik.http.services.arcane.loadbalancer.server.port: 3552
    healthcheck:
      test: ['CMD', '/app/arcane', 'health']
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  arcane-data: {}

networks:
  dockge_default:
    external: true
