services:
  rclone-sftp:
    user: "65534:65534"
    container_name: rclone-sftp
    image: rclone/rclone:1.74.3@sha256:623378ad0ff3ebd5cebf77720843c0e02edfe46e2d5b5ac6bed54c6371780dfb
    restart: unless-stopped
    dns:
      - 100.100.100.100
    env_file:
      - path: .env
    command: >-
      serve sftp /data/ --addr :2022
      --authorized-keys /config/ssh/authorized_keys
      --key /config/ssh/host_key
    volumes:
      - /data/backup/:/data/backup/:rw
      - /opt/stacks-data/:/data/stacks/:ro
      - /opt/stacks-data/${APP}/keys:/config/ssh:ro
    tmpfs:
      - /.cache:uid=65534,gid=65534
    networks:
      - dockge_default
    labels:
      traefik.enable: true
      traefik.tcp.routers.rclone-sftp.rule: HostSNI(`*`)
      traefik.tcp.routers.rclone-sftp.entrypoints: sftp
      traefik.tcp.services.rclone-sftp.loadbalancer.server.port: 2022

networks:
  dockge_default:
    external: true
