#!/bin/sh
# Keeps DBHub's source list equal to "every database that exists".
#
# Runs as the `sources` native sidecar of MCPServer toolhive-postgres
# (../postgres.yaml), in the CNPG PostgreSQL image for its psql. It lists the
# connectable databases on the shared cluster (database/postgres) every
# $INTERVAL seconds and renders /config/dbhub.toml:
#
#   * one `[[sources]]` per database there, via the shared superuser -- so a
#     new app's database shows up without anyone editing this repo;
#   * `authentik`, the one database on the dedicated authentik-pg cluster
#     (stargate-command), via authentik's own owner role -- READ-ONLY, since
#     that database is the estate's SSO and superuser access is off there.
#
# Credentials never land in the file: it carries dollar-brace placeholders
# (PG_USER, PG_PASSWORD, ...) that DBHub interpolates from the `mcp` container's own env at
# load time. Host and port are not secret and are written literally.
#
# The file is rewritten IN PLACE (truncate + write), never mv'd over:
# DBHub hot-reloads via fs.watch on the file itself and only acts on
# `change` events, so a rename would silently detach the watcher. A torn read
# is covered by DBHub's 500ms debounce plus validate-then-rollback on reload.
#
# Mounted from a ConfigMap annotated `kustomize.toolkit.fluxcd.io/substitute:
# disabled` (../kustomization.yaml) -- Flux's envsubst would otherwise
# expand the placeholders below at build time.
set -eu

out=/config/dbhub.toml
tmp=/config/.dbhub.toml.next
ready=/config/.ready
interval=${INTERVAL:-300}

render() {
  # -X: no ~/.psqlrc. ON_ERROR_STOP so a failed query fails the render (and
  # the previous file stays) rather than emitting an empty source list.
  dbs=$(psql -X -v ON_ERROR_STOP=1 -At \
    "host=$PGHOST port=$PGPORT dbname=postgres user=$PGUSER sslmode=disable connect_timeout=10" \
    -c "select datname from pg_database where datallowconn and not datistemplate order by 1")
  [ -n "$dbs" ] || { echo "dbhub-sources: no databases listed" >&2; return 1; }

  {
    echo "# Generated by dbhub-sources.sh -- do not edit; see ../postgres.yaml."
    for db in $dbs; do
      cat <<EOF

[[sources]]
id = "$db"
description = "PostgreSQL database '$db' on the shared CNPG cluster (database/postgres)"
type = "postgres"
host = "$PGHOST"
port = $PGPORT
database = "$db"
user = "\${PG_USER}"
password = "\${PG_PASSWORD}"
sslmode = "disable"
lazy = true
EOF
    done
    cat <<EOF

[[sources]]
id = "authentik"
description = "authentik's database on its dedicated CNPG cluster (stargate-command/authentik-pg). The estate's SSO: read-only here."
type = "postgres"
host = "$AUTHENTIK_PGHOST"
port = 5432
database = "authentik"
user = "\${AUTHENTIK_PG_USER}"
password = "\${AUTHENTIK_PG_PASSWORD}"
sslmode = "disable"
lazy = true

# Listing any [[tools]] for a source REPLACES its default built-ins, so both
# are spelled out. readonly applies to execute_sql only.
[[tools]]
name = "execute_sql"
source = "authentik"
readonly = true

[[tools]]
name = "search_objects"
source = "authentik"
EOF
  } > "$tmp"
}

while :; do
  if render; then
    if ! cmp -s "$tmp" "$out" 2>/dev/null; then
      cat "$tmp" > "$out"
      echo "dbhub-sources: wrote $(grep -c '^\[\[sources\]\]' "$out") sources to $out"
    fi
    touch "$ready"
  else
    echo "dbhub-sources: render failed; keeping the previous $out" >&2
  fi
  rm -f "$tmp"
  sleep "$interval"
done
