---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-env
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  refreshPolicy: Periodic
  refreshInterval: 4m
  target:
    name: ${APP}-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
        annotations:
          reloader.stakater.com/auto: "true"
      data:
        TZ: "${TIMEZONE}"
        ROMM_DB_DRIVER: postgresql
        ROMM_AUTH_SECRET_KEY: "{{ .romm_password }}"
        DB_HOST: "{{ .postgres_hostname }}"
        DB_PORT: "{{ .postgres_port }}"
        DB_NAME: "{{ .postgres_database }}"
        DB_USER: "{{ .postgres_username }}"
        DB_PASSWD: "{{ .postgres_password }}"
        IGDB_CLIENT_ID: "{{ .twitch_username }}"
        IGDB_CLIENT_SECRET: "{{ .twitch_credential }}"
        RETROACHIEVEMENTS_API_KEY: "{{ .retroachievements_credential }}"
        FLASHPOINT_API_ENABLED: "true"
        HLTB_API_ENABLED: "true"
        ENABLE_EXPERIMENTAL_REDIS: "true"
        REDIS_HOST: valkey.database.svc.cluster.local
        REDIS_PORT: "6379"
        REDIS_DB: "5"
        PLAYMATCH_API_ENABLED: "true"
        HASHEOUS_API_ENABLED: "true"
        LAUNCHBOX_API_ENABLED: "true"
        STEAMGRIDDB_API_KEY: "{{ .sgdb_credential }}"
        DISABLE_DOWNLOAD_ENDPOINT_AUTH: "true"
        DISABLE_USERPASS_LOGIN: "true"
        ENABLE_RESCAN_ON_FILESYSTEM_CHANGE: "true"
        ENABLE_SCHEDULED_RESCAN: "true"
        ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB: "true"
        ENABLE_SCHEDULED_UPDATE_LAUNCHBOX_METADATA: "true"
        OIDC_ENABLED: "true"
        OIDC_PROVIDER: "${CLUSTER_TITLE}"
        OIDC_CLIENT_ID: "{{ .oidc_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        OIDC_REDIRECT_URI: https://${APP}.${ROOT_DOMAIN}/api/oauth/openid
        OIDC_SERVER_APPLICATION_URL: "{{ .oidc_issuer }}"
        OIDC_CLAIM_ROLES: groups
        OIDC_ROLE_ADMIN: admins
        OIDC_ROLE_EDITOR: media-managers
        OIDC_ROLE_VIEWER: "*"

  dataFrom:
    - extract:
        # was: Twitch Developer
        key: shared/twitch-developer
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "twitch_$1"
    - extract:
        # was: SteamGridDB
        key: shared/steamgriddb
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "sgdb_$1"
    - extract:
        # was: Retro Achievements Api Key
        key: shared/retro-achievements-api-key
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "retroachievements_$1"
    - extract:
        # was: Romm Secret Key
        key: shared/romm-secret-key
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "romm_$1"
    - extract:
        key: '${APP}-oidc-credentials'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: cluster
      rewrite:
        - regexp:
            source: "(.*)"
            target: "oidc_$1"
    - extract:
        key: '${APP}-postgres'
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database
      rewrite:
        - regexp:
            source: "[\\W]"
            target: _
        - regexp:
            source: "(.*)"
            target: "postgres_$1"
