services:
  autoheal:
    image: willfarrell/autoheal:1.2.0@sha256:31f580ef0279eaced5b38d631b08c474d70d8403c1c2fdd6ddcf2e879d5f3f7c
    container_name: autoheal
    restart: unless-stopped
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
      AUTOHEAL_INTERVAL: 30
      AUTOHEAL_START_PERIOD: 120
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: 15
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: false
