---
# yaml-language-server: $schema=https://raw.githubusercontent.com/david-driscoll/stargate-command-cluster/refs/heads/main/schemas/definition.schema.json
apiVersion: driscoll.dev/v1
kind: ApplicationDefinition
metadata:
  name: ${APP}
spec:
  name: "Karakeep"
  category: Applications
  description: "Bookmark everything app with AI tagging and crawling"
  url: &url https://${APP}.${ROOT_DOMAIN}
  icon: https://raw.githubusercontent.com/karakeep-app/karakeep/main/screenshots/logo.png
  access_policy:
    groups:
      - family
  authentik:
    oauth2:
      clientType: confidential
      allowedRedirectUris:
        - url: https://${APP}.${ROOT_DOMAIN}/api/auth/callback/custom
        - url: https://${APP}.${TAILSCALE_DOMAIN}/api/auth/callback/custom
      propertyMappings:
        - email
        - openid
        - profile
      includeClaimsInIdToken: true
      subMode: user_email
  gatus:
    - group: "Applications"
      url: *url
      method: GET
      conditions:
        - "[STATUS] == 200"
