#!/usr/bin/env bash
#MISE description="Update Pulumi stacks"

for dir in stacks/*/; do
  echo "Running in $(basename "$dir")..."
  pushd "stacks/$(basename "$dir")" > /dev/null || continue
  mise exec -- npm run up || echo "Failed in $dir"
  popd > /dev/null || continue
done
