# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: postgres-user-password
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:SDRxboR2FOtZW1gl6tac9w==,iv:iUYu0loVu6CQRI+xr+BpEju0D/JLNzovF+K9F8/Mihk=,tag:ToHJ2iusll326oZGK/bkUA==,type:str]
  database: ENC[AES256_GCM,data:ZJm969T9F8k=,iv:VXYsNptnNZWuX8D3G11GOPrZgw6HCbpTShENZL5l2ag=,tag:C+aGkbmExlvRNENPv7sDhA==,type:str]
  port: ENC[AES256_GCM,data:+6K7Ug==,iv:lVaLtqgn29o7VqAW7o+sDVwrEEoX4mBU5ap9hHD5ils=,tag:5Jv+Lb6LSQMsve2TZbGvJQ==,type:str]
  hostname: ENC[AES256_GCM,data:WZrbYYdmKlNVIyQdGu8eOl4UhYWL60AsQM1BSGTdw5pK2yENiA0=,iv:5JcewsstE1Lyj1+w9EiOu05eZi2Pppv8PcQ1oB3KnZw=,tag:NdTzOk+7rVVokxmPkSib3w==,type:str]
  password: ENC[AES256_GCM,data:M5onUai/6r49bML/mzzg269hBp10beSU7eENF3NCl3c=,iv:57hckQG16tJoF0XUGKIN4IJePX/z9darAJdZ2IIxCWw=,tag:9YSGSAs6z56KSMb9ZBCiUg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aEFoMitMUnhyLzBUb3BI
        TFVJNjkzRmpOUHNHK3ZQYmQxaWJFL21OUXlJClUyOFVTMGhWdzZTazhMbCtNaHZh
        cFlQc3VFN0VwQUNKcDArRFFpc3BRQlUKLS0tIGJxVnlnTDFwSHk5M1VpTktLOUVl
        cWVMOEplVXRIaFZOUnprSlBJL3AwTk0KETL0gvC9PhAoGJVnA9QGPijdrfODdn2N
        NC2mCC9UhA0hsZQ+creHRu4mX54OiLDP1/+h6f0gXuT0vK7R6ydz3Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwM2RxU1dxS1NQZkF0WnFl
        VmpuZHZhblFzcG5XNUJuaU5IUU1Vb0NXVkg4CkdLZ2NqSmN1RDlvekQxZ2VKR2tM
        Uzd3RXlkaytKMjQ0QnhhWjJSSGFjd1EKLS0tIGRYbVYwUGtOY3V2d0Z4cU9KWk1R
        KzdNTmtoTW9xeG00WnduTEM1TTdVK2sKh1XzYXUzxUn/CTX8dtUIIXQ3a4JTAB37
        QWGlV8OYJj//dFrYSpV86E3QtordntFAvNeqXWUX2ejLJIZU/d/KZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-26T13:08:27Z"
  mac: ENC[AES256_GCM,data:sKnKLftHbcxaNJ5SdvJBAD4BK2BA6opHTietgh3z/59vQZEBcqZNMyzeSrCa7EPKvERz++h+lTpJ9VWUzW2KP0uaMUdRTSB1wtSMEb3/yg2eByb5i04TXmCUwOo151TQ0LnuGejm5Af/CrY0QhmkLTnMJOhGuTl74nzQ2KULq4g=,iv:mRzC8zL5k5A+tdaB7TR0bZ+7xC8zfBH5rIigA1YhtL0=,tag:g2LZoGtuNTe/iiT3p7ACrQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser-password
  labels:
    cnpg.io/reload: "true"
stringData:
  username: ENC[AES256_GCM,data:5ZQBZFSu8yM=,iv:cDU9mbIQ/MnTKcLY9bEDjOg10HEwKL8217/YOMettro=,tag:cpVtpCsTAUDWNfJvAnrQQA==,type:str]
  database: ENC[AES256_GCM,data:fMr/Q4ZfXzM=,iv:GgPegeTUf/7a7NZcahV4cjguw8uKUWpuchOrJTyPDAY=,tag:uL99pbKB2sLUtXfzYAVytQ==,type:str]
  port: ENC[AES256_GCM,data:KlrNLw==,iv:5TFxpwqT0xZAoP8wlGkHNvLmyFQQbVJMeuxKPwhersY=,tag:R9RTB0dmqnup6I8oWEnBhQ==,type:str]
  hostname: ENC[AES256_GCM,data:qqQpQej5uTams4OAy2Xl2qJDYxcxzHyZQISue6JNf1K4hy2R2R8=,iv:PDZzA/c3HUxyuMBoPuilLeM6QcYLUofAcP0Da24jcbo=,tag:19bQcg2n0VYa4MqvIxgcPg==,type:str]
  password: ENC[AES256_GCM,data:2Z4vkN4/3qJ0SoiuHdmDerLAGHLZaBUi8y9ry2hvg3A58JpBDUZLZle4iQlIo3y4BgIq7deX0DuynDP6Avr0ug==,iv:Vg8RmWbQBX+txtFl2OiIfTpQBNeRCZloKjigX6rmxKs=,tag:19Hlo5sDevdECpiUAA2JeQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aEFoMitMUnhyLzBUb3BI
        TFVJNjkzRmpOUHNHK3ZQYmQxaWJFL21OUXlJClUyOFVTMGhWdzZTazhMbCtNaHZh
        cFlQc3VFN0VwQUNKcDArRFFpc3BRQlUKLS0tIGJxVnlnTDFwSHk5M1VpTktLOUVl
        cWVMOEplVXRIaFZOUnprSlBJL3AwTk0KETL0gvC9PhAoGJVnA9QGPijdrfODdn2N
        NC2mCC9UhA0hsZQ+creHRu4mX54OiLDP1/+h6f0gXuT0vK7R6ydz3Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwM2RxU1dxS1NQZkF0WnFl
        VmpuZHZhblFzcG5XNUJuaU5IUU1Vb0NXVkg4CkdLZ2NqSmN1RDlvekQxZ2VKR2tM
        Uzd3RXlkaytKMjQ0QnhhWjJSSGFjd1EKLS0tIGRYbVYwUGtOY3V2d0Z4cU9KWk1R
        KzdNTmtoTW9xeG00WnduTEM1TTdVK2sKh1XzYXUzxUn/CTX8dtUIIXQ3a4JTAB37
        QWGlV8OYJj//dFrYSpV86E3QtordntFAvNeqXWUX2ejLJIZU/d/KZQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-26T13:08:27Z"
  mac: ENC[AES256_GCM,data:sKnKLftHbcxaNJ5SdvJBAD4BK2BA6opHTietgh3z/59vQZEBcqZNMyzeSrCa7EPKvERz++h+lTpJ9VWUzW2KP0uaMUdRTSB1wtSMEb3/yg2eByb5i04TXmCUwOo151TQ0LnuGejm5Af/CrY0QhmkLTnMJOhGuTl74nzQ2KULq4g=,iv:mRzC8zL5k5A+tdaB7TR0bZ+7xC8zfBH5rIigA1YhtL0=,tag:g2LZoGtuNTe/iiT3p7ACrQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
