// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetGpgKeyEmail {
    email: string;
    verified: boolean;
}

export interface GetGpgKeySubkey {
    canCertify: boolean;
    canEncryptComms: boolean;
    canEncryptStorage: boolean;
    canSign: boolean;
    createdAt: string;
    expiresAt: string;
    id: number;
    keyId: string;
    primaryKeyId: string;
    publicKey: string;
}

export interface GetRepositoryExternalTracker {
    /**
     * External issue tracker URL format.
     */
    externalTrackerFormat: string;
    /**
     * External issue tracker issue regular expression.
     */
    externalTrackerRegexpPattern: string;
    /**
     * External issue tracker number format.
     */
    externalTrackerStyle: string;
    /**
     * URL of external issue tracker.
     */
    externalTrackerUrl: string;
}

export interface GetRepositoryExternalWiki {
    /**
     * URL of external wiki.
     */
    externalWikiUrl: string;
}

export interface GetRepositoryInternalTracker {
    /**
     * Let only contributors track time?
     */
    allowOnlyContributorsToTrackTime: boolean;
    /**
     * Enable dependencies for issues and pull requests?
     */
    enableIssueDependencies: boolean;
    /**
     * Enable time tracking?
     */
    enableTimeTracker: boolean;
}

export interface GetRepositoryPermissions {
    /**
     * Allowed to administer?
     */
    admin: boolean;
    /**
     * Allowed to pull?
     */
    pull: boolean;
    /**
     * Allowed to push?
     */
    push: boolean;
}

export interface GpgKeyEmail {
    email: string;
    verified: boolean;
}

export interface GpgKeySubkey {
    canCertify: boolean;
    canEncryptComms: boolean;
    canEncryptStorage: boolean;
    canSign: boolean;
    createdAt: string;
    expiresAt: string;
    id: number;
    keyId: string;
    primaryKeyId: string;
    publicKey: string;
}

export interface RepositoryExternalTracker {
    /**
     * External issue tracker URL format. Use the placeholders `{user}`, `{repo}` and `{index}` for the username, repository name and issue index.
     */
    externalTrackerFormat: string;
    /**
     * External issue tracker issue regular expression.
     */
    externalTrackerRegexpPattern: string;
    /**
     * External issue tracker number format.
     */
    externalTrackerStyle: string;
    /**
     * URL of external issue tracker.
     */
    externalTrackerUrl: string;
}

export interface RepositoryExternalWiki {
    /**
     * URL of external wiki.
     */
    externalWikiUrl: string;
}

export interface RepositoryInternalTracker {
    /**
     * Let only contributors track time?
     */
    allowOnlyContributorsToTrackTime: boolean;
    /**
     * Enable dependencies for issues and pull requests?
     */
    enableIssueDependencies: boolean;
    /**
     * Enable time tracking?
     */
    enableTimeTracker: boolean;
}

export interface RepositoryPermissions {
    /**
     * Allowed to administer?
     */
    admin: boolean;
    /**
     * Allowed to pull?
     */
    pull: boolean;
    /**
     * Allowed to push?
     */
    push: boolean;
}

