apiVersion: v1
kind: Secret
metadata:
  name: iptv-proxy-secret
type: Opaque
stringData:
  PROXY_USERNAME: ENC[AES256_GCM,data:XpsJlQ==,iv:VQZImsaj2vBolaETuOSCHM8RT9AHG3U9aWPqtZR2gTE=,tag:yG7sBHJbxAtpRf/AXIGk/w==,type:str]
  PROXY_PASSWORD: ENC[AES256_GCM,data:kueD8A==,iv:hvVdwyfIVu3Mjut1bNQPo8o2l0I/7KPC5uX5/dnbxbw=,tag:lBJC6iPK+gbv7ngMUa4RNA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVb0szQlFmcVh5SXZ5Tmht
        RGZ3d0FZWmNBTTZUL3ZUT3hFckhzbWF4TEg4CnNEMjhiV2hsY2pkT3VMZ0RUZU5h
        SWUvWU1HU1ZPZEU5MktIalkyU2NsTVkKLS0tIEVkMUp3NTlGS2p3S3B1TWd6UE11
        L0JjcTdBUlNreDBaUENTYk9iNDhNT00KVmXEoWgOfYzmzymPMbr4WYf0xQ/cwxY9
        t02oNUHW/eBEe4G1S0X3u+5F1bvXve0hZJoS4vLoyJC1RzmLYVxUng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUm1FSVFNVFFXNEZtNUZK
        TkkzaE9La1h0NzI2R1lubWV4RDg3R0h6cTBjCm8yZzNYcnk4UHFOWWcvVDBBR3RV
        Z09qc1dGYTRHZnR3c0MvQ1BkMURpVlkKLS0tIERxOEs3Y2cyMU5QcG5SdEw0QkNG
        Q3lQWjBBOWRCS2dEeSs2bHl4VTVJcm8KBKmdOSZFu4tiCkYlYqNYBWURQAzcaIxP
        svVpYHScqJ7kc3TMlBcZZ1+kIdmvUjpqkvS8wgz2ZNXv3xh1ZSeo3Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-05-22T20:05:08Z"
  mac: ENC[AES256_GCM,data:FSQeDvS/swv2MphmeuNDKxrttckdVwDokKdaDlvZ03XcMdofrCwpB/RQR8d1SrWzhCTA2cdoRGpG61RX4GGNE/YdwJFBAGEfOGH4cyydVyNDK2jVdEV6mxHQiB2HmPSbr5gwp7IGXxPoEW8Bc7FyVWKePk/3XdA3wujGURz6C+Y=,iv:fLI7TNnOf40826fwxFqvxDtcBV/lV4XoE8jYXwdz9dk=,tag:VxqynajPqV+yAjeaL37QqQ==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
