// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DatastoreMaintenanceMode {
    /**
     * Optional message presented for maintenance mode.
     */
    message?: pulumi.Input<string>;
    /**
     * Maintenance mode type. Valid values: `offline`, `read-only`.
     */
    type: pulumi.Input<string>;
}

export interface DatastoreNotify {
    /**
     * Garbage collection notification level. Valid values: `always`, `error`, `never`.
     */
    gc?: pulumi.Input<string>;
    /**
     * Prune job notification level. Valid values: `always`, `error`, `never`.
     */
    prune?: pulumi.Input<string>;
    /**
     * Sync job notification level. Valid values: `always`, `error`, `never`.
     */
    sync?: pulumi.Input<string>;
    /**
     * Verification job notification level. Valid values: `always`, `error`, `never`.
     */
    verify?: pulumi.Input<string>;
}

export interface DatastoreTuning {
    /**
     * Chunk iteration order. Valid values: `inode`, `none`.
     */
    chunkOrder?: pulumi.Input<string>;
    /**
     * Garbage collection access time cutoff in seconds.
     */
    gcAtimeCutoff?: pulumi.Input<number>;
    /**
     * Enable garbage collection access time safety check.
     */
    gcAtimeSafetyCheck?: pulumi.Input<boolean>;
    /**
     * Garbage collection cache capacity.
     */
    gcCacheCapacity?: pulumi.Input<number>;
    /**
     * Datastore fsync level. Valid values: `none`, `filesystem`, `file`.
     */
    syncLevel?: pulumi.Input<string>;
}

