services:
  technitium:
    restart: unless-stopped
    dns:
      - 100.100.100.100
    image: technitium/dns-server:15.2.0@sha256:23d3b63d959e997800b095fe93009b3fae271b5258234ff2ade8535cb33682c8
    container_name: technitium
    hostname: ${CLUSTER_KEY}
    env_file:
      - .env
    labels:
      traefik.enable: true

      # Admin web UI via local domain
      traefik.http.routers.technitium.rule: Host(`${CLUSTER_KEY}.dns.${ROOT_DOMAIN}`)
      traefik.http.routers.technitium.entrypoints: websecure
      traefik.http.routers.technitium.tls.certresolver: le
      traefik.http.routers.technitium.service: technitium-admin

      traefik.http.services.technitium-admin.loadbalancer.server.port: 5380

      # DNS over HTTPS (DoH)
      traefik.http.routers.technitium-doh.rule: Host(`${CLUSTER_KEY}.dns.${ROOT_DOMAIN}`) && Path(`/dns-query`)
      traefik.http.routers.technitium-doh.entrypoints: websecure
      traefik.http.routers.technitium-doh.tls.certresolver: le
      traefik.http.routers.technitium-doh.service: technitium-doh
      traefik.http.services.technitium-doh.loadbalancer.server.port: 5380
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "853:853/tcp"
      - "853:853/udp"
      - "8053:8053/tcp"
      - "8053:8053/udp"
      - "5380:5380/tcp"
      - "53443:53443/tcp"
    volumes:
      - /opt/stacks-data/${APP}/config:/etc/dns
      - /opt/stacks/traefik/certs:/etc/ssl/certs
    networks:
      - dockge_default
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
networks:
  dockge_default:
    external: true
x-dockge:
  urls:
    - https://${CLUSTER_KEY}.dns.${ROOT_DOMAIN}
    - http://${ipAddress}:5380
