# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret
type: Opaque
stringData:
  mosquitto_username: ENC[AES256_GCM,data:SG2CGFh4MCYX,iv:o0zgaY4qe7mpP30SzRBjZ3VytS3EzfEH5s6n9Yy5lh0=,tag:Q5fYI4639iGAOkvbakB1RA==,type:str]
  mosquitto_password: ENC[AES256_GCM,data:u93qTTA4RBqcacOdvFf7QAgk0AeSCXkfIxcSIN7h,iv:o0TWZwikag4zfLujCepgK/8/5WjVnnqu5X3AIbGp90U=,tag:1nDaM/KI1/ZsECEr/oz0ow==,type:str]
  mosquitto_pwd: ENC[AES256_GCM,data:S0mY4IRbaJkR2R0nfg1SKDfyOmaG2B8fkB04PFshd8D9WT2G31OuUBs=,iv:yJx3u/Rqt3MvaAPLr+oFclUERpnOD3QH41f5GnSUF1c=,tag:P/7kZ6OgjpBNBRT3MKIA+g==,type:str]
  mosquitto-0.conf: ENC[AES256_GCM,data:K23hU6BktljWLEjn7cdULhOws3pa76JBqKJMjR/05rwY17co2NQsotjgYGMOOl2KTC21H4whNVWw7SrTWFlnrd2fk04DqIMRHOz0VaBK98xWHWZJsheJxLK6O+AwU2roIstl65mhjeKORaqnYixPAvM6G0ZB9P54UasCspdXBJIlEJl8w6AdHrmzGOSgSfiNy6tImNr6P2pyCTo3pYE=,iv:Byihj/AZ+zmHSjf+dWy3pyLxjLuV9v1AiESDMVusrao=,tag:YF5ixQF3Qch4NfjZGJXdTA==,type:str]
  mosquitto-1.conf: ENC[AES256_GCM,data:+zK7HDld9iuqBJFYJnlR3+DhZe3eZpb2Wos1X4C9Rc7buHiwJk+Ll7eki0qfdrp3NK8ES76Y6veKRgkAwux8uPRqlcznc1ITq902yqx+pbaAv7KvVMuTFEMmk/CfO7t9FukcLmH03luY3rC5UxJFUA0+ts5HhTBnm0upYiJ7NbmC4Go/xCK0iFm6oAyIWfM7bWmkMxAvhSy6s/qOicsGFJ95xR3bHtlq4MbneJJKgSf4eUtfGETLUt66hjJ8Y5WOO0BIXu2hgcK1afadTsYDwkuQ8/W2l1H59R/k2PWw/k5JmVa/xbOL02MBFlu+XTg2cg58DAU=,iv:GJL06QklspUSF8pg4E/XhPKn2SHv8MLz6Rem39I5Lt4=,tag:Uz9IvUJDyJM6K+lZtMMGkw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VmI4cng4bzdKWVNuc3J2
        MTNGZllUVkJuK3d5OWlHMmI4QlFPaTdRelgwCjMrVWJZWDJtR0xIOGVqUjZjZnox
        QWc2K1E2MG9OYno1MXVUa25nSWRrMXMKLS0tIEk4L1QwcEJ1djNsd09NelcwSWJv
        cmhobnI0MDd5dXpJRkR5ZGlHbVZ6ZjgKKt2b5f5mFAYeZH8HYltsCsh5oGN+Smmp
        UpDrA2fLVATS9JBKgsf2zNbEk/FqDFKSHY88j3VReiCLdMoP0jZvWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eurl2t7pepw66guv8m7lxh5fjhs4t4frsntqjp08lmypwudlsp7qdusgnf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUEpmMGFyczQrd2FhY1FM
        b2FOc1Vmam1SSW8rakVSdUpKWWNNaEdqNjNBCmtHM05YY2lrZkJhQmp3K09GcWFC
        ZWwwNFI2c016N3ZNMlBmMVZ6OVA3L1kKLS0tIDY0NHRzWHhJTTJFaEJQa0FweGw5
        SFY1azdaRFJzaThQT0YyRjNrMlV0TzgKWQ6je0Q+fgFFSUt/mGTSVq3e8v99wtQF
        tgmHT/kUNYb/JIG6nVRGLV7+6L6z7jvDAtVY4lNcO/fG37XJPzZ4DQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age150z0s36kl9vud8728c5e4zqq6nmyywekk76rwvjclcsfc8mrxuuqr0qfg6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-08-21T19:30:08Z"
  mac: ENC[AES256_GCM,data:MNfAvbZw6FRqAbXedrSqepgAatFuwN/60ofNGN6oypYgDXc3ohsML2VTQ91NOGbhpQvgaLcgHRHLekBQlMJFZn0wtydND2B4JJkyzPvQHQpbSrNang5zmSB0kBrB9qYNCEpRY95mFo/mM9B6GsXdjbJxjNFfSxJaE8R13FyxbmI=,iv:UDfWJnqnJbyI7Vkb7LG9zc0vq/4uv1Np8QHmYDi6pok=,tag:BTNc6EOCxRF0m6qyrKceFA==,type:str]
  mac_only_encrypted: true
  version: 3.10.2
