// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDevices(args?: GetDevicesArgs, opts?: pulumi.InvokeOptions): Promise<GetDevicesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("tailscale:index/getDevices:getDevices", {
        "devices": args.devices,
        "filters": args.filters,
        "namePrefix": args.namePrefix,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDevices.
 */
export interface GetDevicesArgs {
    devices?: inputs.GetDevicesDevice[];
    filters?: inputs.GetDevicesFilter[];
    namePrefix?: string;
}

/**
 * A collection of values returned by getDevices.
 */
export interface GetDevicesResult {
    readonly devices?: outputs.GetDevicesDevice[];
    readonly filters?: outputs.GetDevicesFilter[];
    readonly id: string;
    readonly namePrefix?: string;
}
export function getDevicesOutput(args?: GetDevicesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDevicesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("tailscale:index/getDevices:getDevices", {
        "devices": args.devices,
        "filters": args.filters,
        "namePrefix": args.namePrefix,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDevices.
 */
export interface GetDevicesOutputArgs {
    devices?: pulumi.Input<pulumi.Input<inputs.GetDevicesDeviceArgs>[] | undefined>;
    filters?: pulumi.Input<pulumi.Input<inputs.GetDevicesFilterArgs>[] | undefined>;
    namePrefix?: pulumi.Input<string | undefined>;
}
