
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app readarr-audio
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  interval: 1h
  driftDetection:
    mode: enabled
  timeout: 10m
  install:
    createNamespace: true
    replace: true
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: -1
      strategy: rollback
  rollback:
    force: true
    cleanupOnFail: true
    recreate: true
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        initContainers:
          restore:
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: true
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
              capabilities: { drop: ["ALL"] }
            image:
              repository: busybox
              tag: 1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
              pullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
            args: |-
                chown -R 568:568 /config
                chmod -R 777 /config
                echo "Done.";
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/readarr
              tag: 0.4.18@sha256:8f7551205fbdccd526db23a38a6fba18b0f40726e63bb89be0fb2333ff4ee4cd
            # -- environment variables.
            # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
            env:
              PUID: ${PUID}
              PGID: ${PGID}
              UMASK: 002
              READARR__APP__INSTANCENAME: Readarr (Audio)
              READARR__APP__THEME: dark
              READARR__AUTH__METHOD: External
              READARR__AUTH__REQUIRED: DisabledForLocalAddresses
              READARR__AUTH__APIKEY:
                valueFrom:
                  secretKeyRef:
                    name: readarr-apikey
                    key: apikey
              READARR__LOG__DBENABLED: "False"
              READARR__LOG__LEVEL: info
              READARR__PORT: &port 8787
              TZ: ${TIMEZONE}
            # probes:
            #   liveness: &probes
            #     enabled: true
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /ping
            #         port: *port
            #       initialDelaySeconds: 10
            #       periodSeconds: 20
            #       timeoutSeconds: 10
            #       failureThreshold: 5
            #   readiness: *probes
            securityContext:
              runAsNonRoot: true
              runAsUser: 568
              runAsGroup: 568
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 4Gi

    defaultPodOptions:
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    # -- Configures service settings for the chart.
    service:
      app:
        controller: app
        type: ClusterIP
        ports:
          http:
            port: *port


    persistence:
      config:
        existingClaim: readarr-audio-config
        globalMounts:
          - path: /config
      truenas-media:
        existingClaim: truenas-media
        globalMounts:
          - path: /media/downloads
            subPath: downloads
          - path: /media/ebooks
            subPath: ebooks


    route:
      app:
        parentRefs:
          - name: internal
            namespace: network
            kind: Gateway
        hostnames:
          - "${APP}.${ROOT_DOMAIN}"
        kind: HTTPRoute
        rules:
          - backendRefs:
              - identifier: app
                port: *port
            filters:
              - type: ExtensionRef
                extensionRef:
                  group: traefik.io
                  kind: Middleware
                  name: local-user
        annotations:
          gethomepage.dev/widget.url: "http://${APP}.${INTERNAL_CLUSTER_SERVICE}:8787"
          # gethomepage.dev/widget.key: ""
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media Management
          gethomepage.dev/icon: readarr.svg
          gethomepage.dev/name: Readarr (Audio)
          gethomepage.dev/widget.type: readarr
          gethomepage.dev/namespace: "{{ .Release.Namespace }}" # The kubernetes namespace the app resides in
          gethomepage.dev/app: "${APP}"
